<?php
/*
 * Bulgarian translation by Stanimir Koruev
 */
define("bg_A_DEPT", "отдел .");
define("bg_A_PRIORITY", "приоритет");
define("bg_ACCESS_DENIED", "Достъпът отказан.");
define("bg_ACTION_DENIED_TICKET_LOCKED", "Достъпът отказан. Билета е заключен от някой друг!");
define("bg_ACTION_DENIED", "Операцията отказана");
define("bg_ACTIVE", "Активирай");
define("bg_ADD_NEW_PREMADE_REPLY", "Добавяне на нов предварително направен Отговор");
define("bg_ADD_NEW_USER", "Добави нов потребител");
define("bg_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "Електронната поща на Админа получава сигнал по подразбиране. Изберете допълнителни получатели по-долу");
define("bg_ADMIN_EMAIL", "Емайл на администратор");
define("bg_ADMIN_PANEL", "Администратор панел");
define("bg_ADVANCED", "Напреднал");
define("bg_ALERT_FROM_EMAIL_ADDRESS", "Аларма(и) ОТ ЕМАЙЛ АДРЕС");
define("bg_ALERT_SUBJECT_MISSING", "Обекта на съобщението липсва");
define("bg_ALERTS_NOTICES", "Съобщения &amp; бележки");
define("bg_ALL_DEP", "Всички отдел");
define("bg_ALL_DEPTS", "Всички катедри");
define("bg_ALL", "All");
define("bg_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Позволете клиент да презапишете/зададе приоритет(онлайн билети)");
define("bg_ALLOWED_FILE_EXT_REQ", "Позволени файлови разширения, които се изискват");
define("bg_ALLOWED", "позволено");
define("bg_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "Изпратен е имейл с номера на билета");
define("bg_ANOTHER_DEPT_USING_HOST_COMBINATION", "Друг отдел използва този преносител/потребител комбинация.");
define("bg_ANSWER", "Отговорен");
define("bg_API_SETTINGS_UPDATED", "API опции обновени");
define("bg_ARE_YOU_SURE_YOU_WANT", "Наистина ли искате да");
define("bg_ASSIGN", "възлага");
define("bg_ASSIGNED_STAFF", "Целеви персонал");
define("bg_ASSIGNED_TICKETS", "Целеви Билет");
define("bg_AT_LEAST_ONE_TOPIC", "поне една тема");
define("bg_ATTACH_FILE", "Прикачване на файл");
define("bg_ATTACH_SETTINGS_UPDATED", "Прикачени настройки се обновени");
define("bg_ATTACH", "Прикачи");
define("bg_ATTACHMENT_DISABLED", "Прикачването изключено");
define("bg_ATTEMPTS", "Опити");
define("bg_AUTHENTICATION_REQUIRED", "Изисква се идентификация");
define("bg_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Автоматично възобновява на билети до последния ответник 'ПОЗВОЛЕНО'. (<i> лимит 3 месеца</i>)");
define("bg_AUTOLOCK_TIME", "Автоматично заключване след");
define("bg_AUTORESPONDERS_GLOBAL_SETTING", "Автоматичен отговор &nbsp;(Глобални настройки)");
define("bg_AUTORESPONDERS", "Автоматичен отговор");
define("bg_AUTORESPONSE_FROM_EMAIL", "Автоматичен отговор ОТ ЕМАЙЛ");
define("bg_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Автоматичен отговор включва Номер на билета който се изисква да проверите статуса на билета");
define("bg_BAD_PREFIX_UNDERSCORE", "Лош префикс. Трябва да се подчертае (_) На края. например 'ost_'");
define("bg_BAN_EMAIL_LOWER", "Блокирай Емайл");
define("bg_BYTES_ALLOWED", "Байтовете позволени");
define("bg_CAN_BE_APPENDED_TO_RESPONSES", "могат да бъдат приложени към отговорите.&nbsp;(достъпно за избор за обществени служби)  ");
define("bg_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "Не може да изтрие одели свързани с помощните теми. Премахване на свързването на първо място.");
define("bg_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "Не може да изтрие одели . С членове. Преместете служителите първо.");
define("bg_CANCEL", "Отказ");
define("bg_CATEGORY", "Категория");
define("bg_CELL_PHONE", "Мобилен телефон");
define("bg_CHANGE_PASS", "Промени парола");
define("bg_CHANGE_PRIORITY", "change_priority");
define("bg_CHECK_STATUS_OPENED_TICKETS", "Проверка на състоянието на открит по-рано билет. Ние предлагаме архивите и историята на всички искания за подкрепа, пълни с отговори.");
define("bg_CHECK_STATUS", "Провери статус");
define("bg_CLICKABLE_URL", "Натискащи се URLs");
define("bg_CLIENT_SESSION_TIMEOUT_IN_MINS", "Клиентски максимум път за минута. Въведи 0 да деактивирате изчакване");
define("bg_CLIENT_SESSION_TIMEOUT", "Клиентска серия на изчакване");
define("bg_CLOSE_LOWER", "затвори");
define("bg_CLOSE_REOPEN_TICKETS", "затвори/отвори билет");
define("bg_CLOSE", "Затвори");
define("bg_CLOSED", "Затворен");
define("bg_COMMERCIAL_SUPPORT_AVAILABLE", "Подпомагане на търговията включено");
define("bg_CONF_FILE_ALREADY_MOD", "Конфигурационният файл вече е променен!");
define("bg_CONF_FILE_NOT_WRITABLE", "Конфигурационен файл не е записваем");
define("bg_CONFIRM_NEW_PASS", "Потвърди нова парола");
define("bg_CONFIRM", "потвърди");
define("bg_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Конфликти с система за електронна поща отгоре");
define("bg_CONTACT_ADMIN", "Свържи се с администратор ако мислиш че това е грешка");
define("bg_CREATE_DATE", "Създай дата");
define("bg_CURR_PASS_REQ", "Изисква се текуща парола");
define("bg_CURR_TIME", "Сегашно време");
define("bg_DATE_AND_TIME_FORMAT", "Дата &amp; Формат на Час");
define("bg_DATE_AND_TIME", "Дата &amp; Час");
define("bg_DATE_FORMAT", "Формат на дата");
define("bg_DAY_DATE_TIME_FORMAT", "Ден, Дата &amp; Формат на Час");
define("bg_DAYLIGHT_SAVING", "Спестяване от дневна светлина");
define("bg_DAYLIGHT_SAVINGS", "Спестявания от дневна светлина");
define("bg_DB_NOT_EXISTS", "База данни не съществува");
define("bg_DEFAULT_DEPARTMENT", "отдел под подразбиране");
define("bg_DEFAULT_EMAIL_TEMPLATE", "Имейл шаблон под подразбиране");
define("bg_DEFAULT_EMAIL", "Емейл под подразбиране");
define("bg_DEFAULT_PAGE_SIZE", "Големина на страница под подразбиране");
define("bg_DEFAULT_PRIORITY", "Приоритет под подразбиране");
define("bg_DEFAULT_TIMEZONE", "Времева зона под подразбиране");
define("bg_DELETE_DEPS", "Изтрий департаменти");
define("bg_DELETE_LOWER", "изтрий");
define("bg_DELETE_TICKETS", "изтрий билети");
define("bg_DELETE", "Изтрий");
define("bg_DEPARTMENT_MANAGED", "Мениджър департаменти(нежелана поща)");
define("bg_DEPARTMENT_MANAGER", "Мениджър департаменти");
define("bg_DEPARTMENT_MEMBERS", "Мениджър Потребители (нежелана поща)");
define("bg_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Департаменти под който 'отговора' ще бъде възможен");
define("bg_DEPARTMENTS", "Департаменти");
define("bg_DEPENDS_ON_THE_TAG_BELOW", "зависи от таговете отдолу ");
define("bg_DEPT_DEPENDS_ON_EMAIL", "отдел зависи от емайла &amp; който ще помогне на настройки за входящи билети.");
define("bg_DEPT_EMAIL_ABOVE", "Емайли на отдели(по-горе)");
define("bg_DEPT_EMAIL", "Емайли на отдели");
define("bg_DEPT_MANAGER", "Мениджър на отдели");
define("bg_DEPT_NAME", "Име на департамент");
define("bg_DEPT_SIGNATURE", "Подпис на отдел");
define("bg_DEPT_TRANSFER", "пренос на отдел");
define("bg_DEPT_TYPE", "Тип на отдел");
define("bg_DEPT", "Департамент");
define("bg_DIR_MUST_BE_VALID_WRITABLE", "Директорията трябва да е валидна и записваема .");
define("bg_DIRECTORY", "Директория");
define("bg_DISABLE", "Изключи");
define("bg_DISABLED", "Изключен");
define("bg_DO_REQUESTED_ACTION", "направи исканото действие");
define("bg_EDIT_PREMADE_REPLY", "Редактиране на предварително направени отговори");
define("bg_EMAIL_ADD_SUCCESS", "Емайла добавен успешно");
define("bg_EMAIL_ADDED_TO_BANLIST", "Емайла е добавен в бан листа");
define("bg_EMAIL_ADDRESS", "Емайл адрес");
define("bg_EMAIL_ALREADY_BANNED", "Емайла вече е банат");
define("bg_EMAIL_ALREADY_EXISTS", "Емайла вече съществува");
define("bg_EMAIL_IN_BANLIST", "Елайла е в банлиста. Трябва да се извади за да отговори");
define("bg_EMAIL_MISMATCH", "Емайла не съвпада.");
define("bg_EMAIL_REMOVED", "Емайла премахнат");
define("bg_EMAIL_SETTINGS", "Настройки на емайл");
define("bg_EMAIL_UNKNOWN", "Непознат емайл");
define("bg_EMAIL_UPDATED_SUCCESS", "Емайла качен успешно");
define("bg_ENABLE_AUTOCRON", "Активиране Auto Cron");
define("bg_ENABLE_CRON_CALL", "Активиране cron обаждане за дейността на персонала");
define("bg_ENABLE_EMAIL_PIPING", "Активиране на тръбопроводи на имейл");
define("bg_ENABLE_POP3_EMAIL_FETCH", "Активиране POP3 носител на емайл");
define("bg_ENABLE", "Активиране");
define("bg_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Разрешаване грешки те се изпращат на администратор имейл посечен по-горе");
define("bg_ENTER_MESSAGE", "Добави съобщение");
define("bg_ENTER_VALID_NUM", "Добави валиден номер");
define("bg_ERR_SQL_SYNTAX", "Вие имате грешка в SQL syntax ");
define("bg_ERROR_OCCURED", "Възникна грешка(и).");
define("bg_ERROR_OCCURRED", "Възникнала е грешка. Виж съобщението по-долу.");
define("bg_EXCESSIVE_LOGIN_ATTEMPTS", "Прекалено много опити за влизане");
define("bg_FATAL_ERROR", "Фатална грешка");
define("bg_FETCH_INTERVAL_REQUIRE", "Извежда се изисквания интервал.");
define("bg_FILE_TOO_BIG", "Файла е прекалено голям");
define("bg_FILE_UPLOAD_DISABLED_PHP_INI", "'file_uploads' директива е забранен в php.ini");
define("bg_FIRST_NAME", "Име");
define("bg_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "За POP3 емайл доставка да работи трябва и cron да работи или просто активирайте автоматичен-cron");
define("bg_FORGOT_LOGIN_INFO", "Забравил си паролата? Моля <a href=\"open.php\">отвори нов билет</a>.");
define("bg_FROM_BANLIST", "от бан листа");
define("bg_FULL_NAME", "Име");
define("bg_GENERAL_INQUIRY", "Общо запитване");
define("bg_GENERAL_SETTINGS", "Общо настройки");
define("bg_GET_A_PEACE_OF_MIND", "Вземи спокойствие.");
define("bg_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "Общия автоматичния говорител трябва да е включен за да може настройките да заемат ефект.");
define("bg_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "Обща настройка която може да бъде спряна по нивото на емайла.");
define("bg_HELP_TOPIC", "Помощна тема");
define("bg_HELPDESK_NAME", "Помощен отдел Име/Титла");
define("bg_HELPDESK_STATUS", "Помощен отдел Статус");
define("bg_HELPDESK_URL", "Помощен отдел URL");
define("bg_HELPS_WITH_SPAM", "Помага при спам и контрол на наводненията. Въведи 0 за неограниченост");
define("bg_HOME", "Начало");
define("bg_HOST_MISSING", "Липсва преносител");
define("bg_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Часове преди билета да е маркиран като забавен. Въведи 0 за да изключиш.");
define("bg_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "Ако е включен билета получава автоматично подновяване на формална дейност.");
define("bg_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "Ако искате да изпратите допълнителни коментари или информация по отношение на един и същ въпрос, моля, следвайте инструкциите на електронната поща.");
define("bg_IMAP_DOESNT_EXISTS", "IMAP не съществува. PHP трябва да бъде компилиран с поддръжка за IMAP.");
define("bg_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "За да се рационализират исканията за помощ иза да може да ви служи по добре ние използваме система за помощни билети.Всяко искане на помощ присвоява уникален номер на билет ,който можете да използвате, за да следите напредъка и отговорите ни онлайн.За ваше сведение, ние предлагаме цялостни архиви и история на всички искания за помощ.");
define("bg_INDICATE_SOURCE", "Посочете източник");
define("bg_INSTALL_COMPLETE", "Поздравления osTicket основната инсталация завършена!");
define("bg_INTERNAL_ERROR_OCCURED", "Възникна вътрешна грешка");
define("bg_INTERNAL_ERROR", "Вътрешна грешка. Моля, уверете се, че си изтеглили най-новата ");
define("bg_INTERNAL_NOTE_POSTED", "Вътрешна записка е побликувана");
define("bg_INVALID_ATTACH", "Невалидно прикачване");
define("bg_INVALID_FILE_TYPE", "Невалиден тип на файла");
define("bg_INVALID_FILE", "Невалиден файл");
define("bg_INVALID_LOGIN", "Невалиден вход");
define("bg_INVALID_SOURCE", "Невалиден източник");
define("bg_INVALID_SQL_SCHEMA", "Невалидна SQL схема. Получаване на помощ от страна на предприемачите");
define("bg_INVALID_UPLOAD_DIR", "Невалидна директория за качване");
define("bg_INVALID", "Невалиден");
define("bg_KNOWLEDGE_BASE", "База знания");
define("bg_LANG_PRIVATE", "Частен");
define("bg_LANG_PUBLIC", "Публичен");
define("bg_LAST_NAME", "Фамилия");
define("bg_LAST_RESPONDENT", "Последен  Респондер");
define("bg_LAST_UPDATED", "Последно качени");
define("bg_LOCK", "Заключи");
define("bg_LOCKED", "Заключен");
define("bg_MAIL_METH", "Метод Поща");
define("bg_MAIL_PARSE_ERRORS", "Грешки на пощенските кутии при разбора");
define("bg_MAKE_PRIVATE", "Направи частна");
define("bg_MAKE_PUBLIC", "Направи публична");
define("bg_MAKE_URL_CLICKABLE", "Направи URLs достъпно");
define("bg_MANAGER", "Мениджър");
define("bg_MASS_MANAGE_TICKETS", "маса управлява билети. Свържи се с администратор за такъв достъп");
define("bg_MAX_ALLOWED", "Максимално позволени.");
define("bg_MAX_FILE_SIZED_REQ", "Изисква се максималната големина на файла");
define("bg_MAX_LOGIN_ATTEMPTS", "Вие сте достигнали максималната неуспешни опита за влизане. Опитайте отново след 5 минути или <a href=\"open.php\">отворете нов билет</a>");
define("bg_MAX_OPEN_TICKETS", "Максимални <b>отворени</b> Билети");
define("bg_MAX_PAGE_SIZE", "Максимална големина на страницата");
define("bg_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Съобщение приложено към съществуващия потвържден билет");
define("bg_MESSAGE_POSTED_SUCCESS", "Съобщение, публикувано успешно");
define("bg_MESSAGE_REQUIRED", "Задължително Съобщение");
define("bg_MESSAGE", "Съобщение");
define("bg_MIN_TO_LOCK_A_TICKET", "Минути, за да заключите билет за дейността. Въведете 0 за да деактивирате заключване");
define("bg_MISSING_MESSAGE", "Липсва ID на билета");
define("bg_MISSING_OR_INVALID_GROUP", "Липсваща или невалидна група");
define("bg_MISSING_SQL_SCHEMA", "Липсва SQL Схема");
define("bg_MOBILE", "Мобилен");
define("bg_MUST_BE_SIX_CHARS", "Трябва да е минимум 6 символа");
define("bg_MUST_SELECT_PRIORITY", "Трябва да изберете приоритет");
define("bg_MY_ACCOUNT", "Моя акаунт");
define("bg_MY_PREFERENCES", "Моите настройки");
define("bg_MY_PROFILE_INFO", "Информация за профила ми");
define("bg_MY_PROFILE", "Моя профил");
define("bg_NAME", "Име");
define("bg_NEED_HELP_QUESTION", "Нужда от помощ?");
define("bg_NEW_DEPT", "Нов департамент");
define("bg_NEW_MESSAGE_ALERT", "Ново съобщение за известие");
define("bg_NEW_MESSAGE", "Ново съобщение");
define("bg_NEW_PASS_NOT_MATCH", "Новата парола(и) несъвпада");
define("bg_NEW_PASS_REQ", "Изисква се нова парола");
define("bg_NEW_PASS_SAME_OLD", "Нова парола е същата като старата парола");
define("bg_NEW_PREMADE_REPLY", "Нов предварително направени Отговор");
define("bg_NEW_TICKET_ALERT", "Ново съобщение на аларма");
define("bg_NEW_TICKET", "Нов билет");
define("bg_NO_ACCESS_TO_TICKET", "Нямате достъп до този билет");
define("bg_NO_PERMISSION_TO_REASSIGN", "Вие нямате разрешение да присвоите отново възложения билети");
define("bg_NO_PERMISSION_TO", "Нямате позволение да");
define("bg_NO_REPLY_EMAIL_ADDRESS", "Няма отговор на емайл");
define("bg_NO_REPLY_EMAIL", "Няма емайл");
define("bg_NO_STAFF_FOUND", "Няма намерен персонал");
define("bg_NO_SUCH_FILE", "Няма такъв файл");
define("bg_NO_TICKETS_FOUND", "Няма такъв билети.");
define("bg_NO_TICKETS_SELECTED", "Няма избран билет. Трябва да изберете поне един билет.");
define("bg_NO_USER_ADD_USER", "Няма потребител (Добави потребител)");
define("bg_NONE", "нищо");
define("bg_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "Вие нямате право да променят приоритета на билета");
define("bg_NOT_ALLOWED_TO_TRANSFER_TICKETS", "Вие нямате право да прехвърлите билети.");
define("bg_NOTE_REQ", "Изисква се съобщение в забележка ");
define("bg_NOTE_REQUIRED", "Изисква се Забележка/Съобщение");
define("bg_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Забележката е изпратена до потребител 'Без отговор по емайл' като има предвид, че сигнали за използване на персонал 'Алармен Емайл' определени по-горе от адрес съответно.");
define("bg_OBSERVE", "Наблюдавай");
define("bg_OF", "di");
define("bg_OFFICE_PHONE", "Служебен телефон");
define("bg_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "Офлайн режим ще деактивира клиентски интерфейс и <b>само</b> позволени <b>супер админи</b>ще могат да влезат в персоналния Control Panel");
define("bg_OFFLINE", "Извън линия");
define("bg_ONLINE", "На линия");
//define("bg_OPEN_LOWER", "отворен");
define("bg_OPEN_NEW_TICKET", "Отвори нов билет");
define("bg_OPEN_TICKET", "Отвори билет");
define("bg_OPEN", "Отвори");
define("bg_OSTICKET_BASIC_INSTALL", "osTicket основната инсталация");
define("bg_OSTICKET_INSTALLER", "osTicket Installer");
define("bg_OSTICKET_REQUIRES_MYSQL", "osTicket изисква MySQL 4.1.1 или по нова! Моля обновете");
define("bg_OUTGOING_EMAIL", "Изходящ Email");
define("bg_OVERDUE_LOWER", "закъснял");
define("bg_OVERDUE_TICKET_ALERT", "Аларма просрочени билет ");
define("bg_OVERLIMIT_NOTICE", "Над ограниченията предизвестие");
//define("bg_PAGE", "страница");
define("bg_PASS_CHANGE_SUCCESS", "Паролата сменена успешно");
define("bg_PASS_TO_NOT_MATCH", "паролата не съвпада!");
define("bg_PASSWORD_REQUIRED", "Изисква се парола");
define("bg_PER_EMAIL", "през емайл");
define("bg_PERM_DENIED", "Перм. Отказан достъп.");
define("bg_PHONE_NUM_REQ", "Изисква се Телефон # ");
define("bg_PHONE", "Phone");
define("bg_PHP_DATE_MANUAL", "Моля, вижте <a href=\"http://php.net/date\" target=\"_blank\">PHP Инструкции</a> за поддържаните параметри.");
define("bg_PHP_OUT_OF_DATE", "PHP инсталация сериозно извън от датата");
define("bg_PHRASE_TOO_SHORT", "фраза е твърде кратка!");
define("bg_PHRASE_TWO_WORDS", "Фраза от 2 + думи");
define("bg_PLEASE_ENTER_VALID_EMAIL", "Моля, въведете валиден имейл адрес.");
define("bg_PLEASE_FILL_TO_OPEN_A_TICKET", "Моля попълнете формата по-долу, за да отворите нов билет.");
define("bg_POSSIBLE_ERROR_DETECTED", "Възможни открити грешки, моля, проверете предупрежденията по-долу");
define("bg_POSSIBLY_ACCESS_DENIED", "Възможно е достъпът да е отказан, ако смятате, че това е грешка, моля да техническа поддръжка.");
define("bg_POSSIBLY_INVALID_TICKET", "Възможно е невалиден билет ID");
define("bg_POST_REPLY", "Отговорете");
define("bg_POSTNOTE", "бележка");
define("bg_PREF_ERROR", "Грешка предпочитания актуализация.");
define("bg_PREF_UPDATED", "Предпочитания обновени успешно");
define("bg_PREFERENCES", "Предпочитания");
define("bg_PREFERRED_TIMEZONE", "Предпочитани времеви зони");
define("bg_PREMADE_REPLIES", "предварително направени Отговори");
define("bg_PREMADE_REPLY", "предварително направени Отговор");
define("bg_PRIMARY_OUTGOING_MAIL", "Първичен Изходящ Email");
define("bg_PRIORITY_CHANGED_SUCCESS", "Приоритет променена успешно");
define("bg_PRIORITY", "Приоритет");
define("bg_PRIVATE_HIDDEN", "Личен(Скрит)");
define("bg_PROBLEM_CHANGING_PRIORITY", "Проблеми при промяна приоритет.");
define("bg_PROBLEM_CLOSING_TICKET", "Проблеми при затваряне на билет.");
define("bg_PROBLEM_RELEASING_TICKET", "Проблеми при освобождаване на билет.");
define("bg_PROBLEM_REOPENING_TICKET", "Проблеми при възобновяване на билета.");
define("bg_PROBLEMS_ADMIN_PAGE", "Проблеми със зареждането при поискването на страницата за администриране.");
define("bg_PROBLEMS_DELETING_THE_TICKET", "Проблеми при изтриване на билета");
define("bg_PROBLEMS_DISPLAYING_DIR", "Проблеми с показването на директория");
define("bg_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Проблеми при маркиране на билет като закъсняла");
define("bg_PROCESS", "процес");
define("bg_PROF_INST_AVAILABLE", "Професионален монтаж на разположение");
define("bg_PROFILE_UPDATE_SUCCESS", "Профил обновени успешно");
define("bg_PUBLIC", "Обществен");
define("bg_QUERY", "Запитване");
define("bg_RANDOM", "Sлучаен");
define("bg_RECOMMENDED", "препоръчва");
define("bg_REJECTED", "отхвърлена");
define("bg_RELEASE_LOWER", "Oсвободи");
define("bg_REMOVING_QUOTED_REPLY", "Премахване цитат от отговора");
define("bg_REOPEN_LOWER", "възобнови");
define("bg_REOPEN", "Възобнови");
define("bg_REOPENED_TICKETS", "Възобновява билети");
define("bg_REPLY_REQUIRED", "Изисква се отговор");
define("bg_REPLY_SEPARATOR_TAG", "Отговор Separator Tag");
define("bg_REPLY_TITLE", "Отговор Заглавие");
define("bg_REPLY", "отговор");
define("bg_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Задължително при отдел е публична");
define("bg_REQUIRED", "изисква");
define("bg_RESET_CHANGES", "Рестартирай Промени");
define("bg_RESET", "Reset");
define("bg_RESPONSE_MESSAGE_REQUIRED", "Необходим отговорно съобщение");
define("bg_RESPONSE_POSTED_SUCCESS", "Отговор Публикувано успешно");
define("bg_SALVE_EMAIL_HEADERS", "Запазване на имейл заглавки");
define("bg_SAVE_CHANGES", "Запазване на промените");
define("bg_SAVE_RAW_HEADERS", "Запазване на суровини заглавията");
define("bg_SAVE", "Запамети");
define("bg_SEARCH_FOR", "Търсене за");
define("bg_SEARCH_TERM_MORE_THAN_3_CHARS", "Думата за търсене трябва да бъде повече от три символа");
define("bg_SEARCH", "Търси");
define("bg_SECURITY_VIOLATION", "Нарушение за сигурност . Повторно нарушение ще доведе до вашия профил се заключи.");
define("bg_SELECT_ASSIGNEE", "Изберете синдика");
define("bg_SELECT_DEFAULT_DEPT", "Избор Отдел По подразбиране");
define("bg_SELECT_DEPARTMENT", "Изберете отдел");
define("bg_SELECT_HELP_TOPIC", "Изберете помощната тема");
define("bg_SELECT_MANAGER_OPT", "Изберете диспечер (по избор)");
define("bg_SELECT_ONE", "Избери едно");
define("bg_SELECT_RECIPIENTS", "Избор на получатели");
define("bg_SELECT", "Избери");
define("bg_SELECTED_DEPT_DELETED", "избрани отдели изтрита");
define("bg_SELECTED_EMAILS_DELETED", "избрания(те) поща(и) Изтрити");
define("bg_SELECTED_EMAILS_REMOVED", "избрани имейли отстранен от банове");
define("bg_SELECTED_EMAILS_USED_BY_A_DEPT", "Един или повече от избраните имейли се използва от катедра Премахване на свързването първа.");
define("bg_SELECTED_ENTRIES", "избраните записи");
define("bg_SELECTED_REPLIES_DELETED", "Избраните отговори изтрита");
define("bg_SELECTED_REPLIES_DISABLED", "Избраните отговори са изключени");
define("bg_SELECTED_REPLIES_ENABLED", "Избраните отговори включен");
define("bg_SELECTED_SERVICES_ENABLED", "избраните услуги са включени");
define("bg_SELECTED_TICKETS_CLOSED", "избраните билети затворени");
define("bg_SELECTED_TICKETS_DELETED", "избраните билети изтрити");
define("bg_SELECTED_TICKETS_OVERDUE", "избраните билети отбелязани като закъсняла");
define("bg_SELECTED_TICKETS_REOPENED", "избраните билети възобновени");
define("bg_SELECTED_TICKETS", "избраните билети");
define("bg_SELECTED_TOPIC_DISABLED", "избраните теми са изключени");
define("bg_SELECTED_TOPICS_DELETED", "избраните теми са изтрити");
define("bg_SELECTED_USERS", "избран потребител (и)");
define("bg_SEND_OVERLIMIT_NOTICE", "Изпращане на известие Надвишение");
define("bg_SENT_ONLY_ONCE", "Изпрати <b>само веднъж</b> на нарушение на ограничението на потребителя. <b>Админа ще е известен по подразбиране/b>");
define("bg_SEQUENTIAL", "следващ");
define("bg_SERVER_TIME", "Време на сървъра");
define("bg_SESSION_TIMED_OUT", "Сесията изтече поради бездействие");
define("bg_SHOW_ASSIGNED_TICKETS", "Покажи възложени билети на открита опашката");
define("bg_SHOWING", "Показване");
define("bg_SIGNATURE", "Подпис");
define("bg_SORT_BY", "Сортирай по");
define("bg_SQL_ERRORS", "SQL проблем");
define("bg_STAFF_MAX_IDLE_TIME", "Максимален режим на персонала път в минута. Въведете 0 за да деактивирате изчакване");
define("bg_STAFF_MEMBERS", "Членовете на персонала");
define("bg_STAFF_PANEL", "Персонал панел");
define("bg_STAFF_SESSION_TIMEOUT", "Почивка за персонална сесия");
define("bg_STATUS", "Статус");
define("bg_STRIP_QUOTED_REPLY", "Цитиран Отговор");
define("bg_SUBJECT_MISSING", "предмета липсва");
define("bg_SUBJECT", "Предмет");
define("bg_SUBMIT_A_NEW_REQUEST", "Изпращане на ново искане за ПОМОЩ. Моля, дайте колкото е възможно повече подробности, така че най-добре можем да ви помогнем. За да актуализирате представен преди билет, моля използвайте формата вдясно. Изисква се валиден имейл адрес.");
define("bg_SUMMARY_OF_THE_ISSUE_REQUIRED", "Обобщение на изискваната емисия");
define("bg_SUPPORT_OFFLINE", "Помощната система е временно исключена");
define("bg_SUPPORT_TEAM", "Помощен екип");
define("bg_SUPPORT_TICKET_CREATED", "Билета е създаден");
define("bg_SUPPORT_TICKET_REQ_DENIED_FOR", "Билета за поддръжка е отказано от ");
define("bg_SUPPORT_TICKET_SYSTEM", "Система за онлайн помощ");
define("bg_SYSTEM_ADMIN_EMAIL_ADDRESS", "Администраторски емайл адрес");
define("bg_SYSTEM_ERRORS", "Системна грешка");
define("bg_SYSTEM_OFFLINE", "Системата е извън линия");
define("bg_SYSTEM_PREFERENCES_AND_SETTINGS", "Системни предпочитания и настройки");
define("bg_TABLE_PREFIX", "Таблица префикс");
define("bg_TEMPLATE_ALERT_MSG_REQUIRED", "Съобщение Шаблон на сигнала");
define("bg_TEMPLATE_MSG_REQUIRED", "Шаблона изисква съобщение");
define("bg_TEMPLATES_UPDATED_SUCCESS", "Шаблони обновени успешно");
define("bg_THANK_YOU_FOR_CHOOSING_OSTICKET", "Благодарим Ви, че избрахте osTicket.\nУверете се, че да се присъедините osTicket форум http://osticket.com/forumsда остане UPTO датата на последните новини, предупреждения за защита и актуализации. osTicket forumsсъщо е страхотно място да получите помощ, насоки и помощ. В допълнение към форумите, osTicket уики предоставя полезна колекция от образователни материали, документация, както и бележки от общността.\n\n Ако търсите по-високо ниво на подкрепа, ние предлагаме професионални услуги и обичай за подпомагане на търговията с гарантирано време за реакция и достъп до основния екип за развитие. Можем също така да персонализирате системата, за да отговарят на вашите уникални нужди.\nЗа повече информация или да обсъдим вашите нужди, моля свържете се с нас днес.Всяко мнение ще бъдат оценени!\nosTicket Team");
define("bg_THANK_YOU_FOR_CONTACTING_US", "Благодаря ви, че се свързахте с нас.<br>Заявката за помощен билет е била създадена и наш представител ще се свърже с Вас, ако е необходимо.");
define("bg_THANK_YOU_HELPDESK_OFFLINE", "Благодаря ви, за интереса да се свързахте с нас.<br>Системата за клиентска поддръжка е неактивен в момента, моля проверете отново по-късно.");
define("bg_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "Това е глобална настройка, която може да бъде забранено на ниво отдел");
define("bg_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Билети вече е възложен на персонала.");
define("bg_TICKET_ALREADY_ASSIGNED" , "Билети вече е възложен на персонала.");
define("bg_TICKET_ALREADY_IN_DEPT", "Билет вече в отдела.");
define("bg_TICKET_ASSIGNED_TO_THE_STAFF", "Билета е предаден до целеви персонал");
define("bg_TICKET_CREATED_BY_STAFF", "Билета е създаден от персонала");
define("bg_TICKET_CREATED_SUCCESS", "Билети е създаден успешно");
define("bg_TICKET_DELETED_FOREVER", "Билети изтрити завинаги");
define("bg_TICKET_DENIED_403", "Билета отказан грешка #403");
define("bg_TICKET_DENIED_NOTICE", "Бележка за отказ на билет");
define("bg_TICKET_FLAGGED_AS_OVERDUE", "Билета е с подаден сигнал, че е закъснял");
define("bg_TICKET_GRACE_PERIOD", "Грайс период на билет");
define("bg_TICKET_ID", "Билет N");
//define("bg_TICKET_LOWER", "bilet");
define("bg_TICKET_NOT_ASSIGNED", "Билет не е назначен!");
define("bg_TICKET_OPTIONS_AND_SETTINGS", "Билет Опции &amp; Настройки");
define("bg_TICKET_PRIORITY", "Приоритет на билет");
define("bg_TICKET_RELEASED_FROM", "Освободен билет (неприсвоен) от");
define("bg_TICKET_STATUS_SET_TO", "Статуса на билета променен на");
define("bg_TICKET_STATUS", "Статус на билет");
define("bg_TICKET_TRANSFER", "Билета прехвърлен успешно");
define("bg_TICKET_WILL_BE_REOPENED", "Билет ще бъде отворен отново на съобщено мнение");
define("bg_TICKETS_PER_PAGE", "Билети/предмети на страница");
//define("bg_TICKETS", "Билети");
define("bg_TIME_FORMAT", "Формат час");
define("bg_TITLE_ALREADY_EXISTS", "Заглавие вече съществува");
define("bg_TITLE_REQ", "Изисква се Заглавие");
define("bg_TITLE_REQUIRED", "Изисква се Заглавие");
define("bg_TITLE", "Заглавие");
define("bg_TO_BAN_EMAILS", "за забрана на имейли");
define("bg_TO_CLOSE", "да се затвори");
define("bg_TO_DELETE_SELECTED_DEPTS", "да изтриете избраните Департамент");
define("bg_TO_DELETE_TICKETS", "да изтриете билети");
define("bg_TO_DELETE", "да изтриете");
define("bg_TO_DISABLE", "да деактивирате");
define("bg_TO_ENABLE", "да активирате");
define("bg_TO_FLAG_TICKETS_OVERDUE", "да се отметне билета като закъсняла");
define("bg_TO_LOCK", "to lock");
define("bg_TO_MAKE_SELECTED_DEPTS_PRIVATE", "да направят избраните Департаменти лични");
define("bg_TO_MAKE_SELECTED_DEPTS_PUBLIC", "да направи публични избраните Департаменти");
define("bg_TO_MARK_SELECTED_TICKETS_OVERDUE", "марка избрани билети закъснели/остарели");
define("bg_TO_REM_EMAILS_FROM_BANLIST", "премахване на имейли от банове.");
define("bg_TO_REOPEN", "да възобнови");
define("bg_TO_VIEW_THE_STATUS_OF_A_TICKET", "За да видите състоянието на билет, ни предоставите данните си за вход по-долу.<br/>Ако това е вашето първи опит се свържете с нас или сте загубили номера на билета си , моля<a href=\"open.php\">натиснете тук</a> за да отворите нов билет.");
define("bg_TO", "за");
define("bg_TOGGLE", "Превключване");
define("bg_TOPIC_TOO_SHORT", "Темата е твърде кратъка. Минимум 5 символа");
define("bg_TRANSFER", "прехвърляне");
define("bg_TRY_AGAIN", "Опитайте отново");
define("bg_TYPE", "Тип");
define("bg_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "Не може да добавите имейл, в банове");
define("bg_UNABLE_TO_ADD_EMAIL", "Не можете да добавите имейл. Вътрешна грешка");
define("bg_UNABLE_TO_ADD_MAIL_TO_BANLIST", "Не можете да добавите имейл в банове. Опитайте отново");
define("bg_UNABLE_TO_ASSIGN_TICKET", "Билета Не може да се възложи");
define("bg_UNABLE_TO_COMPLETE_ACTION", "Не може да бъде завършено действие");
define("bg_UNABLE_TO_COMPLETE_PASS_CHANGE", "Смяна на паролата не може да завърши.Вътрешна грешка.");
define("bg_UNABLE_TO_COMPLETE_THE_TRANSFER", "Не може да завършите прехвърлянето");
define("bg_UNABLE_TO_CONNECT_MYSQL", "Не може да се свърже с MySQL сървъра. Възможно е невалиден входна информация.<br>");
define("bg_UNABLE_TO_CREATE_DB", "Не може да се създаде база данни, поради разрешение");
define("bg_UNABLE_TO_CREATE_THE_REPLY", "Отговора не може да се създаде. Вътрешна грешка");
define("bg_UNABLE_TO_CREATE_TICKET", "Билет не може да се създаде. Коригирате грешката(ите) и опитайте отново");
define("bg_UNABLE_TO_DELETE_SELECTED_DEPT", "Не можете да изтриете избрани отдели.");
define("bg_UNABLE_TO_DELETE_SELECTED_EMAILS", "Не може да изтриете избрания имейл (и).");
define("bg_UNABLE_TO_DISABLE_SELECTED_TOPICS", "Не може да забраните избрани теми");
define("bg_UNABLE_TO_FETCH_INFO_ON", "Невъзможност за извличане на информация за");
define("bg_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "Не може да премахнете избраните имейли");
define("bg_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "Не може да направите личен избран отдел(и). Вероятно вече са лични!");
define("bg_UNABLE_TO_OPEN_CONF_FILE", "Не мога да отворя конфигурационния файл за изписване. Разрешението е отказано!");
define("bg_UNABLE_TO_POST_RESPONSE", "Не може да публикувате отговор.");
define("bg_UNABLE_TO_POST_THE_MESSAGE", "Съобщение не може да се публикува");
define("bg_UNABLE_TO_POST_THE_NOTE", "Не може да оставите бележка.");
define("bg_UNABLE_TO_REMOVE_EMAIL", "Не може да премахнете имейл адреса");
define("bg_UNABLE_TO_SELECT_DB", "Не може да се изберете базата данни");
define("bg_UNABLE_TO_UPDATE_EMAIL", "Може да актуализира имейл адреса. Вътрешна грешка");
define("bg_UNBAN_EMAIL_LOWER", "премахни бан на емай;");
define("bg_UNKNOWN_ACTION", "Непозната операция");
define("bg_UNKNOWN_BANLIST_COMMAND", "Неизвестна команда за забранен списък!");
define("bg_UNKNOWN_COMMAND", "Неизвестна команда!");
define("bg_UNKNOWN_DEPT_ACTION", "Неизвестно действие Отдел");
define("bg_UNKNOWN", "Неизвестно");
define("bg_UPDATE_DEPARTMENT", "Актуализация на отдел");
define("bg_UPDATE_ERROR", "Актуализация грешка!");
define("bg_UPDATED_SUCCESS", "актуализиран успешен");
define("bg_UPLOAD_DIR_INVALID", "директорията за Качване невалидна. Свържете се с администратора.");
define("bg_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "Използвайте приоритетен имейл, когато (пишеш емайл за билет)");
define("bg_USERNAME_MISSING", "Липсва потребителско име");
define("bg_USERNAME", "Потребителско име");
define("bg_USERS", "Потребители");
define("bg_VALID_EMAIL", "Валиден имейл");
define("bg_VALID_PASS_REQ", "Изисква се валидна парола");
define("bg_VIEW_STATUS", "Виж статус");
define("bg_WELCOME_BACK", "Здравейте отново! Вие сте изброен като  'на почивка' Моля, уведомете администратор или вашия мениджър да знае, че ти се върна.");
define("bg_WELCOME_TO_SUPPORT_CENTER", "Добре дошли в Центъра за поддръжка.");
define("bg_YOU_ARE_NOT_ALLOWED", "Не е позволено");
define("bg_YOU_HAVE_REACHED_MAX_TICKETS", "Вие сте достигнали максималните разрешени отворени билети.");
define("bg_YOU_LL_NEED_TICKET_NUMBER", "Ще имате нужда от номера на билета, заедно с вашия имейл, за да видите състоянието и напредъка онлайн.");
define("bg_YOU_MUST_CHANGE_PASS", "Вие трябва да промените паролата си, за да продължите.");
define("bg_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "Трябва да въведете домакините да белия списък");
define("bg_YOU_MUST_SELECT_ACTION_TO_PERFORM", "Трябва да изберете действие за изпълнение");
define("bg_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "Трябва да изберете поне един артикул");
define("bg_YOU_MUST_SELECT_ONE_EMAIL", "Трябва да изберете поне един имейл");
define("bg_YOU_MUST_SELECT", "Трябва да изберете");
define("bg_YOU_NEED_TO_SET_UPLOADDIR", "Трябва да настроите директория за качване");
define("bg_YOU_PIPE_WE_ACCEPT_POLICY", "Ние приемаме политика");
define("bg_ZERO_RESULTS", "Запитването върна 0 резултата");