<?php
define("br_A_DEPT", "Dept.");
define("br_A_PRIORITY", "prioridade");
define("br_ACCESS_DENIED", "Accesso Negado");
define("br_ACTION_DENIED_TICKET_LOCKED", "Ação negada. O Ticket está bloqueado por outra pessoa!");
define("br_ACTION_DENIED", "Ação Negada");
define("br_ACTIVE", "Ativo");
define("br_ADD_NEW_PREMADE_REPLY", "Adicionar uma nova resposta");
define("br_ADD_NEW_USER", "Adicionar novo usuário");
define("br_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "E-mail do administrador recebe um alerta por padrão. Selecione destinatários adicionais abaixo");
define("br_ADMIN_EMAIL", "E-mail Administrador");
define("br_ADMIN_PANEL", "Painel de Controle");
define("br_ADVANCED", "Avançado");
define("br_ALERT_FROM_EMAIL_ADDRESS", "Alerta (s) com o endereço de e-mail");
define("br_ALERT_SUBJECT_MISSING", "Alerta assunto faltando");
define("br_ALERTS_NOTICES", "Alertas &amp; Avisos");
define("br_ALL_DEP", "Todo Departamento");
define("br_ALL_DEPTS", "Todos os Departamentos");
define("br_ALL", "Todos");
define("br_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Permitir o cliente substituir / definir a prioridade (bilhetes on-line)");
define("br_ALLOWED_FILE_EXT_REQ", "Extensões de arquivos permitidos necessários");
define("br_ALLOWED", "permitido");
define("br_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "Um bilhete com o número de e-mail foi enviado para");
define("br_ANOTHER_DEPT_USING_HOST_COMBINATION", "Outro departamento utilizando host / combinação de usuário.");
define("br_ANSWER", "Responder");
define("br_API_SETTINGS_UPDATED", "Configurações de API atualizada");
define("br_ARE_YOU_SURE_YOU_WANT", "Tem certeza de que deseja");
define("br_ASSIGN", "atribuir");
define("br_ASSIGNED_STAFF", "Suporte atribuído");
define("br_ASSIGNED_TICKETS", "Bilhetes atribuídos");
define("br_AT_LEAST_ONE_TOPIC", "Pelo menos um tópico");
define("br_ATTACH_FILE", "Anexar arquivo");
define("br_ATTACH_SETTINGS_UPDATED", "Atualizada configurações dos anexos");
define("br_ATTACH", "Anexo");
define("br_ATTACHMENT_DISABLED", "Anexos Desativado");
define("br_ATTEMPTS", "Tentativas");
define("br_AUTHENTICATION_REQUIRED", "Autenticação necessária");
define("br_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Auto-atribuir os bilhetes para último entrevistado reaberta 'disponível'. (<i> 3 meses limite</i>)");
define("br_AUTOLOCK_TIME", "Tempo Auto-lock");
define("br_AUTORESPONDERS_GLOBAL_SETTING", "Auto resposta &nbsp;(Definição Global)");
define("br_AUTORESPONDERS", "Auto Resposta");
define("br_AUTORESPONSE_FROM_EMAIL", "Resposta automática por e-mails");
define("br_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Auto resposta inclui a identificação do bilhete necessário para verificar o seu status");
define("br_BAD_PREFIX_UNDERSCORE", "Bad prefixo. Deve ter sublinhado(_) no final por exemplo. e.g 'ost_'");
define("br_BAN_EMAIL_LOWER", "banemail");
define("br_BYTES_ALLOWED", "bytes permitido");
define("br_CAN_BE_APPENDED_TO_RESPONSES", "pode ser anexado às respostas. (disponível como uma opção para serviços públicos) ");
define("br_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "Não é possível excluir. O departamento está associado a um tópico de ajuda. Remover primeiro a associação.");
define("br_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "Não é possível excluir um Departamento com membros. Mova a equipe em primeiro lugar.");
define("br_CANCEL", "Cancelar");
define("br_CATEGORY", "Categoria");
define("br_CELL_PHONE", "Telefone Celular");
define("br_CHANGE_PASS", "Alterar a senha");
define("br_CHANGE_PRIORITY", "alterar_prioridade");
define("br_CHECK_STATUS_OPENED_TICKETS", "Verifique o status do ticket aberto anteriormente. Nós fornecemos arquivos e histórico de todos os seus pedidos de suporte completo com as respostas.");
define("br_CHECK_STATUS", "Verificar Status");
define("br_CLICKABLE_URL", "URLs clicáveis");
define("br_CLIENT_SESSION_TIMEOUT_IN_MINS", "Tempo ocioso máximo do cliente em poucos minutos. Digite 0 para desativar tempo limite");
define("br_CLIENT_SESSION_TIMEOUT", "Tempo da Sessão do Cliente");
define("br_CLOSE_LOWER", "fechado");
define("br_CLOSE_REOPEN_TICKETS", "fechar / reabrir bilhetes");
define("br_CLOSE", "Fechar");
define("br_CLOSED", "Fechado");
define("br_COMMERCIAL_SUPPORT_AVAILABLE", "Suporte comercial disponível");
define("br_CONF_FILE_ALREADY_MOD", "Arquivo de configuração já modificado!");
define("br_CONF_FILE_NOT_WRITABLE", "Arquivo de configuração não é adequado");
define("br_CONFIRM_NEW_PASS", "Confirmar nova senha");
define("br_CONFIRM", "Confirmar");
define("br_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Conflitos com sistema de e-mail acima");
define("br_CONTACT_ADMIN", "Contate o administrador, se você acredita que é um erro");
define("br_CREATE_DATE", "Data de criação");
define("br_CURR_PASS_REQ", "Senha atual exigida");
define("br_CURR_TIME", "Horário atual");
define("br_DATE_AND_TIME_FORMAT", "Formato de data &amp; hora");
define("br_DATE_AND_TIME", "Data &amp; Hora");
define("br_DATE_FORMAT", "Formado da Data");
define("br_DAY_DATE_TIME_FORMAT", "Formato de Dia, Data &amp; Hora");
define("br_DAYLIGHT_SAVING", "Horário de verão");
define("br_DAYLIGHT_SAVINGS", "Horário de Verões");
define("br_DB_NOT_EXISTS", "Banco de dados não existe");
define("br_DEFAULT_DEPARTMENT", "Departamento padrão");
define("br_DEFAULT_EMAIL_TEMPLATE", "Modelo Padrão de E-mail");
define("br_DEFAULT_EMAIL", "E-mail Padrão");
define("br_DEFAULT_PAGE_SIZE", "Tamanho de página padrão");
define("br_DEFAULT_PRIORITY", "Prioridade padrão");
define("br_DEFAULT_TIMEZONE", "Fuso horário padrão");
define("br_DELETE_DEPS", "Excluir depts");
define("br_DELETE_LOWER", "Excluir");
define("br_DELETE_TICKETS", "excluir tickets");
define("br_DELETE", "Excluir");
define("br_DEPARTMENT_MANAGED", "Gerente de Departamento (spam)");
define("br_DEPARTMENT_MANAGER", "Gerente de Departamento");
define("br_DEPARTMENT_MEMBERS", "Departamento de Membros (spam)");
define("br_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Quais Departamentos constarão na resposta");
define("br_DEPARTMENTS", "Departamentos");
define("br_DEPENDS_ON_THE_TAG_BELOW", "depende da marcação abaixo");
define("br_DEPT_DEPENDS_ON_EMAIL", "Dept depende de e-mail e configurações de tópicos de ajuda para os bilhetes de entrada.");
define("br_DEPT_EMAIL_ABOVE", "Dept e-mail (acima)");
define("br_DEPT_EMAIL", "Dept e-mail");
define("br_DEPT_MANAGER", "Gerente de departamento");
define("br_DEPT_NAME", "Nome do departamento");
define("br_DEPT_SIGNATURE", "Dept Assinatura");
define("br_DEPT_TRANSFER", "Transferência de Dept.");
define("br_DEPT_TYPE", "Tipo de Dept");
define("br_DEPT", "Departamento");
define("br_DIR_MUST_BE_VALID_WRITABLE", "Diretório deve ser válido e adequado");
define("br_DIRECTORY", "Diretório");
define("br_DISABLE", "Disabilitar");
define("br_DISABLED", "Disabilidado");
define("br_DO_REQUESTED_ACTION", "fazer ação solicitada");
define("br_EDIT_PREMADE_REPLY", "Edite Premade Resposta");
define("br_EMAIL_ADD_SUCCESS", "E-mail adicionado com sucesso");
define("br_EMAIL_ADDED_TO_BANLIST", "E-mail adicionado à lista de banidos");
define("br_EMAIL_ADDRESS", "Endereço de e-mail");
define("br_EMAIL_ALREADY_BANNED", "E-mail já banido");
define("br_EMAIL_ALREADY_EXISTS", "E-mail já existe");
define("br_EMAIL_IN_BANLIST", "Este e-mail é em banlist e ser removido para responder");
define("br_EMAIL_MISMATCH", "E-mail incompatibilidade.");
define("br_EMAIL_REMOVED", "Email removido");
define("br_EMAIL_SETTINGS", "Configurações de e-mail");
define("br_EMAIL_UNKNOWN", "E-mail desconhecido");
define("br_EMAIL_UPDATED_SUCCESS", "E-mail atualizado com sucesso");
define("br_ENABLE_AUTOCRON", "Ativar Auto Cron");
define("br_ENABLE_CRON_CALL", "Ativar chamada cron sobre a atividade da equipe");
define("br_ENABLE_EMAIL_PIPING", "Ativar tubulação e-mail");
define("br_ENABLE_POP3_EMAIL_FETCH", "Ativar busca de e-mail via POP3");
define("br_ENABLE", "Ativar");
define("br_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Erros encontrados serão informados no e-mail admin acima");
define("br_ENTER_MESSAGE", "Digite a Mensagem");
define("br_ENTER_VALID_NUM", "Digite um número válido");
define("br_ERR_SQL_SYNTAX", "Você tem um erro em sua sintaxe SQL");
define("br_ERROR_OCCURED", "Ocorram erros");
define("br_ERROR_OCCURRED", "Ocorreu um erro. Consulte Mensagens de erro abaixo.");
define("br_EXCESSIVE_LOGIN_ATTEMPTS", "Excesso de tentativas de login");
define("br_FATAL_ERROR", "Erro Fatal");
define("br_FETCH_INTERVAL_REQUIRE", "Intervalo de busca");
define("br_FILE_TOO_BIG", "O arquivo é muito grande");
define("br_FILE_UPLOAD_DISABLED_PHP_INI", "Os 'uploads de arquivos' estão desativados em php.ini");
define("br_FIRST_NAME", "Primeiro nome");
define("br_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "Para utilizar a busca de e-mail via POP3 o auto-cron deve habilitar (selecionado).");
define("br_FORGOT_LOGIN_INFO", "Esqueceu-se da sua informação de login? Por favor <a href=\"open.php\">abrir um novo ticket</a>.");
define("br_FROM_BANLIST", "de banlist");
define("br_FULL_NAME", "Nome completo");
define("br_GENERAL_INQUIRY", "Inquérito geral");
define("br_GENERAL_SETTINGS", "GConfigurações Gerais");
define("br_GET_A_PEACE_OF_MIND", "Obter uma paz de espírito");
define("br_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "Global de auto resposta em seção de preferência deve estar habilitado para o Dept. 'Ativar' em configuração para que tenha efeito.");
define("br_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "Na configuração global pode ser desabilitado a exigência de e-mail");
define("br_HELP_TOPIC", "Tópicos da Ajuda");
define("br_HELPDESK_NAME", "Helpdesk Nome/Título");
define("br_HELPDESK_STATUS", "Helpdesk Status");
define("br_HELPDESK_URL", "Helpdesk URL");
define("br_HELPS_WITH_SPAM", "Controle de mensagens spam. Enter 0 para inabilitar");
define("br_HOME", "Casa");
define("br_HOST_MISSING", "Hospede faltando");
define("br_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Horas antes bilhete é marcado atraso. Digite 0 para desativar esta função");
define("br_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "Bloqueio de bilhete habilitado, necessário renovar entrada no formulário");
define("br_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "Se você deseja enviar comentários ou informações sobre mesmo assunto adicionais, por favor, siga as instruções no e-mail.");
define("br_IMAP_DOESNT_EXISTS", "IMAP não existe. PHP deve ser compilado com IMAP habilitado.");
define("br_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "A fim de agilizar as solicitações de suporte e melhor atendê-lo, nós utilizamos um sistema de ticket de suporte. Cada pedido de apoio é atribuído um número de bilhete único, que você pode usar para monitorar o progresso e respostas online. Para sua referência, nós fornecemos arquivos completos e histórico de todos os seus pedidos de suporte.");
define("br_INDICATE_SOURCE", "Indique a fonte");
define("br_INSTALL_COMPLETE", "Parabéns pela instalação básica osTicket concluída!");
define("br_INTERNAL_ERROR_OCCURED", "Erro interno");
define("br_INTERNAL_ERROR", "Erro interno. Por favor, certifique-se o download é o mais recente");
define("br_INTERNAL_NOTE_POSTED", "Nota interna postou");
define("br_INVALID_ATTACH", "Anexo inválido");
define("br_INVALID_FILE_TYPE", "Tipo de arquivo inválido");
define("br_INVALID_FILE", "Arquivo inválido");
define("br_INVALID_LOGIN", "Login inválido");
define("br_INVALID_SOURCE", "Fonte inválida");
define("br_INVALID_SQL_SCHEMA", "Esquema SQL inválido. Obtenha ajuda de desenvolvedores");
define("br_INVALID_UPLOAD_DIR", "Inválido upload de dir");
define("br_INVALID", "Inválido");
define("br_KNOWLEDGE_BASE", "Base de dados");
define("br_LANG_PRIVATE", "Privado");
define("br_LANG_PUBLIC", "Público");
define("br_LAST_NAME", "Sobrenome");
define("br_LAST_RESPONDENT", "Última Resposta");
define("br_LAST_UPDATED", "Última atualização");
define("br_LOCK", "Trancar");
define("br_LOCKED", "Trancado");
define("br_MAIL_METH", "Métodos de correio");
define("br_MAIL_PARSE_ERRORS", "E-mail sobre erros de análise");
define("br_MAKE_PRIVATE", "Tornar privado");
define("br_MAKE_PUBLIC", "Tornar público");
define("br_MAKE_URL_CLICKABLE", "Tornar as URLs clickable");
define("br_MANAGER", "Gerente");
define("br_MASS_MANAGE_TICKETS", "gerenciar tickets de massa. Contato administrador para esse acesso");
define("br_MAX_ALLOWED", "Máximos admitidos");
define("br_MAX_FILE_SIZED_REQ", "Tamanho máximo de arquivo necessário");
define("br_MAX_LOGIN_ATTEMPTS", "Você atingiu o número máximo de tentativas de login sem sucesso. Tente novamente após 5 minutos ou <a href=\"open.php\">abra um novo ticket</a>");
define("br_MAX_OPEN_TICKETS", "Máximo <b>Abrir</b> Tickets");
define("br_MAX_PAGE_SIZE", "Tamanho máximo da página");
define("br_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Mensagem apenso a um bilhete confirmação existente");
define("br_MESSAGE_POSTED_SUCCESS", "Mensagem enviada com sucesso");
define("br_MESSAGE_REQUIRED", "Mensagem necessário");
define("br_MESSAGE", "Messagem");
define("br_MIN_TO_LOCK_A_TICKET", "Minutos para bloquear um bilhete sobre a atividade. Digite 0 para desativar o bloqueio");
define("br_MISSING_MESSAGE", "ID ausente na mensagem");
define("br_MISSING_OR_INVALID_GROUP", "Grupo ausente ou inválido");
define("br_MISSING_SQL_SCHEMA", "Falta esquema SQL");
define("br_MOBILE", "Móvel");
define("br_MUST_BE_SIX_CHARS", "Deve ter pelo menos 6 caracteres");
define("br_MUST_SELECT_PRIORITY", "Você deve selecionar a prioridade");
define("br_MY_ACCOUNT", "Minha Conta");
define("br_MY_PREFERENCES", "Minhas preferências");
define("br_MY_PROFILE_INFO", "Informações de perfil");
define("br_MY_PROFILE", "Meu Perfil");
define("br_NAME", "Nome");
define("br_NEED_HELP_QUESTION", "Precisa de ajuda?");
define("br_NEW_DEPT", "Novo Departamento");
define("br_NEW_MESSAGE_ALERT", "Nova mensagem de Alerta");
define("br_NEW_MESSAGE", "Nova mensagem");
define("br_NEW_PASS_NOT_MATCH", "Nova senha(s) não correspondem");
define("br_NEW_PASS_REQ", "Nova senha necessária");
define("br_NEW_PASS_SAME_OLD", "A nova senha é a mesma senha antiga");
define("br_NEW_PREMADE_REPLY", "New Premade Responder");
define("br_NEW_TICKET_ALERT", "Alerta Novo Ticket");
define("br_NEW_TICKET", "Novo ticket");
define("br_NO_ACCESS_TO_TICKET", "Você não tem acesso ao bilhete");
define("br_NO_PERMISSION_TO_REASSIGN", "Você não tem permissão para re-atribuir bilhetes atribuídos");
define("br_NO_PERMISSION_TO", "Você não tem permissão para");
define("br_NO_REPLY_EMAIL_ADDRESS", "Sem resposta do endereço de E-mail");
define("br_NO_REPLY_EMAIL", "Sem resposta de e-mail");
define("br_NO_STAFF_FOUND", "Nenhum suporte encontrado");
define("br_NO_SUCH_FILE", "Nenhum arquivo");
define("br_NO_TICKETS_FOUND", "Nenhum bilhete encontrado.");
define("br_NO_TICKETS_SELECTED", "Não há bilhetes selecionado. Você deve selecionar pelo menos um bilhete.");
define("br_NO_USER_ADD_USER", "Nenhum usuário (Adicionar usuários)");
define("br_NONE", "Nome");
define("br_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "Você não tem permissão para alterar a prioridade do ticket");
define("br_NOT_ALLOWED_TO_TRANSFER_TICKETS", "Você não está autorizado a transferir os bilhetes.");
define("br_NOTE_REQ", "Nota de Mensagem exigida");
define("br_NOTE_REQUIRED", "Nota / Mensagem necessária");
define("br_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Os alertas enviados não obtiveram respostas, a partir de endereço existente.");
define("br_OBSERVE", "Observe");
define("br_OF", "di");
define("br_OFFICE_PHONE", "Telefone de trabalho");
define("br_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "Interface do cliente desabilitada.<b> Só </ b> é permitido a<b> super-administrador </ b> fazer o login para Staff Painel de Controle");
define("br_OFFLINE", "Offline");
define("br_ONLINE", "Online");
//define("br_OPEN_LOWER", "aberto");
define("br_OPEN_NEW_TICKET", "Abrir Novo Ticket");
define("br_OPEN_TICKET", "Ticket aberto");
define("br_OPEN", "Abrir");
define("br_OSTICKET_BASIC_INSTALL", "osTicket Basic Installation");
define("br_OSTICKET_INSTALLER", "osTicket Installer");
define("br_OSTICKET_REQUIRES_MYSQL", "osTicket requires MySQL 4.1.1 or better! Please upgrade");
define("br_OUTGOING_EMAIL", "Outgoing Email");
define("br_OVERDUE_LOWER", "atrasado");
define("br_OVERDUE_TICKET_ALERT", "Alerta Ticket atrasado");
define("br_OVERLIMIT_NOTICE", "Limite ultrapassado");
//define("br_PAGE", "página");
define("br_PASS_CHANGE_SUCCESS", "Senha alterada com sucesso");
define("br_PASS_TO_NOT_MATCH", "senhas não combinam!");
define("br_PASSWORD_REQUIRED", "Senha necessária");
define("br_PER_EMAIL", "por e-mail");
define("br_PERM_DENIED", "Perm. Negado.");
define("br_PHONE_NUM_REQ", "Telefone # necessário");
define("br_PHONE", "Telefone");
define("br_PHP_DATE_MANUAL", "Por favor, consulte <a href=\"http://php.net/date\" target=\"_blank\">PHP Manual</a> para os parâmetros suportados.");
define("br_PHP_OUT_OF_DATE", "Instalação PHP desatualizado");
define("br_PHRASE_TOO_SHORT", "frase é muito curta!");
define("br_PHRASE_TWO_WORDS", "Frase com 2 ou + palavras");
define("br_PLEASE_ENTER_VALID_EMAIL", "Por favor insira um email válido.");
define("br_PLEASE_FILL_TO_OPEN_A_TICKET", "Por favor, preencha o formulário abaixo para abrir um novo ticket.");
define("br_POSSIBLE_ERROR_DETECTED", "Possíveis erros detectados, por favor, verifique os avisos abaixo");
define("br_POSSIBLY_ACCESS_DENIED", "Acesso negado. Se você acredita que isso é um erro, obter suporte técnico.");
define("br_POSSIBLY_INVALID_TICKET", "ID de ticket inválido");
define("br_POST_REPLY", "Responder mensagem");
define("br_POSTNOTE", "nota de mensagem");
define("br_PREF_ERROR", "Erro de atualização das preferências");
define("br_PREF_UPDATED", "Preferências atualizadas com sucesso");
define("br_PREFERENCES", "Preferências");
define("br_PREFERRED_TIMEZONE", "Fuso horário preferidoe");
define("br_PREMADE_REPLIES", "Premade Respostas");
define("br_PREMADE_REPLY", "Premade Resposta");
define("br_PRIMARY_OUTGOING_MAIL", "Primário saída de E-mail");
define("br_PRIORITY_CHANGED_SUCCESS", "Prioridade alterada com sucesso");
define("br_PRIORITY", "Prioridade");
define("br_PRIVATE_HIDDEN", "Privado (Oculto)");
define("br_PROBLEM_CHANGING_PRIORITY", "Problemas ao mudar prioridade.");
define("br_PROBLEM_CLOSING_TICKET", "Problemas ao fechar o ticket.");
define("br_PROBLEM_RELEASING_TICKET", "Problemas liberar a mensagem.");
define("br_PROBLEM_REOPENING_TICKET", "Problemas reabrir o ticket.");
define("br_PROBLEMS_ADMIN_PAGE", "Problemas ao carregar a página de administração solicitada.");
define("br_PROBLEMS_DELETING_THE_TICKET", "Problemas de exclusão do bilhete");
define("br_PROBLEMS_DISPLAYING_DIR", "Problemas de exibição de diretório");
define("br_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Problemas marcam a passagem do atraso");
define("br_PROCESS", "processo");
define("br_PROF_INST_AVAILABLE", "Instalação profissional disponível");
define("br_PROFILE_UPDATE_SUCCESS", "Perfil atualizado com sucesso");
define("br_PUBLIC", "Público");
define("br_QUERY", "Pergunta");
define("br_RANDOM", "Acaso");
define("br_RECOMMENDED", "recomenda");
define("br_REJECTED", "rejeitado");
define("br_RELEASE_LOWER", "liberar");
define("br_REMOVING_QUOTED_REPLY", "Remoção de resposta citada");
define("br_REOPEN_LOWER", "reabrir");
define("br_REOPEN", "reabrir");
define("br_REOPENED_TICKETS", "Tickets reabertos");
define("br_REPLY_REQUIRED", "Necessário resonder");
define("br_REPLY_SEPARATOR_TAG", "Responder Tag Separador");
define("br_REPLY_TITLE", "Responder Título");
define("br_REPLY", "responder");
define("br_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Necessário quando Dept é público");
define("br_REQUIRED", "necessário");
define("br_RESET_CHANGES", "Redefinir Mudanças");
define("br_RESET", "Resetar");
define("br_RESPONSE_MESSAGE_REQUIRED", "Mensagem de resposta exigida");
define("br_RESPONSE_POSTED_SUCCESS", "Resposta postada com sucesso");
define("br_SALVE_EMAIL_HEADERS", "Salvar cabeçalhos de e-mail");
define("br_SAVE_CHANGES", "Salvar alterações");
define("br_SAVE_RAW_HEADERS", "Salvar cabeçalhos matérias");
define("br_SAVE", "Salvar");
define("br_SEARCH_FOR", "Pesquisar por");
define("br_SEARCH_TERM_MORE_THAN_3_CHARS", "O termo a pesquisar deve ter mais de 3 caracteres");
define("br_SEARCH", "Pesquisar");
define("br_SECURITY_VIOLATION", "Violação de segurança. Repetidas violações irá resultar no bloqueio de sua conta.");
define("br_SELECT_ASSIGNEE", "Selecione signatário");
define("br_SELECT_DEFAULT_DEPT", "Selecione o Dept Padrão");
define("br_SELECT_DEPARTMENT", "Selecione o Departamento");
define("br_SELECT_HELP_TOPIC", "Selecione um tópico da ajuda");
define("br_SELECT_MANAGER_OPT", "Selecione um gerente (optional)");
define("br_SELECT_ONE", "Selecione um");
define("br_SELECT_RECIPIENTS", "Selecionar os destinatários");
define("br_SELECT", "Select");
define("br_SELECTED_DEPT_DELETED", "departamentos selecionados excluídos");
define("br_SELECTED_EMAILS_DELETED", "e-mail selecionado (s) eliminado(s)");
define("br_SELECTED_EMAILS_REMOVED", "e-mails selecionados removido banlist");
define("br_SELECTED_EMAILS_USED_BY_A_DEPT", "Um ou mais dos e-mails selecionados está sendo utilizado por um Dept. Retirar a associação.");
define("br_SELECTED_ENTRIES", "entradas selecionadas");
define("br_SELECTED_REPLIES_DELETED", "Respostas selecionadas eliminadas");
define("br_SELECTED_REPLIES_DISABLED", "Respostas selecionadas desativadas");
define("br_SELECTED_REPLIES_ENABLED", "Respostas selecionadas habilitadas");
define("br_SELECTED_SERVICES_ENABLED", "serviços seleccionados habilitados");
define("br_SELECTED_TICKETS_CLOSED", "bilhetes selecionados fechados");
define("br_SELECTED_TICKETS_DELETED", "bilhetes selecionados excluídos");
define("br_SELECTED_TICKETS_OVERDUE", "bilhetes selecionados marcados com atrasos");
define("br_SELECTED_TICKETS_REOPENED", "bilhetes selecionados reabertos");
define("br_SELECTED_TICKETS", "bilhetes selecionados");
define("br_SELECTED_TOPIC_DISABLED", "tópicos selecionados desativados");
define("br_SELECTED_TOPICS_DELETED", "tópicos selecionados excluídos");
define("br_SELECTED_USERS", "usuário selecionado (s)");
define("br_SEND_OVERLIMIT_NOTICE", "Enviar aviso sobre limite");
define("br_SENT_ONLY_ONCE", "Enviado <b>apenas uma vez</b> em violação do limite para o usuário. <b>administrador recebe alertas em TODOS desmentidos por padrão</b>");
define("br_SEQUENTIAL", "Sequencial");
define("br_SERVER_TIME", "Hora de servidor");
define("br_SESSION_TIMED_OUT", "Sessão expirou devido à inatividade");
define("br_SHOW_ASSIGNED_TICKETS", "Mostrar bilhetes em aberto");
define("br_SHOWING", "Mostrando");
define("br_SIGNATURE", "Assinatura");
define("br_SORT_BY", "Ordenar por");
define("br_SQL_ERRORS", "Erros SQL");
define("br_STAFF_MAX_IDLE_TIME", "Tempo máximo ocioso dos funcionários em questão de minutos. Digite 0 para desativar tempo limite");
define("br_STAFF_MEMBERS", "Membros da Equipe");
define("br_STAFF_PANEL", "Painel do Suporte");
define("br_STAFF_SESSION_TIMEOUT", "Tempo de saída do seção de suporte");
define("br_STATUS", "Status");
define("br_STRIP_QUOTED_REPLY", "Nota citada em resposta");
define("br_SUBJECT_MISSING", "sem assunto");
define("br_SUBJECT", "Assunto");
define("br_SUBMIT_A_NEW_REQUEST", "Submeter um novo pedido de suporte. Por favor, forneça o máximo de detalhes possível para que possamos ajudá-lo melhor. Para atualizar um ticket já enviado, por favor use o formulário à direita. Um endereço de e-mail válido é necessário.");
define("br_SUMMARY_OF_THE_ISSUE_REQUIRED", "Resumo da questão necessário");
define("br_SUPPORT_OFFLINE", "Sistema de ticket está off-line");
define("br_SUPPORT_TEAM", "Equipe de Suporte");
define("br_SUPPORT_TICKET_CREATED", "Solicitação de ticket de suporte criado");
define("br_SUPPORT_TICKET_REQ_DENIED_FOR", "Solicitação de ticket de suporte negado para");
define("br_SUPPORT_TICKET_SYSTEM", "Sistema de ticket de suporte");
define("br_SYSTEM_ADMIN_EMAIL_ADDRESS", "Sistema de Administração de endereço de e-mail");
define("br_SYSTEM_ERRORS", "Erros de sistema");
define("br_SYSTEM_OFFLINE", "Desligado do sistema");
define("br_SYSTEM_PREFERENCES_AND_SETTINGS", "Preferências e Configurações do Sistema");
define("br_TABLE_PREFIX", "Prefixo da tabela");
define("br_TEMPLATE_ALERT_MSG_REQUIRED", "Modelo de alerta");
define("br_TEMPLATE_MSG_REQUIRED", "Modelo de mensagem");
define("br_TEMPLATES_UPDATED_SUCCESS", "Templates atualizado com sucesso");
define("br_THANK_YOU_FOR_CHOOSING_OSTICKET", "Obrigado por escolher o osTicket.\nCertifique você juntar osTicket fóruns http://osticket.com/forums ficar até atualizado sobre as últimas notícias, alertas de segurança e atualizações. osTicket fóruns também é um ótimo lugar para obter assistência, orientação e ajuda. Além dos fóruns, osTicket wiki fornece coleção útil de materiais educativos, documentação e notas da comunidade.\n\nSe você está à procura de maior nível de apoio, nós fornecemos serviços profissionais e de apoio comercial personalizado com tempos de resposta garantidos e o acesso à equipe de desenvolvimento do núcleo. Podemos também personalizar o sistema para atender às suas necessidades específicas.\nPara obter mais informações ou para discutir suas necessidades, entre em contato conosco hoje.Qualquer comentário será apreciado!\nosTicket Equipe");
define("br_THANK_YOU_FOR_CONTACTING_US", "Obrigado por entrar em contato conosco.<br>Um pedido de ticket de suporte foi criada e um representante estará recebendo de volta para você em breve, se necessário.");
define("br_THANK_YOU_HELPDESK_OFFLINE", "Obrigado pelo seu interesse em entrar em contato conosco.<br>Nosso helpdesk está offline no momento, por favor, volte mais tarde.");
define("br_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "Essa é a configuração global, que pode ser desativado em nível de departamento");
define("br_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Ticket já atribuído à equipe.");
define("br_TICKET_ALREADY_ASSIGNED" , "Ticket já atribuído.");
define("br_TICKET_ALREADY_IN_DEPT", "Ticket já no Departamento");
define("br_TICKET_ASSIGNED_TO_THE_STAFF", "Ticket atribuído ao suporte");
define("br_TICKET_CREATED_BY_STAFF", "Ticket criado pela equipe");
define("br_TICKET_CREATED_SUCCESS", "Ticket criado com sucesso");
define("br_TICKET_DELETED_FOREVER", "Ticket excluído para sempre");
define("br_TICKET_DENIED_403", "Ticket negado erro #403");
define("br_TICKET_DENIED_NOTICE", "Ticket de notícia negado");
define("br_TICKET_FLAGGED_AS_OVERDUE", "Ticket sinalizado como atraso");
define("br_TICKET_GRACE_PERIOD", "Ticket em período de graça");
define("br_TICKET_ID", "Ticket IDs");
//define("br_TICKET_LOWER", "ticket");
define("br_TICKET_NOT_ASSIGNED", "Ticket não está atribuído!");
define("br_TICKET_OPTIONS_AND_SETTINGS", "Opções &amp; configurações de ingressos");
define("br_TICKET_PRIORITY", "Ticket com Prioridade");
define("br_TICKET_RELEASED_FROM", "Ticket liberado (não atribuído) para");
define("br_TICKET_STATUS_SET_TO", "Estado Ticket definido para");
define("br_TICKET_STATUS", "Ticket status");
define("br_TICKET_TRANSFER", "Ticket transferido com sucesso");
define("br_TICKET_WILL_BE_REOPENED", "Ticket será reaberto na próxima mensagem");
define("br_TICKETS_PER_PAGE", "Tickets/itens por página");
//define("br_TICKETS", "Tickets");
define("br_TIME_FORMAT", "Formato da Hora");
define("br_TITLE_ALREADY_EXISTS", "Título já existe");
define("br_TITLE_REQ", "Título necessário");
define("br_TITLE_REQUIRED", "Título necessário");
define("br_TITLE", "Título");
define("br_TO_BAN_EMAILS", "Proibição de e-mails");
define("br_TO_CLOSE", "para fechar");
define("br_TO_DELETE_SELECTED_DEPTS", "excluir depts selecionados");
define("br_TO_DELETE_TICKETS", "excluir bilhetes");
define("br_TO_DELETE", "para excluir");
define("br_TO_DISABLE", "para desativar");
define("br_TO_ENABLE", "para habilitar");
define("br_TO_FLAG_TICKETS_OVERDUE", "para marcar bilhetes vencidos");
define("br_TO_LOCK", "para bloquear");
define("br_TO_MAKE_SELECTED_DEPTS_PRIVATE", "tornar depts selecionados privado");
define("br_TO_MAKE_SELECTED_DEPTS_PUBLIC", "tornar depts selecionados público");
define("br_TO_MARK_SELECTED_TICKETS_OVERDUE", "para marcar bilhetes selecionados atraso/envelhecer");
define("br_TO_REM_EMAILS_FROM_BANLIST", "remover e-mails de banlist.");
define("br_TO_REOPEN", "para reabrir");
define("br_TO_VIEW_THE_STATUS_OF_A_TICKET", "Para exibir o status de um ticket, com seus dados de login abaixo. <br/> Se esta é a sua primeira vez em contato conosco ou você perdeu o ID do ticket, por favor <a href=\"open.php\"> clique aqui </ a> para abrir um novo ticket.");
define("br_TO", "para");
define("br_TOGGLE", "Alternar");
define("br_TOPIC_TOO_SHORT", "Tópico é muito curto. 5 chars mínimo");
define("br_TRANSFER", "transfer");
define("br_TRY_AGAIN", "Try again");
define("br_TYPE", "Type");
define("br_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "Não é possível adicionar o e-mail para lista de banidos");
define("br_UNABLE_TO_ADD_EMAIL", "Não é possível adicionar e-mail. Erro interno");
define("br_UNABLE_TO_ADD_MAIL_TO_BANLIST", "Não é possível adicionar e-mail para lista de banidos. Tente novamente");
define("br_UNABLE_TO_ASSIGN_TICKET", "Incapaz de atribuir o bilhete");
define("br_UNABLE_TO_COMPLETE_ACTION", "Não foi possível concluir a ação");
define("br_UNABLE_TO_COMPLETE_PASS_CHANGE", "Não foi possível concluir a alteração de senha. Erro interno.");
define("br_UNABLE_TO_COMPLETE_THE_TRANSFER", "Não foi possível concluir a transferência");
define("br_UNABLE_TO_CONNECT_MYSQL", "Não é possível conectar ao servidor MySQL. Informações de login possivelmente inválido. <br>");
define("br_UNABLE_TO_CREATE_DB", "Não é possível criar o banco de dados devido à permissão");
define("br_UNABLE_TO_CREATE_THE_REPLY", "Não é possível criar a resposta. Erro interno");
define("br_UNABLE_TO_CREATE_TICKET", "Não é possível criar o bilhete. Corrigir o erro (s) e tente novamente");
define("br_UNABLE_TO_DELETE_SELECTED_DEPT", "Não é possível excluir os departamentos selecionados.");
define("br_UNABLE_TO_DELETE_SELECTED_EMAILS", "Não é possível excluir e-mail selecionado (s).");
define("br_UNABLE_TO_DISABLE_SELECTED_TOPICS", "Incapaz de desativar temas selecionados");
define("br_UNABLE_TO_FETCH_INFO_ON", "Não foi possível obter informações sobre");
define("br_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "Incapaz de remover e-mails selecionados");
define("br_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "Incapaz de tornar o departamento selecionado (s) privado. Possivelmente já privado!");
define("br_UNABLE_TO_OPEN_CONF_FILE", "Não é possível abrir arquivo de configuração para a escrita. Permissão negada!");
define("br_UNABLE_TO_POST_RESPONSE", "Impossível postar a resposta.");
define("br_UNABLE_TO_POST_THE_MESSAGE", "Incapaz de postar a mensagem");
define("br_UNABLE_TO_POST_THE_NOTE", "Incapaz de postar a nota.");
define("br_UNABLE_TO_REMOVE_EMAIL", "Não foi possível remover o e-mail");
define("br_UNABLE_TO_SELECT_DB", "Não foi possível selecionar o banco de dados");
define("br_UNABLE_TO_UPDATE_EMAIL", "Não é possível atualizar e-mail. Erro interno");
define("br_UNBAN_EMAIL_LOWER", "unbanemail");
define("br_UNKNOWN_ACTION", "Ação Unknown");
define("br_UNKNOWN_BANLIST_COMMAND", "Comando banlist desconhecido");
define("br_UNKNOWN_COMMAND", "Comando desconhecido!");
define("br_UNKNOWN_DEPT_ACTION", "Desconhecida ação de Dept");
define("br_UNKNOWN", "Desconhecido");
define("br_UPDATE_DEPARTMENT", "Atualização de Departamento");
define("br_UPDATE_ERROR", "Atualize, erro!");
define("br_UPDATED_SUCCESS", "atualizado com sucesso");
define("br_UPLOAD_DIR_INVALID", "atualização de dir. inválida. Contate o administrador.");
define("br_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "Use prioridade e-mail quando disponível (bilhetes enviados por email)");
define("br_USERNAME_MISSING", "Nome de usuário ausente");
define("br_USERNAME", "Usuário");
define("br_USERS", "Usuários");
define("br_VALID_EMAIL", "e-mail válido");
define("br_VALID_PASS_REQ", "Senha válida necessária");
define("br_VIEW_STATUS", "Ver Estado");
define("br_WELCOME_BACK", "Bem-vindo de volta! Está listado na categoria 'de férias'. Por favor, deixe o seu administrador ou gerente saber que você está de volta");
define("br_YOU_ARE_NOT_ALLOWED", "Você não tem permissão");
define("br_YOU_HAVE_REACHED_MAX_TICKETS", "Você atingiu a abertura máxima de bilhetes permitida.");
define("br_YOU_LL_NEED_TICKET_NUMBER", "Você precisa ter o número do bilhete, juntamente com seu e-mail para visualizar o status e progresso online.");
define("br_YOU_MUST_CHANGE_PASS", "Você deve alterar sua senha para continuar.");
define("br_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "Você deve digitar hosts para whitelist");
define("br_YOU_MUST_SELECT_ACTION_TO_PERFORM", "Você deve selecionar ação a ser executada");
define("br_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "Você deve selecionar pelo menos um item");
define("br_YOU_MUST_SELECT_ONE_EMAIL", "Você deve selecionar pelo menos um e-mail");
define("br_YOU_MUST_SELECT", "Você deve selecionar");
define("br_YOU_NEED_TO_SET_UPLOADDIR", "Você precisará configurar de upload dir.");
define("br_YOU_PIPE_WE_ACCEPT_POLICY", "Você precisa aceitar nossa política");
define("br_ZERO_RESULTS", "Consulta retornou 0 resultados"); 