<?php
define("es_A_DEPT", "un Departamento");
define("es_A_PRIORITY", "una prioridad");
define("es_ACCESS_DENIED", "Acceso denegado");
define("es_ACTION_DENIED_TICKET_LOCKED", "Acci&#243;n denegado. Venta de entradas est&#225; bloqueado por otra persona!");
define("es_ACTION_DENIED", "Acci&#243;n denegado");
define("es_ACTIVE", "Activo");
define("es_ADD_NEW_PREMADE_REPLY", "A&ntilde;adir Escribir nuevo Premade");
define("es_ADD_NEW_USER", "A&ntilde;adir un nuevo usuario");
define("es_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "Administrador de correo electr&#243;nico recibe una alerta por defecto. Seleccione los destinatarios adicionales a continuaci&#243;n");
define("es_ADMIN_EMAIL", "Admin Email");
define("es_ADMIN_PANEL", "El panel de administraci&#243;n");
define("es_ADVANCED", "Avanzado");
define("es_ALERT_FROM_EMAIL_ADDRESS", "Alerta (s) De Direcci&#243;n de correo electr&#243;nico");
define("es_ALERT_SUBJECT_MISSING", "Alerta tema desaparecidos");
define("es_ALERTS_NOTICES", "Alertas y Avisos");
define("es_ALL_DEP", "Todos Departamento");
define("es_ALL_DEPTS", "Todos los Departamentos");
define("es_ALL", "Todos"); 
define("es_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Permitir al cliente que sobrescribir / establecer la prioridad (boletos en l&#237;nea)");
define("es_ALLOWED_FILE_EXT_REQ", "Admite extensiones de archivo necesario");
define("es_ALLOWED", "permitido");
define("es_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "Un correo electr&#243;nico con el n&#250;mero de billete ha sido enviada a");
define("es_ANOTHER_DEPT_USING_HOST_COMBINATION", "Otro departamento con sede combinaci&#243;n de usuario.");
define("es_ANSWER", "Respuesta");
define("es_API_SETTINGS_UPDATED", "configuraci&#243;n actualizada de la API");
define("es_ARE_YOU_SURE_YOU_WANT", "&#191;Est&#225;s seguro de que desea");
define("es_ASSIGN", "asignar");
define("es_ASSIGNED_STAFF", "Asignaci&#243;n de Personal");
define("es_ASSIGNED_TICKETS", "Asignaci&#243;n de Entradas");
define("es_AT_LEAST_ONE_TOPIC", "por lo menos un tema");
define("es_ATTACH_FILE", "Adjuntar un archivo");
define("es_ATTACH_SETTINGS_UPDATED", "configuraci&#243;n actualizada Adjuntos");
define("es_ATTACH", "Accesorio");
define("es_ATTACHMENT_DISABLED", "Archivos adjuntos de movilidad reducida");
define("es_ATTEMPTS", "Los intentos");
define("es_AUTHENTICATION_REQUIRED", "Se requiere autenticaci&#243;n");
define("es_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Auto-asignar entradas reabierto al demandado por &#250;ltima &#171;disponible&#187;. (3 meses &lt;i&gt; l&#237;mite &lt;/ i&gt;)");
define("es_AUTOLOCK_TIME", "tiempo de auto-cierre");
define("es_AUTORESPONDERS_GLOBAL_SETTING", "Autorespondedores (ajuste global)");
define("es_AUTORESPONDERS", "Autoresponders");
define("es_AUTORESPONSE_FROM_EMAIL", "Auto respuesta de correo electr&#243;nico");
define("es_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Respuesta autom&#225;tica incluye el billete de identificaci&#243;n necesarios para comprobar el estado del billete");
define("es_BAD_PREFIX_UNDERSCORE", "prefijo Bad.Debe tener gui&#243;n bajo (_) al final. por ejemplo, &#171;ost_ '");
define("es_BAN_EMAIL_LOWER", "banemail");
define("es_BYTES_ALLOWED", "bytes permitido");
define("es_CAN_BE_APPENDED_TO_RESPONSES", "se pueden a&ntilde;adir a las respuestas. (Disponible como una opci&#243;n para los servicios p&#250;blicos)");
define("es_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "No se puede eliminar Departamento asociado con un temas de ayuda. Retire la primera asociaci&#243;n.");
define("es_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "No se puede eliminar con los miembros del Depto. Mover primer pentagrama.");
define("es_CANCEL", "Cancelar");
define("es_CATEGORY", "Categor&#237;a");
define("es_CELL_PHONE", "Tel&eacute;fono celular");
define("es_CHANGE_PASS", "Cambiar la contrase&ntilde;a");
define("es_CHANGE_PRIORITY", "change_priority");
define("es_CHECK_STATUS_OPENED_TICKETS", "Comprobar el estado del ticket abierto anteriormente. que dispone de archivos y la historia de todas sus solicitudes de soporte completo con respuestas.");
define("es_CHECK_STATUS", "Comprobar estado");
define("es_CLICKABLE_URL", "Seleccionables URL");
define("es_CLIENT_SESSION_TIMEOUT_IN_MINS", "m&#225;ximo tiempo de inactividad del cliente en cuesti&#243;n de minutos. Introduzca 0 para desactivar el tiempo de espera");
define("es_CLIENT_SESSION_TIMEOUT", "Cliente de tiempo de espera de sesi&#243;n");
define("es_CLOSE_LOWER", "cerrar");
define("es_CLOSE_REOPEN_TICKETS", "cerrar / abrir entradas");
define("es_CLOSE", "Cerrar");
define("es_CLOSED", "Cerrado");
define("es_COMMERCIAL_SUPPORT_AVAILABLE", "Soporte disponible Comercial");
define("es_CONF_FILE_ALREADY_MOD", "Configuraci&#243;n del archivo ya modificado!");
define("es_CONF_FILE_NOT_WRITABLE", "El archivo de configuraci&#243;n no es escribible");
define("es_CONFIRM_NEW_PASS", "Confirmar nueva contrase&ntilde;a");
define("es_CONFIRM", "Confirmar");
define("es_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Conflictos con sistema de correo electr&#243;nico por encima de");
define("es_CONTACT_ADMIN", "P&#243;ngase en contacto con administrador si cree que esto es un error");
define("es_CREATE_DATE", "Fecha de Creaci&#243;n");
define("es_CURR_PASS_REQ", "Contrase&ntilde;a actual requiere");
define("es_CURR_TIME", "La hora actual");
define("es_DATE_AND_TIME_FORMAT", "Fecha Hora y Formato");
define("es_DATE_AND_TIME", "Fecha y Hora");
define("es_DATE_FORMAT", "Formato de fecha");
define("es_DAY_DATE_TIME_FORMAT", "D&#237;a, hora y fecha Formato");
define("es_DAYLIGHT_SAVING", "Horario de verano");
define("es_DAYLIGHT_SAVINGS", "Horario de verano");
define("es_DB_NOT_EXISTS", "Base de datos no existe");
define("es_DEFAULT_DEPARTMENT", "Predeterminado Departamento");
define("es_DEFAULT_EMAIL_TEMPLATE", "Email plantilla predeterminada");
define("es_DEFAULT_EMAIL", "De correo electr&#243;nico predeterminado");
define("es_DEFAULT_PAGE_SIZE", "Por defecto el tama&ntilde;o de p&#225;gina");
define("es_DEFAULT_PRIORITY", "De prioridad por defecto");
define("es_DEFAULT_TIMEZONE", "Predeterminado Timezone");
define("es_DELETE_DEPS", "Depts Eliminar");
define("es_DELETE_LOWER", "borrar");
define("es_DELETE_TICKETS", "Billetes de eliminar");
define("es_DELETE", "Borrar");
define("es_DEPARTMENT_MANAGED", "Gerente del Departamento (spam)");
define("es_DEPARTMENT_MANAGER", "Gerente del Departamento de");
define("es_DEPARTMENT_MEMBERS", "Miembros del Departamento (spam)");
define("es_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Departamento en virtud del cual la &quot;respuesta&quot; se pondr&#225; a disposici&#243;n");
define("es_DEPARTMENTS", "Departamentos");
define("es_DEPENDS_ON_THE_TAG_BELOW", "depende de la etiqueta siguiente");
define("es_DEPT_DEPENDS_ON_EMAIL", "Departamento depende de correo electr&#243;nico y configuraci&#243;n de temas para ayudar a los boletos de entrada.");
define("es_DEPT_EMAIL_ABOVE", "Departamento de correo electr&#243;nico (arriba)");
define("es_DEPT_EMAIL", "Departamento de correo electr&#243;nico");
define("es_DEPT_MANAGER", "Administrador de Departamento");
define("es_DEPT_NAME", "Nombre del departamento");
define("es_DEPT_SIGNATURE", "Departamento de Firma");
define("es_DEPT_TRANSFER", "Departamento de Transferencia");
define("es_DEPT_TYPE", "Departamento Tipo");
define("es_DEPT", "Departamento");
define("es_DIR_MUST_BE_VALID_WRITABLE", "Directorio debe ser v&#225;lido y escritura");
define("es_DIRECTORY", "Directorio");
define("es_DISABLE", "Inhabilitar");
define("es_DISABLED", "Discapacitado");
define("es_DO_REQUESTED_ACTION", "hacer la acci&#243;n solicitada");
define("es_EDIT_PREMADE_REPLY", "Editar Premade respuesta");
define("es_EMAIL_ADD_SUCCESS", "Email a&ntilde;adido correctamente");
define("es_EMAIL_ADDED_TO_BANLIST", "Email a&ntilde;adido a la lista de ban");
define("es_EMAIL_ADDRESS", "Direcci&#243;n de correo electr&#243;nico");
define("es_EMAIL_ALREADY_BANNED", "Correo electr&#243;nico ya ha sido prohibido");
define("es_EMAIL_ALREADY_EXISTS", "Correo electr&#243;nico ya existe");
define("es_EMAIL_IN_BANLIST", "El correo electr&#243;nico es en la lista de ban. Debe ser eliminado para responder");
define("es_EMAIL_MISMATCH", "Correo electr&#243;nico no coincide.");
define("es_EMAIL_REMOVED", "Correo electr&#243;nico eliminado");
define("es_EMAIL_SETTINGS", "Configuraci&#243;n de correo electr&#243;nico");
define("es_EMAIL_UNKNOWN", "Correo electr&#243;nico desconocidos");
define("es_EMAIL_UPDATED_SUCCESS", "Correo electr&#243;nico actualizado correctamente");
define("es_ENABLE_AUTOCRON", "Cron Enable Auto");
define("es_ENABLE_CRON_CALL", "Habilitar llamada cron sobre la actividad del personal");
define("es_ENABLE_EMAIL_PIPING", "Habilitar correo electr&#243;nico de tuber&#237;as");
define("es_ENABLE_POP3_EMAIL_FETCH", "Habilitar correo electr&#243;nico POP3 a buscar");
define("es_ENABLE", "Permitir");
define("es_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Habilitado errores se env&#237;an al administrador de correo electr&#243;nico indicados anteriormente");
define("es_ENTER_MESSAGE", "Introduzca Mensaje");
define("es_ENTER_VALID_NUM", "Introduzca un n&#250;mero v&#225;lido");
define("es_ERR_SQL_SYNTAX", "Usted tiene un error en la sintaxis SQL");
define("es_ERROR_OCCURED", "Error (s) ocurri&#243;.");
define("es_ERROR_OCCURRED", "Ocurri&#243; un error. Ver los mensajes de error a continuaci&#243;n.");
define("es_EXCESSIVE_LOGIN_ATTEMPTS", "Nombre de los intentos excesivo");
define("es_FATAL_ERROR", "Error grave");
define("es_FETCH_INTERVAL_REQUIRE", "Fetch intervalo requerido");
define("es_FILE_TOO_BIG", "Archivo es demasiado grande");
define("es_FILE_UPLOAD_DISABLED_PHP_INI", "La directiva &quot;file_uploads 'est&#225; deshabilitado en php.ini");
define("es_FIRST_NAME", "Nombre");
define("es_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "Para el correo POP3 a buscar al trabajo debe establecer un cron job o simplemente permitir auto-cron");
define("es_FORGOT_LOGIN_INFO", "&#191;Ha olvidado su informaci&#243;n de acceso? Por favor, &lt;a href='open.php'&gt; abierto una &lt;nuevo billete / a&gt;.");
define("es_FROM_BANLIST", "de la lista de ban");
define("es_FULL_NAME", "Nombre completo");
define("es_GENERAL_INQUIRY", "Consultas Generales");
define("es_GENERAL_SETTINGS", "Configuraci&#243;n general");
define("es_GET_A_PEACE_OF_MIND", "Obtener una paz de la mente");
define("es_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "autoresponder Mundial en la secci&#243;n de preferencias deben estar habilitadas para el Departamento 'Habilitar' configuraci&#243;n surta efecto.");
define("es_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "configuraci&#243;n global que puede ser desactivado a nivel de correo electr&#243;nico");
define("es_HELP_TOPIC", "Tema de ayuda");
define("es_HELPDESK_NAME", "Servicio de Ayuda Nombre / T&#237;tulo");
define("es_HELPDESK_STATUS", "Helpdesk Estado");
define("es_HELPDESK_URL", "Servicio de Ayuda URL");
define("es_HELPS_WITH_SPAM", "Ayuda con el spam y el control de inundaciones. Introduzca 0 para un n&#250;mero ilimitado");
define("es_HOME", "Casa");
define("es_HOST_MISSING", "Anfitri&#243;n desaparecidos");
define("es_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Horas antes del billete est&#225; marcado retraso. Introduzca 0 para desactivar el envejecimiento");
define("es_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "Si se habilita bloqueo billete obtener auto-renovaci&#243;n en la actividad de forma.");
define("es_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "Si desea enviar sus comentarios o informaci&#243;n adicional sobre la misma cuesti&#243;n, por favor, siga las instrucciones del correo electr&#243;nico.");
define("es_IMAP_DOESNT_EXISTS", "IMAP no existe. PHP debe ser compilado con IMAP.");
define("es_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "Con el fin de optimizar las solicitudes de apoyo y un mejor servicio, utilizamos un sistema de tickets de soporte. Cada solicitud de ayuda se le asigna un n&#250;mero de billete &#250;nico que puede utilizar para realizar el seguimiento del progreso y respuestas en l&#237;nea. Para su informaci&#243;n le proporcionamos archivos completos y la historia de todas sus solicitudes de apoyo.");
define("es_INDICATE_SOURCE", "Indique la fuente");
define("es_INSTALL_COMPLETE", "Enhorabuena osTicket b&#225;sica completa!");
define("es_INTERNAL_ERROR_OCCURED", "Error interno");
define("es_INTERNAL_ERROR", "Error interno. Por favor, aseg&#250;rese de que la descarga es la &#250;ltima");
define("es_INTERNAL_NOTE_POSTED", "Nota interna Nuevo");
define("es_INVALID_ATTACH", "Adjunto v&#225;lido");
define("es_INVALID_FILE_TYPE", "Tipo de archivo no v&#225;lido");
define("es_INVALID_FILE", "De archivo no v&#225;lido");
define("es_INVALID_LOGIN", "Entrada no v&#225;lida");
define("es_INVALID_SOURCE", "Fuente no v&#225;lida");
define("es_INVALID_SQL_SCHEMA", "SQL no v&#225;lida del esquema. Obt&eacute;n ayuda de desarrolladores");
define("es_INVALID_UPLOAD_DIR", "No v&#225;lido subir dir");
define("es_INVALID", "Inv&#225;lido");
define("es_KNOWLEDGE_BASE", "Base de conocimientos");
define("es_LANG_PRIVATE", "Privado");
define("es_LANG_PUBLIC", "P&#250;blico");
define("es_LAST_NAME", "Apellido");
define("es_LAST_RESPONDENT", "&#218;ltima demandado");
define("es_LAST_UPDATED", "&#218;ltima actualizaci&#243;n");
define("es_LOCK", "Cerradura");
define("es_LOCKED", "Bloqueado");
define("es_MAIL_METH", "M&eacute;todos de correo");
define("es_MAIL_PARSE_ERRORS", "Correo errores de an&#225;lisis");
define("es_MAKE_PRIVATE", "Haga privado");
define("es_MAKE_PUBLIC", "Hacer p&#250;blica");
define("es_MAKE_URL_CLICKABLE", "Hacer hacer clic en las URL");
define("es_MANAGER", "Gerente");
define("es_MASS_MANAGE_TICKETS", "gesti&#243;n de entradas de masas. P&#243;ngase en contacto con administrador de dicho acceso");
define("es_MAX_ALLOWED", "N&#250;mero m&#225;ximo de personas permitidas");
define("es_MAX_FILE_SIZED_REQ", "El tama&ntilde;o m&#225;ximo de archivo requerido");
define("es_MAX_LOGIN_ATTEMPTS", "Has llegado ingreso fallido intento m&#225;xima permitida. Int&eacute;ntelo de nuevo despu&eacute;s de 5 minutos o href='open.php'&gt; &lt;a abrir un &lt;nuevo billete / a&gt;");
define("es_MAX_OPEN_TICKETS", "M&#225;xima &lt;b&gt; Abiertos / Tickets b&gt;");
define("es_MAX_PAGE_SIZE", "M&#225;ximo tama&ntilde;o de p&#225;gina");
define("es_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Mensaje adjunto a una confirmaci&#243;n del boleto existente");
define("es_MESSAGE_POSTED_SUCCESS", "Mensaje Publicado con &eacute;xito");
define("es_MESSAGE_REQUIRED", "Mensaje requeridos");
define("es_MESSAGE", "Mensaje");
define("es_MIN_TO_LOCK_A_TICKET", "Acta para bloquear una entrada en la actividad. Introduzca 0 para deshabilitar el bloqueo");
define("es_MISSING_MESSAGE", "Faltan las p&#225;ginas de ID");
define("es_MISSING_OR_INVALID_GROUP", "Falta o no v&#225;lido grupo");
define("es_MISSING_SQL_SCHEMA", "Falta de esquema SQL");
define("es_MOBILE", "M&#243;vil");
define("es_MUST_BE_SIX_CHARS", "Debe tener al menos 6 caracteres");
define("es_MUST_SELECT_PRIORITY", "Usted debe seleccionar la prioridad");
define("es_MY_ACCOUNT", "Mi Cuenta");
define("es_MY_PREFERENCES", "Mis preferencias");
define("es_MY_PROFILE_INFO", "Mi perfil Informaci&#243;n");
define("es_MY_PROFILE", "Mi Perfil");
define("es_NAME", "Nombre");
define("es_NEED_HELP_QUESTION", "&#191;Necesita ayuda?");
define("es_NEW_DEPT", "Nuevo Departamento");
define("es_NEW_MESSAGE_ALERT", "Nuevo mensaje de alerta");
define("es_NEW_MESSAGE", "Nuevo mensaje");
define("es_NEW_PASS_NOT_MATCH", "Nueva contrase&ntilde;a (s) no coinciden");
define("es_NEW_PASS_REQ", "Nueva contrase&ntilde;a requerida");
define("es_NEW_PASS_SAME_OLD", "La nueva contrase&ntilde;a es la misma que la contrase&ntilde;a de edad");
define("es_NEW_PREMADE_REPLY", "Nueva Premade respuesta");
define("es_NEW_TICKET_ALERT", "Nueva alerta de entradas");
define("es_NEW_TICKET", "Nuevo billete");
define("es_NO_ACCESS_TO_TICKET", "Usted no tiene acceso al boleto");
define("es_NO_PERMISSION_TO_REASSIGN", "Usted no tiene permiso para volver a asignar los boletos asignados");
define("es_NO_PERMISSION_TO", "Usted no tiene permiso para");
define("es_NO_REPLY_EMAIL_ADDRESS", "No hay direcci&#243;n de correo electr&#243;nico Responder");
define("es_NO_REPLY_EMAIL", "No hay respuesta por correo electr&#243;nico");
define("es_NO_STAFF_FOUND", "Ning&#250;n miembro del personal encontrado");
define("es_NO_SUCH_FILE", "No existe el fichero");
define("es_NO_TICKETS_FOUND", "NO billetes encontrados.");
define("es_NO_TICKETS_SELECTED", "No hay entradas seleccionadas. Debe seleccionar al menos un boleto.");
define("es_NO_USER_ADD_USER", "No hay usuarios (Agregar usuarios)");
define("es_NONE", "Ninguno");
define("es_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "No se les permite cambiar la prioridad de venta de las entradas");
define("es_NOT_ALLOWED_TO_TRANSFER_TICKETS", "No est&#225; permitido transferir boletos.");
define("es_NOTE_REQ", "Nota requiere mensaje");
define("es_NOTE_REQUIRED", "Nota / Mensaje requeridos");
define("es_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Las noticias enviadas a utilizar el usuario 'No Reply &quot;Correo electr&#243;nico&quot; que, a alertas uso personal &quot;Alerta de correo electr&#243;nico&quot; indicados anteriormente como direcci&#243;n FROM, respectivamente.");
define("es_OBSERVE", "Observar");
define("es_OF", "di");
define("es_OFFICE_PHONE", "Tel&eacute;fono de la oficina");
define("es_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "El modo sin conexi&#243;n a la interfaz de cliente con discapacidad y &lt;b&gt; s&#243;lo / b&gt; permite &lt;b&gt; super admin / b&gt; para acceder a Panel de control de personal");
define("es_OFFLINE", "Fuera de l&#237;nea");
define("es_ONLINE", "En l&#237;nea");
define("es_OPEN_LOWER", "abierto");
define("es_OPEN_NEW_TICKET", "Abrir Nuevo Ticket");
define("es_OPEN_TICKET", "Abrir Ticket");
define("es_OPEN", "Abierto");
define("es_OSTICKET_BASIC_INSTALL", "osTicket b&#225;sicas de instalaci&#243;n");
define("es_OSTICKET_INSTALLER", "Instalador osTicket");
define("es_OSTICKET_REQUIRES_MYSQL", "osTicket requiere MySQL 4.1.1 o mejor! Por favor, actualice");
define("es_OUTGOING_EMAIL", "De correo saliente");
define("es_OVERDUE_LOWER", "atrasado");
define("es_OVERDUE_TICKET_ALERT", "Atrasado Alerta Venta de entradas");
define("es_OVERLIMIT_NOTICE", "Exceder el L&#237;mite Aviso");
define("es_PAGE", "p&#225;gina");
define("es_PASS_CHANGE_SUCCESS", "Contrase&ntilde;a cambiada con &eacute;xito");
define("es_PASS_TO_NOT_MATCH", "contrase&ntilde;as no coinciden!");
define("es_PASSWORD_REQUIRED", "Se requiere contrase&ntilde;a");
define("es_PER_EMAIL", "por correo electr&#243;nico");
define("es_PERM_DENIED", "Perm. Denegado.");
define("es_PHONE_NUM_REQ", "N &#186; de tel&eacute;fono necesarios");
define("es_PHONE", "Tel&eacute;fono");
define("es_PHP_DATE_MANUAL", "Por favor, consulte &lt;a href='http://php.net/date' target='_blank'&gt; Manual de PHP &lt;/ a&gt; para obtener par&#225;metros que admite.");
define("es_PHP_OUT_OF_DATE", "PHP instalaci&#243;n seriamente fuera de fecha");
define("es_PHRASE_TOO_SHORT", "frase es muy corta!");
define("es_PHRASE_TWO_WORDS", "Frase de 2 + palabras");
define("es_PLEASE_ENTER_VALID_EMAIL", "Por favor ingrese un correo electr&#243;nico v&#225;lida.");
define("es_PLEASE_FILL_TO_OPEN_A_TICKET", "Por favor, rellene el siguiente formulario para abrir un nuevo ticket.");
define("es_POSSIBLE_ERROR_DETECTED", "Los posibles errores detectados, por favor revise las advertencias a continuaci&#243;n");
define("es_POSSIBLY_ACCESS_DENIED", "Posiblemente de acceso denegado, si usted cree que esto es un error por favor, obtener asistencia t&eacute;cnica.");
define("es_POSSIBLY_INVALID_TICKET", "Posiblemente billete v&#225;lido de identificaci&#243;n");
define("es_POST_REPLY", "Responder");
define("es_POSTNOTE", "postnote");
define("es_PREF_ERROR", "Preferencia de error de actualizaci&#243;n.");
define("es_PREF_UPDATED", "Preferencias Actualizado correctamente");
define("es_PREFERENCES", "Preferencias");
define("es_PREFERRED_TIMEZONE", "Preferencia Timezone");
define("es_PREMADE_REPLIES", "Premade Respuestas");
define("es_PREMADE_REPLY", "Premade respuesta");
define("es_PRIMARY_OUTGOING_MAIL", "Correo electr&#243;nico saliente Primaria");
define("es_PRIORITY_CHANGED_SUCCESS", "Prioridad cambiado correctamente");
define("es_PRIORITY", "Prioridad");
define("es_PRIVATE_HIDDEN", "Privado (Oculto)");
define("es_PROBLEM_CHANGING_PRIORITY", "Problemas al cambiar prioridad.");
define("es_PROBLEM_CLOSING_TICKET", "Problemas para cerrar la entrada.");
define("es_PROBLEM_RELEASING_TICKET", "Problemas de soltar el billete.");
define("es_PROBLEM_REOPENING_TICKET", "Problemas de la reapertura del billete.");
define("es_PROBLEMS_ADMIN_PAGE", "Problemas de carga solicitada p&#225;gina de administraci&#243;n.");
define("es_PROBLEMS_DELETING_THE_TICKET", "Problemas de eliminar el billete");
define("es_PROBLEMS_DISPLAYING_DIR", "Los problemas que muestra el directorio");
define("es_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Problemas que marca el ticket de la mora");
define("es_PROCESS", "proceso");
define("es_PROF_INST_AVAILABLE", "Instalaci&#243;n Profesional disponible");
define("es_PROFILE_UPDATE_SUCCESS", "Perfil Actualizado correctamente");
define("es_PUBLIC", "P&#250;blico");
define("es_QUERY", "Pregunta");
define("es_RANDOM", "Azar");
define("es_RECOMMENDED", "recomendado");
define("es_REJECTED", "rechazado");
define("es_RELEASE_LOWER", "liberaci&#243;n");
define("es_REMOVING_QUOTED_REPLY", "Extracci&#243;n de respuesta citado");
define("es_REOPEN_LOWER", "reabrir");
define("es_REOPEN", "Reabrir");
define("es_REOPENED_TICKETS", "Nuevamente entradas");
define("es_REPLY_REQUIRED", "Respuesta necesaria");
define("es_REPLY_SEPARATOR_TAG", "Responder etiqueta de separaci&#243;n");
define("es_REPLY_TITLE", "Responder T&#237;tulo");
define("es_REPLY", "respuesta");
define("es_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Se requiere cuando es p&#250;blica Departamento");
define("es_REQUIRED", "necesario");
define("es_RESET_CHANGES", "Perd&#237; cambios");
define("es_RESET", "Reajustar");
define("es_RESPONSE_MESSAGE_REQUIRED", "mensaje de respuesta requerida");
define("es_RESPONSE_POSTED_SUCCESS", "Respuesta Publicado con &eacute;xito");
define("es_SALVE_EMAIL_HEADERS", "Guardar encabezados de los mensajes");
define("es_SAVE_CHANGES", "Guardar cambios");
define("es_SAVE_RAW_HEADERS", "Guardar primas encabezados");
define("es_SAVE", "Guardar");
define("es_SEARCH_FOR", "Buscar");
define("es_SEARCH_TERM_MORE_THAN_3_CHARS", "t&eacute;rminos a buscar deben tener m&#225;s de 3 caracteres");
define("es_SEARCH", "B&#250;squeda");
define("es_SECURITY_VIOLATION", "Seguridad violaci&#243;n. violaci&#243;nes repetidas resultar&#225;n en su cuenta est&#225; bloqueada.");
define("es_SELECT_ASSIGNEE", "Seleccione el cesionario");
define("es_SELECT_DEFAULT_DEPT", "Seleccione Predeterminado Departamento");
define("es_SELECT_DEPARTMENT", "Elegir el servicio");
define("es_SELECT_HELP_TOPIC", "Seleccione tema de ayuda");
define("es_SELECT_MANAGER_OPT", "Seleccione Manager (opcional)");
define("es_SELECT_ONE", "Seleccione una");
define("es_SELECT_RECIPIENTS", "Seleccione los destinatarios");
define("es_SELECT", "Seleccionar");
define("es_SELECTED_DEPT_DELETED", "departamentos seleccionados eliminado");
define("es_SELECTED_EMAILS_DELETED", "correo electr&#243;nico seleccionado (s) borr&#243;");
define("es_SELECTED_EMAILS_REMOVED", "mensajes de correo electr&#243;nico seleccionado eliminado de la lista de ban");
define("es_SELECTED_EMAILS_USED_BY_A_DEPT", "Uno o m&#225;s de los mensajes de correo electr&#243;nico seleccionado est&#225; siendo utilizado por una asociaci&#243;n Depto quitar primero.");
define("es_SELECTED_ENTRIES", "entradas seleccionadas");
define("es_SELECTED_REPLIES_DELETED", "Selecci&#243;n de las respuestas eliminado");
define("es_SELECTED_REPLIES_DISABLED", "Selecci&#243;n de respuestas con discapacidad");
define("es_SELECTED_REPLIES_ENABLED", "Selecci&#243;n de respuestas habilitado");
define("es_SELECTED_SERVICES_ENABLED", "servicios seleccionados habilitado");
define("es_SELECTED_TICKETS_CLOSED", "entradas seleccionadas cerrada");
define("es_SELECTED_TICKETS_DELETED", "entradas seleccionadas eliminado");
define("es_SELECTED_TICKETS_OVERDUE", "entradas seleccionadas marcada atrasados");
define("es_SELECTED_TICKETS_REOPENED", "entradas seleccionadas reapertura");
define("es_SELECTED_TICKETS", "entradas seleccionadas");
define("es_SELECTED_TOPIC_DISABLED", "temas seleccionados con discapacidad");
define("es_SELECTED_TOPICS_DELETED", "temas seleccionados eliminado");
define("es_SELECTED_USERS", "usuario seleccionado (s)");
define("es_SEND_OVERLIMIT_NOTICE", "Enviar aviso sobrel&#237;mite");
define("es_SENT_ONLY_ONCE", "Enviado &lt;b&gt; una sola vez &lt;/ b&gt; sobre la violaci&#243;n l&#237;mite para el usuario. &lt;b&gt; Admin se alertas sobre denegaciones TODOS por default &lt;/ b&gt;");
define("es_SEQUENTIAL", "Secuencial");
define("es_SERVER_TIME", "Horario del servidor");
define("es_SESSION_TIMED_OUT", "Per&#237;odo de sesiones el tiempo de espera debido a la inactividad");
define("es_SHOW_ASSIGNED_TICKETS", "Mostrar asignado entradas a la cola abierta");
define("es_SHOWING", "Listado");
define("es_SIGNATURE", "Firma");
define("es_SORT_BY", "Clasificar por");
define("es_SQL_ERRORS", "SQL errores");
define("es_STAFF_MAX_IDLE_TIME", "m&#225;ximo tiempo de inactividad de Personal en cuesti&#243;n de minutos. Introduzca 0 para desactivar el tiempo de espera");
define("es_STAFF_MEMBERS", "Miembros del Personal");
define("es_STAFF_PANEL", "Personal del panel");
define("es_STAFF_SESSION_TIMEOUT", "Personal de tiempo de espera de sesi&#243;n");
define("es_STATUS", "Estado");
define("es_STRIP_QUOTED_REPLY", "Citado Franja de respuesta");
define("es_SUBJECT_MISSING", "sujetos que faltan");
define("es_SUBJECT", "Tema");
define("es_SUBMIT_A_NEW_REQUEST", "Presentar una nueva solicitud de soporte. Por favor, proporcione tantos detalles como sea posible, as&#237; que mejor le puede ayudar. Para actualizar un ticket presentados anteriormente, por favor, utilice el formulario a la derecha. Una direcci&#243;n de correo electr&#243;nico v&#225;lida se requiere.");
define("es_SUMMARY_OF_THE_ISSUE_REQUIRED", "Resumen de la cuesti&#243;n requiere");
define("es_SUPPORT_OFFLINE", "sistema de Ticket de Ayuda no est&#225; en l&#237;nea");
define("es_SUPPORT_TEAM", "Equipo de Soporte");
define("es_SUPPORT_TICKET_CREATED", "solicitud Ticket de Ayuda creado");
define("es_SUPPORT_TICKET_REQ_DENIED_FOR", "petici&#243;n denegada por Ticket de Ayuda");
define("es_SUPPORT_TICKET_SYSTEM", "Apoyo sistema de tickets");
define("es_SYSTEM_ADMIN_EMAIL_ADDRESS", "Administrador de Sistema de Correo Electr&#243;nico");
define("es_SYSTEM_ERRORS", "Errores de sistema");
define("es_SYSTEM_OFFLINE", "Sistema en l&#237;nea");
define("es_SYSTEM_PREFERENCES_AND_SETTINGS", "Preferencias del Sistema y Configuraci&#243;n");
define("es_TABLE_PREFIX", "Cuadro prefijo");
define("es_TEMPLATE_ALERT_MSG_REQUIRED", "Plantilla de mensaje de alerta necesaria");
define("es_TEMPLATE_MSG_REQUIRED", "Plantilla de mensaje requerido");
define("es_TEMPLATES_UPDATED_SUCCESS", "Plantillas actualizado correctamente");
define("es_THANK_YOU_FOR_CHOOSING_OSTICKET", "Gracias por elegir osTicket. \ Nmake seguro de que incorporarse a foros de osTicket http://osticket.com/forums a permanecer hasta que la fecha de las &#250;ltimas noticias, alertas de seguridad y actualizaciones. foros osTicket tambi&eacute;n es un gran lugar para conseguir ayuda, orientaci&#243;n y ayuda. Adem&#225;s de los foros, wiki osTicket proporciona &#250;til colecci&#243;n de materiales educativos, documentaci&#243;n y notas de la comunidad. \ N \ n Si usted est&#225; buscando un mayor nivel de apoyo, ofrecemos servicios profesionales y apoyo personalizado comercial con tiempos de respuesta garantizados y acceso al equipo de desarrollo.Tambi&eacute;n podemos personalizar el sistema para satisfacer sus necesidades &#250;nicas. Informaci&#243;n \ nPara m&#225;s informaci&#243;n o para discutir sus necesidades, por favor p&#243;ngase en contacto con nosotros hoy. Cualquier comentario ser&#225; apreciado! \ NosTicket equipo");
define("es_THANK_YOU_FOR_CONTACTING_US", "Gracias por contactar con nosotros. &lt;br&gt; Una solicitud ticket de soporte ha sido creado y un representante que recibir&#225; a la brevedad si es necesario.");
define("es_THANK_YOU_HELPDESK_OFFLINE", "Gracias por su inter&eacute;s en contactar con nosotros. &lt;br&gt; Nuestro servicio de asistencia est&#225; en l&#237;nea en este momento, por favor regrese en otro momento.");
define("es_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "Esta es la configuraci&#243;n global que puede ser desactivado a nivel del departamento");
define("es_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Venta de entradas ya asignadas al personal.");
define("es_TICKET_ALREADY_ASSIGNED" , "Venta de entradas ya est&#225; asignado.");
define("es_TICKET_ALREADY_IN_DEPT", "Venta de entradas ya est&#225;n en el Departamento");
define("es_TICKET_ASSIGNED_TO_THE_STAFF", "Venta de entradas asignadas al personal");
define("es_TICKET_CREATED_BY_STAFF", "Venta de entradas creadas por el personal");
define("es_TICKET_CREATED_SUCCESS", "Venta de entradas creado correctamente");
define("es_TICKET_DELETED_FOREVER", "Venta de entradas borrado para siempre");
define("es_TICKET_DENIED_403", "Venta de entradas neg&#243; Error # 403");
define("es_TICKET_DENIED_NOTICE", "Venta de entradas denegado Aviso");
define("es_TICKET_FLAGGED_AS_OVERDUE", "Venta de entradas marcadas como pendientes");
define("es_TICKET_GRACE_PERIOD", "Venta de entradas plazo de gracia");
define("es_TICKET_ID", "Venta de entradas ID");
define("es_TICKET_LOWER", "boleto");
define("es_TICKET_NOT_ASSIGNED", "Venta de entradas no se ha asignado!");
define("es_TICKET_OPTIONS_AND_SETTINGS", "Venta de entradas Opciones de Configuraci&#243;n y");
define("es_TICKET_PRIORITY", "Venta de entradas prioridad");
define("es_TICKET_RELEASED_FROM", "Venta de entradas en libertad (sin asignar) de");
define("es_TICKET_STATUS_SET_TO", "estado de los tickets establece en");
define("es_TICKET_STATUS", "Venta de entradas de estado");
define("es_TICKET_TRANSFER", "Venta de entradas transferido correctamente");
define("es_TICKET_WILL_BE_REOPENED", "Venta de entradas se abrir&#225; nuevamente en el poste mensaje");
define("es_TICKETS_PER_PAGE", "Entradas / art&#237;culos por p&#225;gina");
define("es_TICKETS", "Entradas");
define("es_TIME_FORMAT", "Formato de hora");
define("es_TITLE_ALREADY_EXISTS", "T&#237;tulo ya existe");
define("es_TITLE_REQ", "T&#237;tulo requerido");
define("es_TITLE_REQUIRED", "T&#237;tulo requerido");
define("es_TITLE", "T&#237;tulo");
define("es_TO_BAN_EMAILS", "la prohibici&#243;n de mensajes de correo electr&#243;nico");
define("es_TO_CLOSE", "para cerrar");
define("es_TO_DELETE_SELECTED_DEPTS", "para borrar un Depts");
define("es_TO_DELETE_TICKETS", "para borrar entradas");
define("es_TO_DELETE", "para eliminar");
define("es_TO_DISABLE", "para desactivar");
define("es_TO_ENABLE", "para permitir que");
define("es_TO_FLAG_TICKETS_OVERDUE", "a los billetes de bandera mora");
define("es_TO_LOCK", "para bloquear");
define("es_TO_MAKE_SELECTED_DEPTS_PRIVATE", "seleccionados para hacer Depts privado");
define("es_TO_MAKE_SELECTED_DEPTS_PUBLIC", "para hacer p&#250;blicos seleccionados Depts");
define("es_TO_MARK_SELECTED_TICKETS_OVERDUE", "para marcar seleccionados boletos vencidos / rancio");
define("es_TO_REM_EMAILS_FROM_BANLIST", "eliminar e-mails de la lista de ban.");
define("es_TO_REOPEN", "para volver a abrir");
define("es_TO_VIEW_THE_STATUS_OF_A_TICKET", "Para ver el estado de un ticket, nos proporciona sus datos de acceso a continuaci&#243;n. &lt;br/&gt; Si es tu primera vez en contacto con nosotros o has perdido el ticket de identificaci&#243;n, por favor haga clic aqu&#237; &lt;a href='open.php'&gt; &lt;/ a&gt; para abrir un nuevo ticket.");
define("es_TO", "a");
define("es_TOGGLE", "Palanca");
define("es_TOPIC_TOO_SHORT", "El tema es demasiado corto. 5 caracteres m&#237;nimo");
define("es_TRANSFER", "transferencia");
define("es_TRY_AGAIN", "Int&eacute;ntalo de nuevo");
define("es_TYPE", "Tipo");
define("es_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "No se puede agregar el correo electr&#243;nico a la lista de ban");
define("es_UNABLE_TO_ADD_EMAIL", "No se puede a&ntilde;adir correo electr&#243;nico. Error interno");
define("es_UNABLE_TO_ADD_MAIL_TO_BANLIST", "No se puede agregar a la lista de ban-mail. Int&eacute;ntalo de nuevo");
define("es_UNABLE_TO_ASSIGN_TICKET", "No se puede asignar el billete");
define("es_UNABLE_TO_COMPLETE_ACTION", "No se puede completar la acci&#243;n");
define("es_UNABLE_TO_COMPLETE_PASS_CHANGE", "No se puede completar cambio de contrase&ntilde;a. Error interno.");
define("es_UNABLE_TO_COMPLETE_THE_TRANSFER", "No se puede completar la transferencia");
define("es_UNABLE_TO_CONNECT_MYSQL", "No se puede conectar al servidor MySQL. Posiblemente informaci&#243;n de acceso no v&#225;lido. MedlinePlus");
define("es_UNABLE_TO_CREATE_DB", "No se puede crear la base de datos debido a la autorizaci&#243;n");
define("es_UNABLE_TO_CREATE_THE_REPLY", "No se puede crear la respuesta. Error interno");
define("es_UNABLE_TO_CREATE_TICKET", "No se puede crear el billete. Corrija el error (s) y vuelva a intentarlo");
define("es_UNABLE_TO_DELETE_SELECTED_DEPT", "No se puede eliminar departamentos seleccionados.");
define("es_UNABLE_TO_DELETE_SELECTED_EMAILS", "No se puede eliminar correo electr&#243;nico seleccionado (s).");
define("es_UNABLE_TO_DISABLE_SELECTED_TOPICS", "No se puede desactivar temas seleccionados");
define("es_UNABLE_TO_FETCH_INFO_ON", "No se pudieron obtener informaci&#243;n sobre");
define("es_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "No se puede hacer eliminar mensajes de correo electr&#243;nico, seleccione");
define("es_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "No se puede hacer el departamento seleccionado (s) privada. Posiblemente ya privado!");
define("es_UNABLE_TO_OPEN_CONF_FILE", "No se puede abrir el archivo de configuraci&#243;n para la escritura. Permiso denegado!");
define("es_UNABLE_TO_POST_RESPONSE", "No se puede enviar la respuesta.");
define("es_UNABLE_TO_POST_THE_MESSAGE", "No se puede enviar el mensaje");
define("es_UNABLE_TO_POST_THE_NOTE", "No se puede enviar la nota.");
define("es_UNABLE_TO_REMOVE_EMAIL", "No se puede eliminar el correo electr&#243;nico");
define("es_UNABLE_TO_SELECT_DB", "No se puede seleccionar la base de datos");
define("es_UNABLE_TO_UPDATE_EMAIL", "No se puede actualizar de correo electr&#243;nico. Error interno");
define("es_UNBAN_EMAIL_LOWER", "unbanemail");
define("es_UNKNOWN_ACTION", "desconocida por el");
define("es_UNKNOWN_BANLIST_COMMAND", "comando de la lista de ban Uknown!");
define("es_UNKNOWN_COMMAND", "Uknown comando!");
define("es_UNKNOWN_DEPT_ACTION", "Desconocida acci&#243;n Departamento");
define("es_UNKNOWN", "Desconocido");
define("es_UPDATE_DEPARTMENT", "Actualizaci&#243;n Departamento");
define("es_UPDATE_ERROR", "Actualizaci&#243;n de error!");
define("es_UPDATED_SUCCESS", "actualizado correctamente");
define("es_UPLOAD_DIR_INVALID", "subir v&#225;lido dir. P&#243;ngase en contacto con admin.");
define("es_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "prioridad Utilice el correo electr&#243;nico enviado por correo electr&#243;nico cuando las entradas disponibles ()");
define("es_USERNAME_MISSING", "Nombre de usuario que faltan");
define("es_USERNAME", "Nombre de usuario");
define("es_USERS", "Usuario");
define("es_VALID_EMAIL", "V&#225;lido correo electr&#243;nico");
define("es_VALID_PASS_REQ", "V&#225;lido contrase&ntilde;a requerida");
define("es_VIEW_STATUS", "Ver el estado");
define("es_WELCOME_BACK", "Bienvenido de nuevo! Usted est&#225; clasificada como &quot;de vacaciones&quot; Por favor, administrador o el administrador de saber que est&#225;n de vuelta.");
define("es_WELCOME_TO_SUPPORT_CENTER", "Bienvenido al centro de soporte.");
define("es_YOU_ARE_NOT_ALLOWED", "No est&#225; permitido");
define("es_YOU_HAVE_REACHED_MAX_TICKETS", "Has llegado al m&#225;ximo permitido billetes abiertos.");
define("es_YOU_LL_NEED_TICKET_NUMBER", "Usted necesitar&#225; el n&#250;mero de ticket, junto con su correo electr&#243;nico para ver el estado y progreso en l&#237;nea.");
define("es_YOU_MUST_CHANGE_PASS", "Debe cambiar su contrase&ntilde;a para continuar.");
define("es_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "Debe introducir los ej&eacute;rcitos a la lista blanca");
define("es_YOU_MUST_SELECT_ACTION_TO_PERFORM", "Usted debe seleccionar la acci&#243;n a realizar");
define("es_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "Debe seleccionar al menos un punto");
define("es_YOU_MUST_SELECT_ONE_EMAIL", "Debe seleccionar al menos un e-mail");
define("es_YOU_MUST_SELECT", "Usted debe seleccionar");
define("es_YOU_NEED_TO_SET_UPLOADDIR", "Necesitas dir configuraci&#243;n de subida.");
define("es_YOU_PIPE_WE_ACCEPT_POLICY", "Usted tuber&#237;a aceptamos la pol&#237;tica");
define("es_ZERO_RESULTS", "Consulta ha devuelto 0 resultados ");
