<?php
define("he_A_DEPT", "מחלקה");
define("he_A_PRIORITY", "עדיפות");
define("he_ACCESS_DENIED", "גישה מוגבלת");
define("he_ACTION_DENIED_TICKET_LOCKED", "גישה מוגבלת. הפניה הועברה למישהו אחר!");
define("he_ACTION_DENIED", "פעולה נחסמה");
define("he_ACTIVE", "פעיל");
define("he_ADD_NEW_PREMADE_REPLY", "הוסף תגובה מוכנה מראש");
define("he_ADD_NEW_USER", "הוסף משתמש חדש");
define("he_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "התראות אוטומטיות נשלחות למנהל כברירת מחדל. בחר נמענים נוספים למטה");
define("he_ADMIN_EMAIL", "דואל מנהל");
define("he_ADMIN_PANEL", "פאנל ניהול");
define("he_ADVANCED", "מתקדם");
define("he_ALERT_FROM_EMAIL_ADDRESS", "התראות מכתובת דואל");
define("he_ALERT_SUBJECT_MISSING", "חסר נושא להתראה");
define("he_ALERTS_NOTICES", "התראות &amp;הערות");
define("he_ALL_DEP", "כל המחלקה");
define("he_ALL_DEPTS", "כל המחלקות");
define("he_ALL", "הכל");
define("he_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "לאפשר ללקוחות לעדכן/לקבוע עדיפות (online tickets)");
define("he_ALLOWED_FILE_EXT_REQ", "סוגי סיומות לקבצים מורשים");
define("he_ALLOWED", "מורשה");
define("he_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "הודעת דואל עם מספר הפניה נשלחה ל ");
define("he_ANOTHER_DEPT_USING_HOST_COMBINATION", "מחלקת המחבר משתמשת בשילוב מארח/משתמש");
define("he_ANSWER", "תשובה");
define("he_API_SETTINGS_UPDATED", "API עדכון הגדרות");
define("he_ARE_YOU_SURE_YOU_WANT", "האם אתה בטוח שאתה רוצה ");
define("he_ASSIGN", "הקצאה");
define("he_ASSIGNED_STAFF", "שייוך חבר צוות");
define("he_ASSIGNED_TICKETS", "פניה משוייכת");
define("he_AT_LEAST_ONE_TOPIC", "לפחות נושא אחד");
define("he_ATTACH_FILE", "קובץ מצורף");
define("he_ATTACH_SETTINGS_UPDATED", "הגדרות צרוף קבצים התעדכנו");
define("he_ATTACH", "קבצים מצורפים");
define("he_ATTACHMENT_DISABLED", "צרוף קבצים מנוטרל");
define("he_ATTEMPTS", "ניסיונות");
define("he_AUTHENTICATION_REQUIRED", "נדרשת היזדהות");
define("he_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", " 'available'שייוך אוטומטי של תגובה לפניה האחרונה שנענתה. (<i> 3 months limit</i>)");
define("he_AUTOLOCK_TIME", "זמן נעילה אוטומטית");
define("he_AUTORESPONDERS_GLOBAL_SETTING", "הגדרות מענה אוטומטי &nbsp;(Global Setting)");
define("he_AUTORESPONDERS", "מענה אוטומטי");
define("he_AUTORESPONSE_FROM_EMAIL", "מענה אוטומטי מ Email");
define("he_AUTORESPONSE_INCLUDES_THE_TICKET_ID", " מענה אוטומטי הכולל מספר הפניה הכרחי לבדיקת סטטוס הפניה");
define("he_BAD_PREFIX_UNDERSCORE", "קידומת שגויה (_) הכרחי לדוגמא 'ost_'");
define("he_BAN_EMAIL_LOWER", "banemail");
define("he_BYTES_ALLOWED", "bytes מורשי");
define("he_CAN_BE_APPENDED_TO_RESPONSES", "can be appended to responses.&nbsp;(available as a choice for public departments)  ");
define("he_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", ".לא ניתן למחק מחלקה המשוייכת לנושאי עזרה, יש למחוק את הנושאים קודם");
define("he_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "לא ניתן למחוק מחלקה עם חברי צוות משוייכים");
define("he_CANCEL", "בטל");
define("he_CATEGORY", "קטגוריה");
define("he_CELL_PHONE", "סלולארי");
define("he_CHANGE_PASS", "שינויי סיסמה");
define("he_CHANGE_PRIORITY", "שנה_עדיפות");
define("he_CHECK_STATUS_OPENED_TICKETS", "בדקו את המצב של הפניה הקודמת שנפתחה. אנו מספקים ארכיונים וההיסטוריה של כל בקשות התמיכה מלאות עם תגובות שלך");
define("he_CHECK_STATUS", "בדוק סטטוס");
define("he_CLICKABLE_URL", "הניתנים להקלקה URLs");
define("he_CLIENT_SESSION_TIMEOUT_IN_MINS", "זמן מתנה המקסימאלי של הלקוח בתוך דקות. הזן 0 כדי לבטל פסק זמן");
define("he_CLIENT_SESSION_TIMEOUT", "פסק זמן פעילות לקוח");
define("he_CLOSE_LOWER", "close");
define("he_CLOSE_REOPEN_TICKETS", "סגירה/להגיב לפניה");
define("he_CLOSE", "סגור");
define("he_CLOSED", "סגור");
define("he_COMMERCIAL_SUPPORT_AVAILABLE", "תמיכה מסחרית זמינה");
define("he_CONF_FILE_ALREADY_MOD", "קובץ תצורה כבר שונה!");
define("he_CONF_FILE_NOT_WRITABLE", "קובץ תצורה אינו ניתן לעריכה");
define("he_CONFIRM_NEW_PASS", "אשר את הסיסמה החדשה");
define("he_CONFIRM", "אשר");
define("he_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", 'מתנגש עם דוא"ל מערכת לעיל');
define("he_CONTACT_ADMIN", "פנה למנהל אם אתה מאמין שזה בטעות");
define("he_CREATE_DATE", "תאריך יצירה");
define("he_CURR_PASS_REQ", "סיסמה נוכחית נחוצה");
define("he_CURR_TIME", "זמן נוכחי");
define("he_DATE_AND_TIME_FORMAT", "תאריך &amp; פורמט זמן");
define("he_DATE_AND_TIME", "תאריך &amp; זמן");
define("he_DATE_FORMAT", "פורמט תאריך");
define("he_DAY_DATE_TIME_FORMAT", "יום, תאריך &amp; פורמט זמן");
define("he_DAYLIGHT_SAVING", "שעון קיץ");
define("he_DAYLIGHT_SAVINGS", "שעון קיץ");
define("he_DB_NOT_EXISTS", "מסד-נתונים לא קיים");
define("he_DEFAULT_DEPARTMENT", "מחלקה ברירת מחדל");
define("he_DEFAULT_EMAIL_TEMPLATE", "תבנית ברירת מחדל לדואל");
define("he_DEFAULT_EMAIL", "דואל ברירת מחדל");
define("he_DEFAULT_PAGE_SIZE", " ברירת מחדל לגודל דף ");
define("he_DEFAULT_PRIORITY", "ברירת מחדל לעדיפות");
define("he_DEFAULT_TIMEZONE", "ברירת מחדל לאיזור זמן");
define("he_DELETE_DEPS", "מחקת מחלקה");
define("he_DELETE_LOWER", "מחק");
define("he_DELETE_TICKETS", "מחקית פניה");
define("he_DELETE", "מחק");
define("he_DEPARTMENT_MANAGED", "מנהל מחלקה (spammy)");
define("he_DEPARTMENT_MANAGER", "מנהל מחלקה");
define("he_DEPARTMENT_MEMBERS", "חברי מחלקה (spammy)");
define("he_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", 'מחלקה שתחתיו "התשובה');
define("he_DEPARTMENTS", "מחלקה");
define("he_DEPENDS_ON_THE_TAG_BELOW", "תלוי בתגית שמתחת ");
define("he_DEPT_DEPENDS_ON_EMAIL", "מחלקה תלוייה בדואל &amp; נושאי עזרה עבור פניות נכנסות.");
define("he_DEPT_EMAIL_ABOVE", "דואל מחלקה (above)");
define("he_DEPT_EMAIL", "דואל מחלקה");
define("he_DEPT_MANAGER", "מנהל מחלקה");
define("he_DEPT_NAME", "שם מחלקה");
define("he_DEPT_SIGNATURE", "חתימת מחלקה");
define("he_DEPT_TRANSFER", "העבר מחלקה");
define("he_DEPT_TYPE", "סוג מחלקה");
define("he_DEPT", "מחלקה");
define("he_DIR_MUST_BE_VALID_WRITABLE", "הספרייה חייבת להיות חוקית ניתנת לכתיבה");
define("he_DIRECTORY", "ספריה");
define("he_DISABLE", "נטרל");
define("he_DISABLED", "מנוטרל");
define("he_DO_REQUESTED_ACTION", "בצע פעולות נחוצות");
define("he_EDIT_PREMADE_REPLY", "ערוך תגובה מוכנה מראש");
define("he_EMAIL_ADD_SUCCESS", "דואל נוסף בהצלחה");
define("he_EMAIL_ADDED_TO_BANLIST", "דואר נוסף לרשימה האסורה");
define("he_EMAIL_ADDRESS", "כתובת דואל");
define("he_EMAIL_ALREADY_BANNED", "הדואל כבר ברשימה האסורה");
define("he_EMAIL_ALREADY_EXISTS", "דואל כבר קיים");
define("he_EMAIL_IN_BANLIST", "אימייל הוא ברשימה האסורה. יש להסיר כדי להשיב");
define("he_EMAIL_MISMATCH", "דואל לא זהה");
define("he_EMAIL_REMOVED", "דואל הוסר");
define("he_EMAIL_SETTINGS", "הגדרות דואל");
define("he_EMAIL_UNKNOWN", "דואל לא ידוע");
define("he_EMAIL_UPDATED_SUCCESS", "דואל עודכן בהצלה");
define("he_ENABLE_AUTOCRON", "אפשר Cron האוטומטי");
define("he_ENABLE_CRON_CALL", "אפשר קריאה cron על פעילותו של הצוות");
define("he_ENABLE_EMAIL_PIPING", 'אפשר צנרת דוא"ל');
define("he_ENABLE_POP3_EMAIL_FETCH", "אפשר להביא דוא'ל POP3");
define("he_ENABLE", "אפשר");
define("he_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "'טעויות מאופשרות' ישלחו לדואל של המנהל למעלה");
define("he_ENTER_MESSAGE", "הכנס הודעה");
define("he_ENTER_VALID_NUM", "הזן מספר תקף");
define("he_ERR_SQL_SYNTAX", "יש לך טעות בביטוי SQL ");
define("he_ERROR_OCCURED", "קרתה טעות/טעויות");
define("he_ERROR_OCCURRED", "קרתה טעות, נא ראה בהערות למטה");
define("he_EXCESSIVE_LOGIN_ATTEMPTS", "נסיונות התחברות שגויים מוגבל!");
define("he_FATAL_ERROR", "טעות קריתית");
define("he_FETCH_INTERVAL_REQUIRE", "Fetch מרווח אחזר נדרש");
define("he_FILE_TOO_BIG", "גובץ גדול מדי");
define("he_FILE_UPLOAD_DISABLED_PHP_INI", "הוראה של file_uploads 'מושבתת ב php.ini");
define("he_FIRST_NAME", "שם פרטי");
define("he_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "עבור POP3 ' אחזור' דואל, עליך להגדיר משימת cron עבודה או פשוט לאפשר אוטומטי cron");
define("he_FORGOT_LOGIN_INFO", "שכחת את פרטי הכניסה שלך? אנא <a href=\"open.php\">פתח פניה חדשה</a>.");
define("he_FROM_BANLIST", "מרשימת דואל אסורה");
define("he_FULL_NAME", "שם מלא");
define("he_GENERAL_INQUIRY", "פנייה כללית");
define("he_GENERAL_SETTINGS", "הגדרות כלליות");
define("he_GET_A_PEACE_OF_MIND", "קבל שקט נפשי");
define("he_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", " 'Global autoresponder' חייב לאיות מאופשר עבור המלחחקה גדי שההגדרות ישפיעו מענה אוטומטי ");
define("he_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "הגדרה שיכולה להיות פעילה ברמת דואל");
define("he_HELP_TOPIC", "נושא עזרה");
define("he_HELPDESK_NAME", "שם מוקד תמיכה / תאור");
define("he_HELPDESK_STATUS", "סטטוס מוקד תמיכה");
define("he_HELPDESK_URL", "מוקד תמיכה URL");
define("he_HELPS_WITH_SPAM", "מסייע בדואר זבל ובקרת 'הצפות מידע'. הזן 0 ללא הגבלה");
define("he_HOME", "ראשי");
define("he_HOST_MISSING", "חסר מארח");
define("he_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "מספר שעות לפני שהפניה המסומנת כאיחור בטיפול. הזן 0 כדי לבטל את התישנות");
define("he_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "אם מסומן , פניה תופעל מחדש בעת ביצוע פעילות");
define("he_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "אם ברצונך לשלוח הערות נוספות או מידע לגבי אותה פניה, אנא עקוב אחר ההוראות שבהודעת הדואל.");
define("he_IMAP_DOESNT_EXISTS", "IMAP לא קיים. PHP יש לבצע קומפילציה עם IMAP מופעל.");
define("he_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "על מנת לייעל את בקשות תמיכה ולשרת טוב יותר , אנו מנצלים מערכת כרטיס תמיכה על. כל בקשה לתמיכה מקבלת מספר הפניה ייחודי שבו ניתן להשתמש כדי לעקוב אחר ההתקדמות ותגובות באינטרנט. לעיונך אנו מספקים ארכיונים והיסטוריה של כל בקשות התמיכה שלך מלאים.");
define("he_INDICATE_SOURCE", "ציין מקור");
define("he_INSTALL_COMPLETE", "ברכות, התקנה בסיסית osTicket הושלמה!");
define("he_INTERNAL_ERROR_OCCURED", "שגיאה פנימית התרחשה");
define("he_INTERNAL_ERROR", "שגיאה פנימית. אנא וודא שההורדה שלך הכי מעודכנת");
define("he_INTERNAL_NOTE_POSTED", "הערה פנימית עודכנה/נרשמה");
define("he_INVALID_ATTACH", "צרוף קובץ שגויי");
define("he_INVALID_FILE_TYPE", "סוג קובץ שגויי");
define("he_INVALID_FILE", "קובץ שגויי");
define("he_INVALID_LOGIN", "פרטי כניסה שגויים");
define("he_INVALID_SOURCE", "מקור שגויי");
define("he_INVALID_SQL_SCHEMA", "סכימה לא חוקית של SQL. קבל עזרה ממפתחים");
define("he_INVALID_UPLOAD_DIR", "ספרית העלאה שגוייה");
define("he_INVALID", "שגיאת ");
define("he_KNOWLEDGE_BASE", "מרכז ידע");
define("he_LANG_PRIVATE", "פרטי");
define("he_LANG_PUBLIC", "ציבורי");
define("he_LAST_NAME", "שם משפחה");
define("he_LAST_RESPONDENT", "המשיב האחרון");
define("he_LAST_UPDATED", "העדכון האחרון");
define("he_LOCK", "נעילה");
define("he_LOCKED", "נעול");
define("he_MAIL_METH", "שיטות דואל");
define("he_MAIL_PARSE_ERRORS", "שגיאות ניתוח דואל");
define("he_MAKE_PRIVATE", "סמן כפרטי");
define("he_MAKE_PUBLIC", "סמן כציבורי");
define("he_MAKE_URL_CLICKABLE", "אפשר קישורים ניתנים להקלקה");
define("he_MANAGER", "מנהל");
define("he_MASS_MANAGE_TICKETS", "ניהול פניות מאסיבי.פניה למנהל לגישה מסוג זה");
define("he_MAX_ALLOWED", "מקסימום מאופשרים");
define("he_MAX_FILE_SIZED_REQ", "גודל קובץ מקסימאלי הכרחי");
define("he_MAX_LOGIN_ATTEMPTS", "מספר נסיונות כניסה שגויים הוגבל!. אנא נסה בעוד 5 דקות או  <a href=\"open.php\">פתח פניה חדשה</a>");
define("he_MAX_OPEN_TICKETS", "מקסימום <b>Open</b> פניות");
define("he_MAX_PAGE_SIZE", "גודל דף מאקסימאלי");
define("he_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "הודעה תצורף לאישור פניה קיימת");
define("he_MESSAGE_POSTED_SUCCESS", "הודעה פורסמה בהצלחה");
define("he_MESSAGE_REQUIRED", "תוכן הודעה הכרחי");
define("he_MESSAGE", "הודעה");
define("he_MIN_TO_LOCK_A_TICKET", "דקות לנעילת הפניה לפעילות. הזן 0 כדי לבטל את הנעילה");
define("he_MISSING_MESSAGE", "חסר של ההודעה ID");
define("he_MISSING_OR_INVALID_GROUP", "חסר או לא קיימת קבוצה כזו");
define("he_MISSING_SQL_SCHEMA", "סכימת SQL חסרה");
define("he_MOBILE", "נייד");
define("he_MUST_BE_SIX_CHARS", "חייב להכיל לפחות 6 תווים");
define("he_MUST_SELECT_PRIORITY", "חייב לבחור עדיפות");
define("he_MY_ACCOUNT", "החשבון שלי");
define("he_MY_PREFERENCES", "ההעדפות שלי");
define("he_MY_PROFILE_INFO", "מידע הפרופיל שלי");
define("he_MY_PROFILE", "הפרופיל שלי");
define("he_NAME", "שם");
define("he_NEED_HELP_QUESTION", "זקוק לעזרה");
define("he_NEW_DEPT", "מחלקה חדשה");
define("he_NEW_MESSAGE_ALERT", "התראת הודעה חדשה");
define("he_NEW_MESSAGE", "הודעה חדשה");
define("he_NEW_PASS_NOT_MATCH", "הודעה חדשה לא תואמת");
define("he_NEW_PASS_REQ", "סיסמה חדשה נחוצה");
define("he_NEW_PASS_SAME_OLD", "הסיסמה החדשה זהה לישנה");
define("he_NEW_PREMADE_REPLY", "הודעה מוכנה חדשה");
define("he_NEW_TICKET_ALERT", "התראת פניה חדשה");
define("he_NEW_TICKET", "פניה חדשה");
define("he_NO_ACCESS_TO_TICKET", "אין לך גישה לפניה זו");
define("he_NO_PERMISSION_TO_REASSIGN", "אין לך הרשאות להקצרה מחדש  של הפניה");
define("he_NO_PERMISSION_TO", "אין לך הרשאות ל");
define("he_NO_REPLY_EMAIL_ADDRESS", "דואל עבור הודעות NO-REPLY");
define("he_NO_REPLY_EMAIL", "No Reply דואל");
define("he_NO_STAFF_FOUND", "לא נמצא איש סגל");
define("he_NO_SUCH_FILE", "אין קובץ כזה");
define("he_NO_TICKETS_FOUND", "לא נמצאה פניה");
define("he_NO_TICKETS_SELECTED", "לא נבחרה פניה. חייב לבחור לפחות פניה אחת");
define("he_NO_USER_ADD_USER", "אין משתמש (Add Users)");
define("he_NONE", "ללא");
define("he_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "אתה לא מורשה לעדכן עדיפות לפניה");
define("he_NOT_ALLOWED_TO_TRANSFER_TICKETS", "אתה לא מורשה לעביר פניה.");
define("he_NOTE_REQ", "הערה להודעה נחוצה");
define("he_NOTE_REQUIRED", "הערה/הודעה נחוצה");
define("he_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", " הודעות שנשלחו למשתמש עם דואל NO-REPLY  יוגדרו ככתובת לטופס בהתאמה'Alert Email'והתראות לצוות עם ");
define("he_OBSERVE", "צפה/פקח");
define("he_OF", "di");
define("he_OFFICE_PHONE", "טלפון במשרד");
define("he_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "מצב לא מקוון ללקוחת מנוטרל ו <b>only</b> allow <b>super admin</b> כדי להתחבר לממשק ניהול");
define("he_OFFLINE", "Offline");
define("he_ONLINE", "Online");
//define("he_OPEN_LOWER", "פתוח");
define("he_OPEN_NEW_TICKET", "פתח פניה חדשה");
define("he_OPEN_TICKET", "פניה פתוחה/חדשה");
define("he_OPEN", "פתח");
define("he_OSTICKET_BASIC_INSTALL", "osTicket Basic Installation");
define("he_OSTICKET_INSTALLER", "osTicket Installer");
define("he_OSTICKET_REQUIRES_MYSQL", "osTicket requires MySQL 4.1.1 or better! Please upgrade");
define("he_OUTGOING_EMAIL", "דואל יוצא");
define("he_OVERDUE_LOWER", "באיחור");
define("he_OVERDUE_TICKET_ALERT", "התראת פניות באיחור");
define("he_OVERLIMIT_NOTICE", "הודעה על חריגת מגבלה");
//define("he_PAGE", "עמוד");
define("he_PASS_CHANGE_SUCCESS", "סיסמה השתנתה בהצלחה");
define("he_PASS_TO_NOT_MATCH", "סיסמאות לא תואמות");
define("he_PASSWORD_REQUIRED", "סיסמה נחוצה");
define("he_PER_EMAIL", "עבור הודעת דואל אחת");
define("he_PERM_DENIED", "Perm. נדחה.");
define("he_PHONE_NUM_REQ", "מספר טלפון הכרחי");
define("he_PHONE", "טלפון");
define("he_PHP_DATE_MANUAL", "אנא התייחס ל <a href=\"http://php.net/date\" target=\"_blank\">PHP Manual</a> לערכים נתמכים");
define("he_PHP_OUT_OF_DATE", " התקנת PHP לא מעודכנת בעליל");
define("he_PHRASE_TOO_SHORT", "ביטוי קצר מדי!");
define("he_PHRASE_TWO_WORDS", "ביטוי חייב להכיל לפחות 2 מילים");
define("he_PLEASE_ENTER_VALID_EMAIL", "הזן דואל תקין.");
define("he_PLEASE_FILL_TO_OPEN_A_TICKET", "אנא מלא את הטופס הבא כדי לפתוח פניה חדשה");
define("he_POSSIBLE_ERROR_DETECTED", "שגיאות אפשריות זוהו, אנא בדוק את האזהרות להלן");
define("he_POSSIBLY_ACCESS_DENIED", "אם הגישה נדחה, אם אתה מאמין שזה בטעות, נא לקבל תמיכה טכנית.");
define("he_POSSIBLY_INVALID_TICKET", "יתכן ומספר הפניה שגוי ID");
define("he_POST_REPLY", "תגובה לפרסום");
define("he_POSTNOTE", "הערה פתרסום");
define("he_PREF_ERROR", "שגיאה בעדכון הנתונים.");
define("he_PREF_UPDATED", "נתונים עודכנו בהצלחה");
define("he_PREFERENCES", "הגדרות");
define("he_PREFERRED_TIMEZONE", "איזור זמן מועדף");
define("he_PREMADE_REPLIES", "תשובות מוכנות מראש");
define("he_PREMADE_REPLY", "תשובות  מוכנות מראש");
define("he_PRIMARY_OUTGOING_MAIL", "דואל ראשי להודעות יוצאות");
define("he_PRIORITY_CHANGED_SUCCESS", "עדיפות שונתה בהצלחה");
define("he_PRIORITY", "עדיפות");
define("he_PRIVATE_HIDDEN", "פרטי (Hidden)");
define("he_PROBLEM_CHANGING_PRIORITY", "בעיה בשינוי העדיפות.");
define("he_PROBLEM_CLOSING_TICKET", "בעיה בסגירת הפניה.");
define("he_PROBLEM_RELEASING_TICKET", "ביעה בשחרור הפניה");
define("he_PROBLEM_REOPENING_TICKET", "בעיה במענה לפניה");
define("he_PROBLEMS_ADMIN_PAGE", "בעיה בהעלאת עמוד הניהול.");
define("he_PROBLEMS_DELETING_THE_TICKET", "בעיה במחיקת פניה");
define("he_PROBLEMS_DISPLAYING_DIR", "בעיה בהצגת ספריה");
define("he_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "בעיה בסימון פניה כפניה באיחור");
define("he_PROCESS", "תהליך");
define("he_PROF_INST_AVAILABLE", "התקנה מקצועית זמינה");
define("he_PROFILE_UPDATE_SUCCESS", "פרופיל עודכן בהצלחה");
define("he_PUBLIC", "ציבורי");
define("he_QUERY", "Queryשאלה ");
define("he_RANDOM", "ראנדומלי");
define("he_RECOMMENDED", "מומלץ");
define("he_REJECTED", "נדחה");
define("he_RELEASE_LOWER", "שחרר");
define("he_REMOVING_QUOTED_REPLY", "הסרת תשובה מצוטטת");
define("he_REOPEN_LOWER", "פתח מחדש");
define("he_REOPEN", "פתח מחדש");
define("he_REOPENED_TICKETS", "פניות פתוחות מחדש");
define("he_REPLY_REQUIRED", "תגובה הכרחית");
define("he_REPLY_SEPARATOR_TAG", "תגובה עם תג מפריד");
define("he_REPLY_TITLE", "כותרת התגובה");
define("he_REPLY", "תגובה");
define("he_REQUIRED_WHEN_DEPT_IS_PUBLIC", "הכרחי כאשר מחלקה ציבורית");
define("he_REQUIRED", "required");
define("he_RESET_CHANGES", "אפס שינויים");
define("he_RESET", "איפוס");
define("he_RESPONSE_MESSAGE_REQUIRED", "תגובה נדרשת להודעה");
define("he_RESPONSE_POSTED_SUCCESS", "תגובה פורסמה בהצלחה");
define("he_SALVE_EMAIL_HEADERS", "שמור ראשי הודעת דואל");
define("he_SAVE_CHANGES", "שמור שינויים");
define("he_SAVE_RAW_HEADERS", "שמור כותרות גולמיות");
define("he_SAVE", "שמור");
define("he_SEARCH_FOR", "חיפוש עבור");
define("he_SEARCH_TERM_MORE_THAN_3_CHARS", "מינימום 3 תוים לביצעו חיפוש");
define("he_SEARCH", "חיפוש");
define("he_SECURITY_VIOLATION", "הפרת אבטחה. הפרות חוזרות ונשנות יביאו לכך שהחשבון שלך ינעל.");
define("he_SELECT_ASSIGNEE", "Sבחר מקבל ההעברה");
define("he_SELECT_DEFAULT_DEPT", "בחר מחלקה לברירת מחדל");
define("he_SELECT_DEPARTMENT", "בחר מחלקה");
define("he_SELECT_HELP_TOPIC", "בחר נושא עזרה");
define("he_SELECT_MANAGER_OPT", "בחר מנהל (optional)");
define("he_SELECT_ONE", "בחר אחד");
define("he_SELECT_RECIPIENTS", "בחר נמען");
define("he_SELECT", "בחר");
define("he_SELECTED_DEPT_DELETED", "מחלקה שנבחרה נמחקה");
define("he_SELECTED_EMAILS_DELETED", "כתובות דואל שנבחרו נמחקו");
define("he_SELECTED_EMAILS_REMOVED", "כתובתות דואל הוסרו מרשימה אסורה");
define("he_SELECTED_EMAILS_USED_BY_A_DEPT", "אחד או יותר מהמיילים הנבחרים נמצא בשימוש על ידי מחלקה הסר קישור קודם....");
define("he_SELECTED_ENTRIES", "רשומה נבחרה");
define("he_SELECTED_REPLIES_DELETED", "תשובות שנבחרו נמחקו");
define("he_SELECTED_REPLIES_DISABLED", "תשובות שנבחרו מנוטרלות");
define("he_SELECTED_REPLIES_ENABLED", "תשובות שנבחרו מאופשרות");
define("he_SELECTED_SERVICES_ENABLED", "שירותים שנבחרו מאופשרים");
define("he_SELECTED_TICKETS_CLOSED", "פניות שנבחרו נסגרו");
define("he_SELECTED_TICKETS_DELETED", "פניות שנבחרו נמחקו");
define("he_SELECTED_TICKETS_OVERDUE", "פניות שנבחרו סומנו  באיחור");
define("he_SELECTED_TICKETS_REOPENED", "פניות שנבחרו נפתחו מחדש");
define("he_SELECTED_TICKETS", "פניות שנבחרו");
define("he_SELECTED_TOPIC_DISABLED", "נושאים שנבחרו נוטרלו");
define("he_SELECTED_TOPICS_DELETED", "נושאים שנבחרו נמחקו");
define("he_SELECTED_USERS", "משתמשים שנבחרו(s)");
define("he_SEND_OVERLIMIT_NOTICE", "שלח התראה על חריגה מהלימיט");
define("he_SENT_ONLY_ONCE", "שלח <b>only once</b> בעת הפרת לימיט על ידי המשתמש. <b>Admin gets alerts on ALL denials by default</b>");
define("he_SEQUENTIAL", "עוקב,רצוף");
define("he_SERVER_TIME", "זמן בשרת");
define("he_SESSION_TIMED_OUT", "נותקת עקב חוסר פעילות");
define("he_SHOW_ASSIGNED_TICKETS", "הצג פניות פתוחות שהוקצו לתור הפתוח");
define("he_SHOWING", "הצגה");
define("he_SIGNATURE", "חתימה");
define("he_SORT_BY", "סינון לפי");
define("he_SQL_ERRORS", "SQL שגיאת");
define("he_STAFF_MAX_IDLE_TIME", "זמן המתנה של הצוות מקסימום המתנה בדקות. זן 0 כדי לבטל פסק זמן");
define("he_STAFF_MEMBERS", "חבר צוות");
define("he_STAFF_PANEL", "פאנל הצוות");
define("he_STAFF_SESSION_TIMEOUT", "ניתוק צוות מחוסר פעילות");
define("he_STATUS", "סטטוס");
define("he_STRIP_QUOTED_REPLY", "רצועת תגובה מצוטטת");
define("he_SUBJECT_MISSING", "חסר נושא");
define("he_SUBJECT", "נושא");
define("he_SUBMIT_A_NEW_REQUEST", 'שלח בקשה חדשה לתמיכה . אנא ספק פרטים רבים ככל האפשר, כדי שנוכל לסייע לך הכי טוב. כדי לעדכן את פניה הוגש הבעבר, אנא השתמש בטופס בצד ימין.כתובת דוא"ל חוקית נדרשת.');
define("he_SUMMARY_OF_THE_ISSUE_REQUIRED", "סקירת הנושא הכרחית");
define("he_SUPPORT_OFFLINE", "מערכת התמיכה במצה לא מקוון");
define("he_SUPPORT_TEAM", "צוות התמיכה ");
define("he_SUPPORT_TICKET_CREATED", "פניה לתמיכה נוצרה בהצלחה");
define("he_SUPPORT_TICKET_REQ_DENIED_FOR", "בקשה לפניה לתמיכה נדחתה עקב ");
define("he_SUPPORT_TICKET_SYSTEM", "מערכת תמיכה ושרות");
define("he_SYSTEM_ADMIN_EMAIL_ADDRESS", "דואל של מנהל המערכת");
define("he_SYSTEM_ERRORS", "שגיאות מערכת");
define("he_SYSTEM_OFFLINE", "המערכת במצב לא מקוון");
define("he_SYSTEM_PREFERENCES_AND_SETTINGS", "הגדרות ואפיוני מערכת");
define("he_TABLE_PREFIX", "קידומת לטבלאות");
define("he_TEMPLATE_ALERT_MSG_REQUIRED", "תבנית להודעות התראה הכרחית");
define("he_TEMPLATE_MSG_REQUIRED", "תבנית להודעות הכרחית");
define("he_TEMPLATES_UPDATED_SUCCESS", "תבניות עודכנו בהצלחה");
define("he_THANK_YOU_FOR_CHOOSING_OSTICKET", "תודה על בחירה במערכת osTicket.\nMake sure you join osTicket forums http://osticket.com/forums להישאר מעודכן  בחדשות האחרונות, התראות אבטחה ועדכונים. פורומי osTicket הוא גם מקום מצוין לקבל סיוע, ליווי ועזרה. בנוסף לפורום, osTicket wiki מספק אוסף שימושי של חומרי לימוד, תיעוד והערות מהקהילה. אם אתם מחפשים רמה גבוהה יותר של תמיכה, אנו מספקים שירותים מקצועיים ותמיכה מסחרית מותאמת אישית עם זמני תגובה ומבטיחים גישה לצוות הפיתוח של הליבה. אנחנו יכולים גם להתאים אישית את המערכת כדי לענות על הצרכימים הייחודיים שלך. ידע נוסף או כדי לדון צרכים שלך, אנא פנה אלינו היום. כל משוב יהיה מוערך! \ צוות nosTicket");
define("he_THANK_YOU_FOR_CONTACTING_US", "תודה על פנייתך.<br>בקשת תמיכה נוצרה ונציג יהיה לחזור אליך תוך זמן קצר במידת צורך.");
define("he_THANK_YOU_HELPDESK_OFFLINE", "תודה על רצונך לפנות אלינו.<br>מרכז התמיכה שלנו אינו מחובר ברגע זה, אנא בדוק שוב במועד מאוחר יותר.");
define("he_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "זוהי הגדרה הכללית ניתן להשבית ברמת מחלקה");
define("he_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "פניה זו כבר הוקצתה לחבר צוות");
define("he_TICKET_ALREADY_ASSIGNED" , "פניה זו כבר הופנתה.");
define("he_TICKET_ALREADY_IN_DEPT", "פניה זו כבר במחלקה.");
define("he_TICKET_ASSIGNED_TO_THE_STAFF", "פניה הועברה לחבר צוות");
define("he_TICKET_CREATED_BY_STAFF", "פניה נוצרה על ידי חבר צוות");
define("he_TICKET_CREATED_SUCCESS", "פניה נוצרה בהצלחה");
define("he_TICKET_DELETED_FOREVER", "פניה נמחקה לנצח!");
define("he_TICKET_DENIED_403", "Ticket denied Error #403");
define("he_TICKET_DENIED_NOTICE", "הודעת דחיה לפניה");
define("he_TICKET_FLAGGED_AS_OVERDUE", "פניה סומנה כנמצאת באיחור");
define("he_TICKET_GRACE_PERIOD", "זמן ה'חסד' לפניה");
define("he_TICKET_ID", "פניות IDs");
//define("he_TICKET_LOWER", "פניה");
define("he_TICKET_NOT_ASSIGNED", "פניה לא הופנתה!");
define("he_TICKET_OPTIONS_AND_SETTINGS", "הגדרות ואפשריות לפניה &amp; ");
define("he_TICKET_PRIORITY", "עדיפות פניה");
define("he_TICKET_RELEASED_FROM", "פניה שוחררה מ  (unassigned) ");
define("he_TICKET_STATUS_SET_TO", "סטטוס פניה עודכן ל");
define("he_TICKET_STATUS", "סטטוס פניה");
define("he_TICKET_TRANSFER", "פניה בועברה בהצלחה");
define("he_TICKET_WILL_BE_REOPENED", "הפניה תענה בעת פרסום ההודעה");
define("he_TICKETS_PER_PAGE", " מספר פניות/פריטים לעמוד");
//define("he_TICKETS", "פניות");
define("he_TIME_FORMAT", "פורמט זמן");
define("he_TITLE_ALREADY_EXISTS", "כותרת כבר קיימת");
define("he_TITLE_REQ", "כותרת הכרחית");
define("he_TITLE_REQUIRED", "כותרת הכרחית");
define("he_TITLE", "כותרת");
define("he_TO_BAN_EMAILS", "לכתובתות דואל אסורות");
define("he_TO_CLOSE", "לסגירה");
define("he_TO_DELETE_SELECTED_DEPTS", "למחיקת מחלקות מסומנות");
define("he_TO_DELETE_TICKETS", "למחיקת פניות");
define("he_TO_DELETE", "למחיקה");
define("he_TO_DISABLE", "לניטרול");
define("he_TO_ENABLE", "לאפשר");
define("he_TO_FLAG_TICKETS_OVERDUE", "לסמן פניות כאיחור בטיפול");
define("he_TO_LOCK", "לנעול");
define("he_TO_MAKE_SELECTED_DEPTS_PRIVATE", "לסמן מחלקות שנבחרו כפרטיות");
define("he_TO_MAKE_SELECTED_DEPTS_PUBLIC", "לסמן מחלקות שנבחרו כציבוריות");
define("he_TO_MARK_SELECTED_TICKETS_OVERDUE", "לסמן פניות נבחרות כמטופלות מדי או 'מציקות'");
define("he_TO_REM_EMAILS_FROM_BANLIST", "הסר דואל מרשימה אסורה.");
define("he_TO_REOPEN", "לפתוח מחדש");
define("he_TO_VIEW_THE_STATUS_OF_A_TICKET", "לצפיה בסטטוס הפניה יש לספק את פרטי ההתחברות למטה.<br/>אם זו פניה ראשונה אלינו או שאיבדת את פרטי הפניה, אנא <a href=\"open.php\">לחץ כאן</a> לפתוח פניה חדשה.");
define("he_TO", "עבור");
define("he_TOGGLE", "למתג");
define("he_TOPIC_TOO_SHORT", "נושא קצר מדי, יש להשתמש בערך בן 5 תווים לפחות");
define("he_TRANSFER", "העברה");
define("he_TRY_AGAIN", "נסה שוב");
define("he_TYPE", "סוג");
define("he_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "לא הצליח לשייך דואל לרשימה האסורה");
define("he_UNABLE_TO_ADD_EMAIL", "לא הצליחה הוספת  דואל.שגיאה פנימית");
define("he_UNABLE_TO_ADD_MAIL_TO_BANLIST", "לא הצליחה הוספת הדואל לרשימה האסורה, נסה שנית");
define("he_UNABLE_TO_ASSIGN_TICKET", "לא הצליחה הקצאת הפניה");
define("he_UNABLE_TO_COMPLETE_ACTION", "לא הצליחה ביצוע הפעולה");
define("he_UNABLE_TO_COMPLETE_PASS_CHANGE", "לא ניתן להשלים את שינוי סיסמא. שגיאה פנימית.");
define("he_UNABLE_TO_COMPLETE_THE_TRANSFER", "לא ניתן להשלים את ההעברה");
define("he_UNABLE_TO_CONNECT_MYSQL", "אין אפשרות להתחבר לשרת MySQL. פרטי התחברות אולי לא חוקיים. <br>");
define("he_UNABLE_TO_CREATE_DB", "לא ניתן ליצור מסד הנתונים עקב חוסר ההרשאה");
define("he_UNABLE_TO_CREATE_THE_REPLY", "לא ניתן ליצור את התשובה. שגיאה פנימית");
define("he_UNABLE_TO_CREATE_TICKET", "לא ניתן ליצור את הפניה. תקן את השגיאה  ונסה שוב");
define("he_UNABLE_TO_DELETE_SELECTED_DEPT", "לא מצליח למחוק מחלקות נבחרות.");
define("he_UNABLE_TO_DELETE_SELECTED_EMAILS", "לא מצליח למחוק את כתובת הדואל.");
define("he_UNABLE_TO_DISABLE_SELECTED_TOPICS", "לא ניתן להשבית נושאים נבחרים");
define("he_UNABLE_TO_FETCH_INFO_ON", "לא ניתן לקבל מידע על");
define("he_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "לא ניתן להסיר את המיילים נבחרים");
define("he_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "לא ניתן להפוך את המחלקה נבחרת פרטית. אולי כבר מסומן כפרטי!");
define("he_UNABLE_TO_OPEN_CONF_FILE", "לא ניתן לפתוח את קובץ CONFIG, אין הרשאות מתאימות");
define("he_UNABLE_TO_POST_RESPONSE", "לא ניתן לפרסם את התגובה.");
define("he_UNABLE_TO_POST_THE_MESSAGE", "לא ניתן לפרסם את ההודעה");
define("he_UNABLE_TO_POST_THE_NOTE", "לא ניתן לפרסם את ההערה.");
define("he_UNABLE_TO_REMOVE_EMAIL", "לא ניתן להסיר את הדואל");
define("he_UNABLE_TO_SELECT_DB", "לא ניתן לבחור את מסד הנתונים");
define("he_UNABLE_TO_UPDATE_EMAIL", "לא ניתן לעדכן את הדואר אלקטרוני. שגיאה פנימית");
define("he_UNBAN_EMAIL_LOWER", "כתובת דואר הוסרה מאסורה");
define("he_UNKNOWN_ACTION", "פעולה לא מוכרת");
define("he_UNKNOWN_BANLIST_COMMAND", "פקודת דואר אסור לא מוכרת");
define("he_UNKNOWN_COMMAND", "פקודה לא מוכרת");
define("he_UNKNOWN_DEPT_ACTION", "פעולת מחלקה לא מוכרת");
define("he_UNKNOWN", "לא מוכר");
define("he_UPDATE_DEPARTMENT", "עדכן מחלקה");
define("he_UPDATE_ERROR", "שגיאת עדכון");
define("he_UPDATED_SUCCESS", "עודכן בהצלחה");
define("he_UPLOAD_DIR_INVALID", "ספרית העלאה לא מוכרת.נא צור קשר עם המנהל.");
define("he_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "השתמש בעדיפות לדואל אם אפשרי (פניות בדואל)");
define("he_USERNAME_MISSING", "שם משתמש חסר");
define("he_USERNAME", "שם משתמש");
define("he_USERS", "משתמשים");
define("he_VALID_EMAIL", "דואל תקין");
define("he_VALID_PASS_REQ", "סיסמה תקפה נחוצה");
define("he_VIEW_STATUS", "צפה בסטטוס");
define("he_WELCOME_BACK", 'ברוכים השבים! אתה מופיע בתור "בחופשה" אנא, עדכן את  המנהל שלך יודע שאתה חוזר.');
define("he_WELCOME_TO_SUPPORT_CENTER", "ברוכים הבאים למרכז התמיכה והשרות.");
define("he_YOU_ARE_NOT_ALLOWED", "אתה לא מורשה");
define("he_YOU_HAVE_REACHED_MAX_TICKETS", "מיצית את כמות הפניות הפתוחות המרבית המותרת.");
define("he_YOU_LL_NEED_TICKET_NUMBER", "אתה צריך את מספר הפניה וכתובת הדואל שלך כדי לצפות בסטטוס והמהלך ההתקדמות הטיפול בפניה ");
define("he_YOU_MUST_CHANGE_PASS", "אתה צריך לשנות את הסיסמה שלך כדי להמשיך.");
define("he_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "אתה חייב להכניס את המארחים לרשימה לבנה");
define("he_YOU_MUST_SELECT_ACTION_TO_PERFORM", "עליך לבחור פעולה לביצוע");
define("he_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "עליך לבחור לפחות פריט אחד");
define("he_YOU_MUST_SELECT_ONE_EMAIL", 'עליך לבחור דוא"ל אחת לפחות');
define("he_YOU_MUST_SELECT", "אתה חייב לבחור");
define("he_YOU_NEED_TO_SET_UPLOADDIR", "עלייך להגדיר ספריה להעלאות.");
define("he_YOU_PIPE_WE_ACCEPT_POLICY", "את צינור קבלת התנאים");
define("he_ZERO_RESULTS", "השאילתה החזירה 0 תוצאות");

