<?php
define("nl_A_DEPT", "Afdeling.");
define("nl_A_PRIORITY", "Prioriteit");
define("nl_ACCESS_DENIED", "Toegang geweigerd");
define("nl_ACTION_DENIED_TICKET_LOCKED", "Toegang geweigerd. Dit ticket is door iemand anders in gebruik!");
define("nl_ACTION_DENIED", "Toegang geweigerd");
define("nl_ACTIVE", "Actief");
define("nl_ADD_NEW_PREMADE_REPLY", "Maak een nieuw ticket aan");
define("nl_ADD_NEW_USER", "Voeg een nieuwe gebruiker toe");
define("nl_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "De administrator krijgt standaard een e-mail. Selecteer onderaan extra ontvangers");
define("nl_ADMIN_EMAIL", "Administrator e-mail");
define("nl_ADMIN_PANEL", "Admin panel");
define("nl_ADVANCED", "Gevorderd");
define("nl_ALERT_FROM_EMAIL_ADDRESS", "Aanmeldingen van het volgende e-mail adres");
define("nl_ALERT_SUBJECT_MISSING", "Aanmeldingen onderwerp mist");
define("nl_ALERTS_NOTICES", "Aanmeldingen &amp; Notificaties");
define("nl_ALL_DEP", "Alle afdelingen");
define("nl_ALL_DEPTS", "Alle afdelingen");
define("nl_ALL", "Alle");
define("nl_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Laat klanten toe om online tickets te overschrijven");
define("nl_ALLOWED_FILE_EXT_REQ", "Toegestane vereiste bestand extenties");
define("nl_ALLOWED", "toegestaan");
define("nl_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "Uw ticket is doorgezet");
define("nl_ANOTHER_DEPT_USING_HOST_COMBINATION", "Een andere afdeling met behulp van host / user combinatie van.");
define("nl_ANSWER", "Antwoord");
define("nl_API_SETTINGS_UPDATED", "API instellingen zijn geupdate");
define("nl_ARE_YOU_SURE_YOU_WANT", "Weet u het zeker");
define("nl_ASSIGN", "toewijzen");
define("nl_ASSIGNED_STAFF", "Toegewezen personeel");
define("nl_ASSIGNED_TICKETS", "Toegewezen tickets");
define("nl_AT_LEAST_ONE_TOPIC", "Minimaal 1 topic");
define("nl_ATTACH_FILE", "Voeg een bestand toe");
define("nl_ATTACH_SETTINGS_UPDATED", "Bijlagen instellingen bijgewerkt");
define("nl_ATTACH", "Bijlage");
define("nl_ATTACHMENT_DISABLED", "Bijlage toevoegen uitgeschakeld");
define("nl_ATTEMPTS", "Pogingen");
define("nl_AUTHENTICATION_REQUIRED", "verificatie vereist");
define("nl_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Auto-assign reopened tickets to last respondent 'available'. (<i> 3 months limit</i>)");
define("nl_AUTOLOCK_TIME", "automatische afsluit tijd");
define("nl_AUTORESPONDERS_GLOBAL_SETTING", "Autoresponders &nbsp;(Global Setting)");
define("nl_AUTORESPONDERS", "Automatische reactie");
define("nl_AUTORESPONSE_FROM_EMAIL", "Automatische reactie van Email");
define("nl_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Autoresponse includes the ticket ID required to check status of the ticket");
define("nl_BAD_PREFIX_UNDERSCORE", "Bad prefix. Must have underscore (_) at the end. e.g 'ost_'");
define("nl_BAN_EMAIL_LOWER", "banemail");
define("nl_BYTES_ALLOWED", "bytes allowed");
define("nl_CAN_BE_APPENDED_TO_RESPONSES", "can be appended to responses.&nbsp;(available as a choice for public departments)  ");
define("nl_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "Can not delete Dept. associated with a help topics. Remove association first.");
define("nl_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "Can not delete Dept. with members. Move staff first.");
define("nl_CANCEL", "Annuleren");
define("nl_CATEGORY", "Categorie");
define("nl_CELL_PHONE", "Mobiele telefoon");
define("nl_CHANGE_PASS", "Verander uw paswoord");
define("nl_CHANGE_PRIORITY", "Verander de prioriteit");
define("nl_CHECK_STATUS_OPENED_TICKETS", "Bekijk de status van onlangs geopende tickets. We verzamelen al de ooit aangemelde tickets door u in onze database.");
define("nl_CHECK_STATUS", "Bekijk status");
define("nl_CLICKABLE_URL", "Klikbare verwijzingen");
define("nl_CLIENT_SESSION_TIMEOUT_IN_MINS", "Client's max Idle time in minutes. Enter 0 to disable timeout");
define("nl_CLIENT_SESSION_TIMEOUT", "Client Session Timeout");
define("nl_CLOSE_LOWER", "sluit");
define("nl_CLOSE_REOPEN_TICKETS", "close/reopen tickets");
define("nl_CLOSE", "Sluit");
define("nl_CLOSED", "Gesloten");
define("nl_COMMERCIAL_SUPPORT_AVAILABLE", "Commercial Support Available");
define("nl_CONF_FILE_ALREADY_MOD", "Configuration file already modified!");
define("nl_CONF_FILE_NOT_WRITABLE", "Configuration file is not writable");
define("nl_CONFIRM_NEW_PASS", "Bevestig nieuw wachtwoord");
define("nl_CONFIRM", "Bevestig");
define("nl_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Conflicts with system email above");
define("nl_CONTACT_ADMIN", "Contact admin if you believe this is in error");
define("nl_CREATE_DATE", "Aanmaak datum");
define("nl_CURR_PASS_REQ", "Huidige paswoord benodigd");
define("nl_CURR_TIME", "Huidige tijd");
define("nl_DATE_AND_TIME_FORMAT", "Date &amp; Time Format");
define("nl_DATE_AND_TIME", "Date &amp; Time");
define("nl_DATE_FORMAT", "Date Format");
define("nl_DAY_DATE_TIME_FORMAT", "Day, Date &amp; Time Format");
define("nl_DAYLIGHT_SAVING", "Daylight Saving");
define("nl_DAYLIGHT_SAVINGS", "Daylight Savings");
define("nl_DB_NOT_EXISTS", "Database doesn't exist");
define("nl_DEFAULT_DEPARTMENT", "Default Department");
define("nl_DEFAULT_EMAIL_TEMPLATE", "Default Email Template");
define("nl_DEFAULT_EMAIL", "Default Email");
define("nl_DEFAULT_PAGE_SIZE", "Default page size");
define("nl_DEFAULT_PRIORITY", "Default priority");
define("nl_DEFAULT_TIMEZONE", "Default Timezone");
define("nl_DELETE_DEPS", "Delete depts");
define("nl_DELETE_LOWER", "delete");
define("nl_DELETE_TICKETS", "verwijder tickets");
define("nl_DELETE", "Verwijder");
define("nl_DEPARTMENT_MANAGED", "Department Manager (spammy)");
define("nl_DEPARTMENT_MANAGER", "Department Manager");
define("nl_DEPARTMENT_MEMBERS", "Department Members (spammy)");
define("nl_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Department under which the 'answer' will be made available");
define("nl_DEPARTMENTS", "Departments");
define("nl_DEPENDS_ON_THE_TAG_BELOW", "depends on the tag below");
define("nl_DEPT_DEPENDS_ON_EMAIL", "Dept depends on email &amp; help topics settings for incoming tickets.");
define("nl_DEPT_EMAIL_ABOVE", "Dept Email (above)");
define("nl_DEPT_EMAIL", "Dept email");
define("nl_DEPT_MANAGER", "Dept Manager");
define("nl_DEPT_NAME", "Afdelingsnaam");
define("nl_DEPT_SIGNATURE", "Afdeling ondertekening");
define("nl_DEPT_TRANSFER", "Dept. Transfer");
define("nl_DEPT_TYPE", "Afdelingstype");
define("nl_DEPT", "Afdelingt");
define("nl_DIR_MUST_BE_VALID_WRITABLE", "Directory must be valid and writeable");
define("nl_DIRECTORY", "Directory");
define("nl_DISABLE", "Disable");
define("nl_DISABLED", "Disabled");
define("nl_DO_REQUESTED_ACTION", "do requested action");
define("nl_EDIT_PREMADE_REPLY", "Edit Premade Reply");
define("nl_EMAIL_ADD_SUCCESS", "Email added successfully");
define("nl_EMAIL_ADDED_TO_BANLIST", "Email added to banlist");
define("nl_EMAIL_ADDRESS", "Email adres");
define("nl_EMAIL_ALREADY_BANNED", "Email already banned");
define("nl_EMAIL_ALREADY_EXISTS", "Email already exists");
define("nl_EMAIL_IN_BANLIST", "Email is in banlist. Must be removed to reply");
define("nl_EMAIL_MISMATCH", "Email mismatch.");
define("nl_EMAIL_REMOVED", "Email removed");
define("nl_EMAIL_SETTINGS", "Email Settings");
define("nl_EMAIL_UNKNOWN", "Email unknown");
define("nl_EMAIL_UPDATED_SUCCESS", "Email updated successfully");
define("nl_ENABLE_AUTOCRON", "Enable Auto Cron");
define("nl_ENABLE_CRON_CALL", "Enable cron call on staff's activity");
define("nl_ENABLE_EMAIL_PIPING", "Enable email piping");
define("nl_ENABLE_POP3_EMAIL_FETCH", "Enable POP3 email fetch");
define("nl_ENABLE", "Enable");
define("nl_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Enabled errors are sent to admin email set above");
define("nl_ENTER_MESSAGE", "Enter Message");
define("nl_ENTER_VALID_NUM", "Enter a valid number");
define("nl_ERR_SQL_SYNTAX", "You have an error in your SQL syntax ");
define("nl_ERROR_OCCURED", "Error(s) occured.");
define("nl_ERROR_OCCURRED", "Error occured. See error messages below.");
define("nl_EXCESSIVE_LOGIN_ATTEMPTS", "Excessive Login attempts");
define("nl_FATAL_ERROR", "Fatal Error");
define("nl_FETCH_INTERVAL_REQUIRE", "Fetch interval required");
define("nl_FILE_TOO_BIG", "File is too big");
define("nl_FILE_UPLOAD_DISABLED_PHP_INI", "The 'file_uploads' directive is disabled in php.ini");
define("nl_FIRST_NAME", "First name");
define("nl_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "For POP3 mail fetch to work you must set a cron job or simply enable auto-cron");
define("nl_FORGOT_LOGIN_INFO", "Forgot your login info? Please <a href=\"open.php\">open a new ticket</a>.");
define("nl_FROM_BANLIST", "from banlist");
define("nl_FULL_NAME", "Volledige naam");
define("nl_GENERAL_INQUIRY", "General Inquiry");
define("nl_GENERAL_SETTINGS", "General Settings");
define("nl_GET_A_PEACE_OF_MIND", "Get a peace of mind");
define("nl_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "Global autoresponder in preference section must be enabled for Dept 'Enable' setting to take effect.");
define("nl_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "Global setting which can be disabled at email level");
define("nl_HELP_TOPIC", "Ticket onderwerp");
define("nl_HELPDESK_NAME", "Helpdesk Name/Title");
define("nl_HELPDESK_STATUS", "Helpdesk Status");
define("nl_HELPDESK_URL", "Helpdesk URL");
define("nl_HELPS_WITH_SPAM", "Helps with spam and flood control. Enter 0 for unlimited");
define("nl_HOME", "Home");
define("nl_HOST_MISSING", "Host missing");
define("nl_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Hours before ticket is marked overdue. Enter 0 to disable aging");
define("nl_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "If enabled ticket lock get auto-renewed on form activity.");
define("nl_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "If you wish to send additional comments or information regarding same issue, please follow the instructions on the email.");
define("nl_IMAP_DOESNT_EXISTS", "IMAP doesn't exist. PHP must be compiled with IMAP enabled.");
define("nl_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "In order to streamline support requests and better serve you, we utilize a support ticket system. Every support request is assigned a unique ticket number which you can use to track the progress and responses online. For your reference we provide complete archives and history of all your support requests.");
define("nl_INDICATE_SOURCE", "Indicate source");
define("nl_INSTALL_COMPLETE", "Congratulations osTicket basic installation completed!");
define("nl_INTERNAL_ERROR_OCCURED", "Internal error occured");
define("nl_INTERNAL_ERROR", "Internal error. Please make sure your download is the latest");
define("nl_INTERNAL_NOTE_POSTED", "Internal note posted");
define("nl_INVALID_ATTACH", "Invalid Attachment");
define("nl_INVALID_FILE_TYPE", "Invalid file type");
define("nl_INVALID_FILE", "Invalid file");
define("nl_INVALID_LOGIN", "Invalid login");
define("nl_INVALID_SOURCE", "Invalid source");
define("nl_INVALID_SQL_SCHEMA", "Invalid SQL schema. Get help from Developers");
define("nl_INVALID_UPLOAD_DIR", "Invalid upload dir");
define("nl_INVALID", "Invalid");
define("nl_KNOWLEDGE_BASE", "Knowledge base");
define("nl_LANG_PRIVATE", "Private");
define("nl_LANG_PUBLIC", "Public");
define("nl_LAST_NAME", "Last name");
define("nl_LAST_RESPONDENT", "Last Respondent");
define("nl_LAST_UPDATED", "Last updated");
define("nl_LOCK", "Lock");
define("nl_LOCKED", "Locked");
define("nl_MAIL_METH", "Mail Methods");
define("nl_MAIL_PARSE_ERRORS", "Mail Parse Errors");
define("nl_MAKE_PRIVATE", "Make private");
define("nl_MAKE_PUBLIC", "Make public");
define("nl_MAKE_URL_CLICKABLE", "Make URLs clickable");
define("nl_MANAGER", "Manager");
define("nl_MASS_MANAGE_TICKETS", "mass manage tickets. Contact admin for such access");
define("nl_MAX_ALLOWED", "Max Allowed");
define("nl_MAX_FILE_SIZED_REQ", "Maximum file size required");
define("nl_MAX_LOGIN_ATTEMPTS", "You've reached maximum failed login attempts allowed. Try again after 5 minutes or <a href=\"open.php\">open a new ticket</a>");
define("nl_MAX_OPEN_TICKETS", "Maximum <b>Open</b> Tickets");
define("nl_MAX_PAGE_SIZE", "Maximum page size");
define("nl_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Message appended to an existing ticket confirmation");
define("nl_MESSAGE_POSTED_SUCCESS", "Bericht succesvol aangemaakt");
define("nl_MESSAGE_REQUIRED", "Bericht verplicht");
define("nl_MESSAGE", "Bericht");
define("nl_MIN_TO_LOCK_A_TICKET", "Minutes to lock a ticket on activity. Enter 0 to disable locking");
define("nl_MISSING_MESSAGE", "Missing message ID");
define("nl_MISSING_OR_INVALID_GROUP", "Missing or invalid group");
define("nl_MISSING_SQL_SCHEMA", "Missing SQL schema");
define("nl_MOBILE", "Mobile");
define("nl_MUST_BE_SIX_CHARS", "Must be at least 6 characters");
define("nl_MUST_SELECT_PRIORITY", "You must select priority");
define("nl_MY_ACCOUNT", "My Account");
define("nl_MY_PREFERENCES", "My Preferences");
define("nl_MY_PROFILE_INFO", "My Profile Info");
define("nl_MY_PROFILE", "My Profile");
define("nl_NAME", "Name");
define("nl_NEED_HELP_QUESTION", "Need help?");
define("nl_NEW_DEPT", "New Department");
define("nl_NEW_MESSAGE_ALERT", "Nieuw bericht melding");
define("nl_NEW_MESSAGE", "Nieuw bericht");
define("nl_NEW_PASS_NOT_MATCH", "New password(s) don't match");
define("nl_NEW_PASS_REQ", "New password required");
define("nl_NEW_PASS_SAME_OLD", "New password is same as old password");
define("nl_NEW_PREMADE_REPLY", "New Premade Reply");
define("nl_NEW_TICKET_ALERT", "Nieuw bericht melding");
define("nl_NEW_TICKET", "Nieuw ticket");
define("nl_NO_ACCESS_TO_TICKET", "You do not have access to the ticket");
define("nl_NO_PERMISSION_TO_REASSIGN", "You do not have permission to re-assign assigned tickets");
define("nl_NO_PERMISSION_TO", "You do not have permission to");
define("nl_NO_REPLY_EMAIL_ADDRESS", "No Reply Email Adres");
define("nl_NO_REPLY_EMAIL", "No Reply email");
define("nl_NO_STAFF_FOUND", "No staff found");
define("nl_NO_SUCH_FILE", "No such file");
define("nl_NO_TICKETS_FOUND", "NO tickets found.");
define("nl_NO_TICKETS_SELECTED", "No tickets selected. You must select at least one ticket.");
define("nl_NO_USER_ADD_USER", "No Users (Add Users)");
define("nl_NONE", "None");
define("nl_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "You are not allowed to change ticket's priority");
define("nl_NOT_ALLOWED_TO_TRANSFER_TICKETS", "You are not allowed to transfer tickets.");
define("nl_NOTE_REQ", "Note message required");
define("nl_NOTE_REQUIRED", "Note/Message required");
define("nl_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Notices sent to user use 'No Reply Email' whereas alerts to staff use 'Alert Email' set above as FROM address respectively.");
define("nl_OBSERVE", "Observe");
define("nl_OF", "di");
define("nl_OFFICE_PHONE", "Kantoor telefoon");
define("nl_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "Offline mode will disable client interface and <b>only</b> allow <b>super admin</b> to login to Staff Control Panel");
define("nl_OFFLINE", "Offline");
define("nl_ONLINE", "Online");
//define("nl_OPEN_LOWER", "open");
define("nl_OPEN_NEW_TICKET", "Open een nieuw ticket");
define("nl_OPEN_TICKET", "Open Ticket");
define("nl_OPEN", "Open");
define("nl_OSTICKET_BASIC_INSTALL", "osTicket Basic Installation");
define("nl_OSTICKET_INSTALLER", "osTicket Installer");
define("nl_OSTICKET_REQUIRES_MYSQL", "osTicket requires MySQL 4.1.1 or better! Please upgrade");
define("nl_OUTGOING_EMAIL", "Outgoing Email");
define("nl_OVERDUE_LOWER", "overdue");
define("nl_OVERDUE_TICKET_ALERT", "Overdue Ticket Alert");
define("nl_OVERLIMIT_NOTICE", "Overlimit Notice");
//define("nl_PAGE", "page");
define("nl_PASS_CHANGE_SUCCESS", "Password Changed Successfully");
define("nl_PASS_TO_NOT_MATCH", "passwords to not match!");
define("nl_PASSWORD_REQUIRED", "Password required");
define("nl_PER_EMAIL", "per email");
define("nl_PERM_DENIED", "Perm. Denied.");
define("nl_PHONE_NUM_REQ", "Telefoon # verplicht");
define("nl_PHONE", "Telefoon");
define("nl_PHP_DATE_MANUAL", "Please refer to <a href=\"http://php.net/date\" target=\"_blank\">PHP Manual</a> for supported parameters.");
define("nl_PHP_OUT_OF_DATE", "PHP installation seriously out of date");
define("nl_PHRASE_TOO_SHORT", "phrase is too short!");
define("nl_PHRASE_TWO_WORDS", "Phrase of 2+ words");
define("nl_PLEASE_ENTER_VALID_EMAIL", "Please enter a valid email.");
define("nl_PLEASE_FILL_TO_OPEN_A_TICKET", "Vul onderstaand formulier in om een nieuw support ticket te openen.");
define("nl_POSSIBLE_ERROR_DETECTED", "Possible errors detected, please check the warnings below");
define("nl_POSSIBLY_ACCESS_DENIED", "Possibly access denied, if you believe this is in error please get technical support.");
define("nl_POSSIBLY_INVALID_TICKET", "Possibly invalid ticket ID");
define("nl_POST_REPLY", "Post Reply");
define("nl_POSTNOTE", "postnote");
define("nl_PREF_ERROR", "Preference update error.");
define("nl_PREF_UPDATED", "Preferences Updated Successfully");
define("nl_PREFERENCES", "Preferences");
define("nl_PREFERRED_TIMEZONE", "Preferred Timezone");
define("nl_PREMADE_REPLIES", "Premade Replies");
define("nl_PREMADE_REPLY", "Premade Reply");
define("nl_PRIMARY_OUTGOING_MAIL", "Primary Outgoing Email");
define("nl_PRIORITY_CHANGED_SUCCESS", "Priority Changed Successfully");
define("nl_PRIORITY", "Priority");
define("nl_PRIVATE_HIDDEN", "Private (Hidden)");
define("nl_PROBLEM_CHANGING_PRIORITY", "Problems changing priority.");
define("nl_PROBLEM_CLOSING_TICKET", "Problems closing the ticket.");
define("nl_PROBLEM_RELEASING_TICKET", "Problems releasing the ticket.");
define("nl_PROBLEM_REOPENING_TICKET", "Problems reopening the ticket.");
define("nl_PROBLEMS_ADMIN_PAGE", "Problems loading requested admin page.");
define("nl_PROBLEMS_DELETING_THE_TICKET", "Problems deleting the ticket");
define("nl_PROBLEMS_DISPLAYING_DIR", "Problems displaying directory");
define("nl_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Problems marking the the ticket overdue");
define("nl_PROCESS", "process");
define("nl_PROF_INST_AVAILABLE", "Professional Installation Available");
define("nl_PROFILE_UPDATE_SUCCESS", "Profile Updated Successfully");
define("nl_PUBLIC", "Public");
define("nl_QUERY", "Query");
define("nl_RANDOM", "Random");
define("nl_RECOMMENDED", "recommended");
define("nl_REJECTED", "rejected");
define("nl_RELEASE_LOWER", "release");
define("nl_REMOVING_QUOTED_REPLY", "Removing quoted reply");
define("nl_REOPEN_LOWER", "reopen");
define("nl_REOPEN", "Reopen");
define("nl_REOPENED_TICKETS", "Reopened tickets");
define("nl_REPLY_REQUIRED", "Reply required");
define("nl_REPLY_SEPARATOR_TAG", "Reply Separator Tag");
define("nl_REPLY_TITLE", "Reply Title");
define("nl_REPLY", "reply");
define("nl_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Required when Dept is public");
define("nl_REQUIRED", "required");
define("nl_RESET_CHANGES", "Reset Changes");
define("nl_RESET", "Reset");
define("nl_RESPONSE_MESSAGE_REQUIRED", "Response message required");
define("nl_RESPONSE_POSTED_SUCCESS", "Response Posted Successfully");
define("nl_SALVE_EMAIL_HEADERS", "Save Email Headers");
define("nl_SAVE_CHANGES", "Save Changes");
define("nl_SAVE_RAW_HEADERS", "Save raw headers");
define("nl_SAVE", "Save");
define("nl_SEARCH_FOR", "Search for");
define("nl_SEARCH_TERM_MORE_THAN_3_CHARS", "Search term must be more than 3 chars");
define("nl_SEARCH", "Search");
define("nl_SECURITY_VIOLATION", "Security violation. Repeated violations will result in your account being locked.");
define("nl_SELECT_ASSIGNEE", "Select assignee");
define("nl_SELECT_DEFAULT_DEPT", "Select Default Dept");
define("nl_SELECT_DEPARTMENT", "Select Department");
define("nl_SELECT_HELP_TOPIC", "Selecteer ticket onderwerp");
define("nl_SELECT_MANAGER_OPT", "Select Manager (optional)");
define("nl_SELECT_ONE", "Kies een");
define("nl_SELECT_RECIPIENTS", "Select recipients");
define("nl_SELECT", "Select");
define("nl_SELECTED_DEPT_DELETED", "selected departments deleted");
define("nl_SELECTED_EMAILS_DELETED", "selected email(s) deleted");
define("nl_SELECTED_EMAILS_REMOVED", "selected emails removed from banlist");
define("nl_SELECTED_EMAILS_USED_BY_A_DEPT", "One or more of the selected emails is being used by a Dept. Remove association first.");
define("nl_SELECTED_ENTRIES", "selected entries");
define("nl_SELECTED_REPLIES_DELETED", "Selected replies deleted");
define("nl_SELECTED_REPLIES_DISABLED", "Selected replies disabled");
define("nl_SELECTED_REPLIES_ENABLED", "Selected replies enabled");
define("nl_SELECTED_SERVICES_ENABLED", "selected services enabled");
define("nl_SELECTED_TICKETS_CLOSED", "selected tickets closed");
define("nl_SELECTED_TICKETS_DELETED", "selected tickets deleted");
define("nl_SELECTED_TICKETS_OVERDUE", "selected tickets marked overdue");
define("nl_SELECTED_TICKETS_REOPENED", "selected tickets reopened");
define("nl_SELECTED_TICKETS", "selected tickets");
define("nl_SELECTED_TOPIC_DISABLED", "selected topics disabled");
define("nl_SELECTED_TOPICS_DELETED", "selected topics deleted");
define("nl_SELECTED_USERS", "selected user(s)");
define("nl_SEND_OVERLIMIT_NOTICE", "Send overlimit notice");
define("nl_SENT_ONLY_ONCE", "Sent <b>only once</b> on limit violation to the user. <b>Admin gets alerts on ALL denials by default</b>");
define("nl_SEQUENTIAL", "Sequential");
define("nl_SERVER_TIME", "Server time");
define("nl_SESSION_TIMED_OUT", "Session timed out due to inactivity");
define("nl_SHOW_ASSIGNED_TICKETS", "Show assigned tickets on open queue");
define("nl_SHOWING", "Showing");
define("nl_SIGNATURE", "Signature");
define("nl_SORT_BY", "Sort by");
define("nl_SQL_ERRORS", "SQL errors");
define("nl_STAFF_MAX_IDLE_TIME", "Staff's max Idle time in minutes. Enter 0 to disable timeout");
define("nl_STAFF_MEMBERS", "Staff Members");
define("nl_STAFF_PANEL", "Staff panel");
define("nl_STAFF_SESSION_TIMEOUT", "Staff Session Timeout");
define("nl_STATUS", "Status");
define("nl_STRIP_QUOTED_REPLY", "Strip Quoted Reply");
define("nl_SUBJECT_MISSING", "onderwerp mist");
define("nl_SUBJECT", "Onderwerp");
define("nl_SUBMIT_A_NEW_REQUEST", "Submit a new support request. Please provide as much detail as possible so we can best assist you. To update a previously submitted ticket, please use the form to the right. A valid email address is required.");
define("nl_SUMMARY_OF_THE_ISSUE_REQUIRED", "Summary of the issue required");
define("nl_SUPPORT_OFFLINE", "Support ticket system is offline");
define("nl_SUPPORT_TEAM", "Support Team ");
define("nl_SUPPORT_TICKET_CREATED", "Support ticket request created");
define("nl_SUPPORT_TICKET_REQ_DENIED_FOR", "Support ticket request denied for");
define("nl_SUPPORT_TICKET_SYSTEM", "Support ticket system");
define("nl_SYSTEM_ADMIN_EMAIL_ADDRESS", "System Admin Email Address");
define("nl_SYSTEM_ERRORS", "System Errors");
define("nl_SYSTEM_OFFLINE", "System offline");
define("nl_SYSTEM_PREFERENCES_AND_SETTINGS", "System Preferences and Settings");
define("nl_TABLE_PREFIX", "Table prefix");
define("nl_TEMPLATE_ALERT_MSG_REQUIRED", "Template alert message required");
define("nl_TEMPLATE_MSG_REQUIRED", "Template message required");
define("nl_TEMPLATES_UPDATED_SUCCESS", "Templates updated successfully");
define("nl_THANK_YOU_FOR_CHOOSING_OSTICKET", "Thank you for choosing osTicket.\nMake sure you join osTicket forums http://osticket.com/forums to stay upto date on the latest news, security alerts and updates. osTicket forums is also a great place to get assistance, guidance and help. In addition to the forums, osTicket wiki provides useful collection of educational materials, documentation, and notes from the community.\n\n If you are looking for greater level of support, we provide professional services and custom commercial support with guaranteed response times and access to the core development team. We can also customize the system to meet your unique needs.\nFor more information or to discuss your needs, please contact us today. Any feedback will be appreciated!\nosTicket Team");
define("nl_THANK_YOU_FOR_CONTACTING_US", "Bedankt voor het versturen van dit bericht.<br>Er is een support ticket aangemaakt een medewerker zal zo spoedig mogelijk contact met u opnemen.");
define("nl_THANK_YOU_HELPDESK_OFFLINE", "Thank you for your interest in contacting us.<br>Our helpdesk is offline at the moment, please check back at a later time.");
define("nl_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "This is global setting which can be disabled at department level");
define("nl_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Dit ticket is al toegekend aan de servicedesk.");
define("nl_TICKET_ALREADY_ASSIGNED" , "Ticket is al toegewezen.");
define("nl_TICKET_ALREADY_IN_DEPT", "Ticket is al toegewezen aan de juiste afdeling.");
define("nl_TICKET_ASSIGNED_TO_THE_STAFF", "Ticket is toegewezen aan de servbice afdeling");
define("nl_TICKET_CREATED_BY_STAFF", "Ticket aangemaakt bij de service afdeling");
define("nl_TICKET_CREATED_SUCCESS", "Ticket is succesvol aangemaakt");
define("nl_TICKET_DELETED_FOREVER", "Ticket is permanent verwijderd");
define("nl_TICKET_DENIED_403", "Ticket is niet geaccepteerd foutmelding #403");
define("nl_TICKET_DENIED_NOTICE", "Ticket is afgewezen melding");
define("nl_TICKET_FLAGGED_AS_OVERDUE", "Ticket flagged as overdue");
define("nl_TICKET_GRACE_PERIOD", "Ticket Grace Period");
define("nl_TICKET_ID", "Ticket IDs");
//define("nl_TICKET_LOWER", "ticket");
define("nl_TICKET_NOT_ASSIGNED", "Ticket is not assigned!");
define("nl_TICKET_OPTIONS_AND_SETTINGS", "Ticket Options &amp; Settings");
define("nl_TICKET_PRIORITY", "Ticket Priority");
define("nl_TICKET_RELEASED_FROM", "Ticket released (unassigned) from");
define("nl_TICKET_STATUS_SET_TO", "Ticket status set to");
define("nl_TICKET_STATUS", "Ticket status");
define("nl_TICKET_TRANSFER", "Ticket Transfered Successfully");
define("nl_TICKET_WILL_BE_REOPENED", "Ticket will be reopened on message post");
define("nl_TICKETS_PER_PAGE", "Tickets/items per page");
//define("nl_TICKETS", "Tickets");
define("nl_TIME_FORMAT", "Time Format");
define("nl_TITLE_ALREADY_EXISTS", "Title already exists");
define("nl_TITLE_REQ", "Title required");
define("nl_TITLE_REQUIRED", "Title required");
define("nl_TITLE", "Title");
define("nl_TO_BAN_EMAILS", "to ban emails");
define("nl_TO_CLOSE", "to close");
define("nl_TO_DELETE_SELECTED_DEPTS", "to delete selected depts");
define("nl_TO_DELETE_TICKETS", "to delete tickets");
define("nl_TO_DELETE", "to delete");
define("nl_TO_DISABLE", "to disable");
define("nl_TO_ENABLE", "to enable");
define("nl_TO_FLAG_TICKETS_OVERDUE", "to flag tickets overdue");
define("nl_TO_LOCK", "to lock");
define("nl_TO_MAKE_SELECTED_DEPTS_PRIVATE", "to make selected depts private");
define("nl_TO_MAKE_SELECTED_DEPTS_PUBLIC", "to make selected depts public");
define("nl_TO_MARK_SELECTED_TICKETS_OVERDUE", "to mark selected tickets overdue/stale");
define("nl_TO_REM_EMAILS_FROM_BANLIST", "remove emails from banlist.");
define("nl_TO_REOPEN", "to reopen");
define("nl_TO_VIEW_THE_STATUS_OF_A_TICKET", "To view the status of a ticket, provide us with your login details below.<br/>If this is your first time contacting us or you've lost the ticket ID, please <a href=\"open.php\">click here</a> to open a new ticket.");
define("nl_TO", "to");
define("nl_TOGGLE", "Toggle");
define("nl_TOPIC_TOO_SHORT", "Topic is too short. 5 chars minimum");
define("nl_TRANSFER", "transfer");
define("nl_TRY_AGAIN", "Try again");
define("nl_TYPE", "Type");
define("nl_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "Unable to add the email to banlist");
define("nl_UNABLE_TO_ADD_EMAIL", "Unable to add email. Internal error");
define("nl_UNABLE_TO_ADD_MAIL_TO_BANLIST", "Unable to add email to banlist. Try again");
define("nl_UNABLE_TO_ASSIGN_TICKET", "Unable to assign the ticket");
define("nl_UNABLE_TO_COMPLETE_ACTION", "Unable to complete action");
define("nl_UNABLE_TO_COMPLETE_PASS_CHANGE", "Unable to complete password change. Internal error.");
define("nl_UNABLE_TO_COMPLETE_THE_TRANSFER", "Unable to complete the transfer");
define("nl_UNABLE_TO_CONNECT_MYSQL", "Unable to connect to MySQL server. Possibly invalid login info. <br>");
define("nl_UNABLE_TO_CREATE_DB", "Unable to create the database due to permission");
define("nl_UNABLE_TO_CREATE_THE_REPLY", "Unable to create the reply. Internal error");
define("nl_UNABLE_TO_CREATE_TICKET", "Unable to create the ticket. Correct the error(s) and try again");
define("nl_UNABLE_TO_DELETE_SELECTED_DEPT", "Unable to delete selected departments.");
define("nl_UNABLE_TO_DELETE_SELECTED_EMAILS", "Unable to delete selected email(s).");
define("nl_UNABLE_TO_DISABLE_SELECTED_TOPICS", "Unable to disable selected topics");
define("nl_UNABLE_TO_FETCH_INFO_ON", "Unable to fetch info on");
define("nl_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "Unable to make remove selected emails");
define("nl_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "Unable to make selected department(s) private. Possibly already private!");
define("nl_UNABLE_TO_OPEN_CONF_FILE", "Unable to open config file for writting. Permission denied!");
define("nl_UNABLE_TO_POST_RESPONSE", "Unable to post the response.");
define("nl_UNABLE_TO_POST_THE_MESSAGE", "Unable to post the message");
define("nl_UNABLE_TO_POST_THE_NOTE", "Unable to post the note.");
define("nl_UNABLE_TO_REMOVE_EMAIL", "Unable to remove the email");
define("nl_UNABLE_TO_SELECT_DB", "Unable to select the database");
define("nl_UNABLE_TO_UPDATE_EMAIL", "Unable to update email. Internal error occured");
define("nl_UNBAN_EMAIL_LOWER", "unbanemail");
define("nl_UNKNOWN_ACTION", "Unknown action");
define("nl_UNKNOWN_BANLIST_COMMAND", "Uknown banlist command!");
define("nl_UNKNOWN_COMMAND", "Uknown command!");
define("nl_UNKNOWN_DEPT_ACTION", "Unknown Dept action");
define("nl_UNKNOWN", "Unknown");
define("nl_UPDATE_DEPARTMENT", "Update Department");
define("nl_UPDATE_ERROR", "Update error!");
define("nl_UPDATED_SUCCESS", "updated successfully");
define("nl_UPLOAD_DIR_INVALID", "upload dir invalid. Contact admin.");
define("nl_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "Use email priority when available (emailed tickets)");
define("nl_USERNAME_MISSING", "Username missing");
define("nl_USERNAME", "Username");
define("nl_USERS", "Users");
define("nl_VALID_EMAIL", "Valid email");
define("nl_VALID_PASS_REQ", "Valid password required");
define("nl_VIEW_STATUS", "View Status");
define("nl_WELCOME_BACK", "Welcome back! You are listed as 'on vacation' Please let admin or your manager know that you are back.");
define("nl_WELCOME_TO_SUPPORT_CENTER", "Welcome to the support center.");
define("nl_YOU_ARE_NOT_ALLOWED", "You are not allowed");
define("nl_YOU_HAVE_REACHED_MAX_TICKETS", "You've reached the maximum open tickets allowed.");
define("nl_YOU_LL_NEED_TICKET_NUMBER", "You'll need the ticket number along with your email to view status and progress online.");
define("nl_YOU_MUST_CHANGE_PASS", "You must change your password to continue.");
define("nl_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "You must enter hosts to whitelist");
define("nl_YOU_MUST_SELECT_ACTION_TO_PERFORM", "You must select action to perform");
define("nl_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "You must select at least one item");
define("nl_YOU_MUST_SELECT_ONE_EMAIL", "You must select at least one email");
define("nl_YOU_MUST_SELECT", "You must select");
define("nl_YOU_NEED_TO_SET_UPLOADDIR", "You need to setup upload dir.");
define("nl_YOU_PIPE_WE_ACCEPT_POLICY", "You pipe we accept policy");
define("nl_ZERO_RESULTS", "Query returned 0 results");
