<?php
define("no_A_DEPT", "Avdeling");
define("no_A_PRIORITY", "en prioritet");
define("no_ACCESS_DENIED", "Ingen tilgang");
define("no_ACTION_DENIED_TICKET_LOCKED", "Ingen tilgang. Supportsaken er låst av en annen saksbehandler");
define("no_ACTION_DENIED", "Ingen tilgang");
define("no_ACTIVE", "Aktive");
define("no_ADD_NEW_PREMADE_REPLY", "Legg til nytt forhåndslagd svar");
define("no_ADD_NEW_USER", "Legg til ny bruker");
define("no_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "Admin email får varsel som standard. Velg flere mottakere under");
define("no_ADMIN_EMAIL", "Admin email");
define("no_ADMIN_PANEL", "Kontrollplanel");
define("no_ADVANCED", "Avansert");
define("no_ALERT_FROM_EMAIL_ADDRESS", "Varsel FRA epostadresse");
define("no_ALERT_SUBJECT_MISSING", "Varsel emne mangler");
define("no_ALERTS_NOTICES", "Varsel &amp; merknader");
define("no_ALL_DEP", "Alle avdelinger");
define("no_ALL_DEPTS", "Alle avdelinger");
define("no_ALL", "Alle");
define("no_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Tilat kunde å overskrive/sette prioritet (supportsak)");
define("no_ALLOWED_FILE_EXT_REQ", "Tillat filtype kreves");
define("no_ALLOWED", "Tillatt");
define("no_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "En e-post med supportsaksnummer er sendt til");
define("no_ANOTHER_DEPT_USING_HOST_COMBINATION", "En annen avdeling bruker host/bruker kombinasjonen.");
define("no_ANSWER", "Svar");
define("no_API_SETTINGS_UPDATED", "API instillinger oppdatert");
define("no_ARE_YOU_SURE_YOU_WANT", "Er du sikker?");
define("no_ASSIGN", "Tildel");
define("no_ASSIGNED_STAFF", "Tilordnet saksbehandler");
define("no_ASSIGNED_TICKETS", "Tilordnet supportsak");
define("no_AT_LEAST_ONE_TOPIC", "minst ett emne");
define("no_ATTACH_FILE", "Vedlagt fil");
define("no_ATTACH_SETTINGS_UPDATED", "Vedlegsinstillinger oppdatert");
define("no_ATTACH", "Vedlegg");
define("no_ATTACHMENT_DISABLED", "Vedlegg deaktivert");
define("no_ATTEMPTS", "Forsøk");
define("no_AUTHENTICATION_REQUIRED", "Autentisering påkrevd");
define("no_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Autotildeling gjenåpner supportsak til ledig saksbehandler'. (<i> 3 mnd frist</i>)");
define("no_AUTOLOCK_TIME", "Auto-lock tid");
define("no_AUTORESPONDERS_GLOBAL_SETTING", "Autosvar &nbsp;(Global instilling)");
define("no_AUTORESPONDERS", "Autosvar");
define("no_AUTORESPONSE_FROM_EMAIL", "Autosvar FRA epost");
define("no_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Autosvar inkluderer saksnummer for å se status på supportsaken");
define("no_BAD_PREFIX_UNDERSCORE", "Feil prefix. Må ha understrek (_) i enden. eks. 'ost_'");
define("no_BAN_EMAIL_LOWER", "utestengt espot");
define("no_BYTES_ALLOWED", "bytes tillatt");
define("no_CAN_BE_APPENDED_TO_RESPONSES", "can legges til svar. &nbsp;(tilgjengelig som valg for avdelinger)  ");
define("no_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "Kan ikke slette avdeling da den har tilknytning til emner. Slett emne først.");
define("no_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "Kan ikke slette avdeling. Flytt saksbehandlere til en annen avdeling først");
define("no_CANCEL", "Avbryt");
define("no_CATEGORY", "Kategori");
define("no_CELL_PHONE", "Mobiltelefon");
define("no_CHANGE_PASS", "Endre passord");
define("no_CHANGE_PRIORITY", "change_priority");
define("no_CHECK_STATUS_OPENED_TICKETS", "Sjekk status for tidligere åpnet suportsak. Vi lagrer all historikk med svar på sine supportsaker.");
define("no_CHECK_STATUS", "Sjekk status");
define("no_CLICKABLE_URL", "Klikkbare URLs");
define("no_CLIENT_SESSION_TIMEOUT_IN_MINS", "Kundes max Idle tid i minutter. Velg 0 for å deaktivere timeout");
define("no_CLIENT_SESSION_TIMEOUT", "Kundes Session Timeout");
define("no_CLOSE_LOWER", "lukk");
define("no_CLOSE_REOPEN_TICKETS", "lukk/gjenåpne supportsak");
define("no_CLOSE", "Lukk");
define("no_CLOSED", "Lukket");
define("no_COMMERCIAL_SUPPORT_AVAILABLE", "Kommersiell support tilgjengelig");
define("no_CONF_FILE_ALREADY_MOD", "Konfigurasjonsfilen allerede endret!");
define("no_CONF_FILE_NOT_WRITABLE", "Konfigurasjonsfilen er ikke skrivbar");
define("no_CONFIRM_NEW_PASS", "Bekreft nytt passord");
define("no_CONFIRM", "Bekreft");
define("no_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Koflikt med system epost over");
define("no_CONTACT_ADMIN", "Kontakt systemadmin hvis du tror dette er feil");
define("no_CREATE_DATE", "Opprettelsesdato");
define("no_CURR_PASS_REQ", "Gjeldende passord kreves");
define("no_CURR_TIME", "Gjeldende tid");
define("no_DATE_AND_TIME_FORMAT", "Dato &amp; Tid format");
define("no_DATE_AND_TIME", "Dato &amp; Tid");
define("no_DATE_FORMAT", "Dato format");
define("no_DAY_DATE_TIME_FORMAT", "Dag, Dato &amp; Tid format");
define("no_DAYLIGHT_SAVING", "Daylight lagring");
define("no_DAYLIGHT_SAVINGS", "Daylight lagring");
define("no_DB_NOT_EXISTS", "Database ekstiterer ikke");
define("no_DEFAULT_DEPARTMENT", "Standard avdeling");
define("no_DEFAULT_EMAIL_TEMPLATE", "Standard epostmal");
define("no_DEFAULT_EMAIL", "Standard epost");
define("no_DEFAULT_PAGE_SIZE", "Standrad sidestørrelse");
define("no_DEFAULT_PRIORITY", "Standard prioritet");
define("no_DEFAULT_TIMEZONE", "Standard tidssone");
define("no_DELETE_DEPS", "Slett avdelinger");
define("no_DELETE_LOWER", "slett");
define("no_DELETE_TICKETS", "delete supportsaker");
define("no_DELETE", "Slett");
define("no_DEPARTMENT_MANAGED", "Avdelingsleder (spammy)");
define("no_DEPARTMENT_MANAGER", "Avdelingsleder");
define("no_DEPARTMENT_MEMBERS", "Avdelingens saksbehandlere (spammy)");
define("no_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Svar vil bli gjort tilgjengelig under gjeldende avdeling");
define("no_DEPARTMENTS", "Avdelinger");
define("no_DEPENDS_ON_THE_TAG_BELOW", "Avhenger av taggen under");
define("no_DEPT_DEPENDS_ON_EMAIL", "Avdeling avhenger av epost &amp; hjelpeemner instillinger for inkommende supportsaker.");
define("no_DEPT_EMAIL_ABOVE", "Avdelingens epost (over)");
define("no_DEPT_EMAIL", "Avdelingsepost");
define("no_DEPT_MANAGER", "Avdelingsleder");
define("no_DEPT_NAME", "Avdelingens navn");
define("no_DEPT_SIGNATURE", "Avdelingssignatur");
define("no_DEPT_TRANSFER", "Avdelings overføring");
define("no_DEPT_TYPE", "Avdelingstype");
define("no_DEPT", "Avdeling");
define("no_DIR_MUST_BE_VALID_WRITABLE", "Katalogen må være gyldig og skrivbar");
define("no_DIRECTORY", "Katalog");
define("no_DISABLE", "Deaktiver");
define("no_DISABLED", "Deaktivert");
define("no_DO_REQUESTED_ACTION", "Gjør forespurt handling");
define("no_EDIT_PREMADE_REPLY", "Endre autosvar");
define("no_EMAIL_ADD_SUCCESS", "Epost tilagt");
define("no_EMAIL_ADDED_TO_BANLIST", "Epost tilagt utestengt epost");
define("no_EMAIL_ADDRESS", "Epostadresse");
define("no_EMAIL_ALREADY_BANNED", "Epost er allerede tilagt utestengt epost");
define("no_EMAIL_ALREADY_EXISTS", "Epost eksiterer allerede");
define("no_EMAIL_IN_BANLIST", "Epost tilagt utestengt epost. Må fjernes derfra for å svare");
define("no_EMAIL_MISMATCH", "Epost mismatch");
define("no_EMAIL_REMOVED", "Epost slettet");
define("no_EMAIL_SETTINGS", "Emailinstillinger");
define("no_EMAIL_UNKNOWN", "Ukjent epost");
define("no_EMAIL_UPDATED_SUCCESS", "Email oppdatert");
define("no_ENABLE_AUTOCRON", "Aktiver Auto-Cron");
define("no_ENABLE_CRON_CALL", "Aktiver cron call på saksbehandler aktivitet");
define("no_ENABLE_EMAIL_PIPING", "Aktiver epost piping");
define("no_ENABLE_POP3_EMAIL_FETCH", "Aktiver POP3 email fetch");
define("no_ENABLE", "Aktiver");
define("no_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Feil sendes til adminepost over");
define("no_ENTER_MESSAGE", "Melding");
define("no_ENTER_VALID_NUM", "Skriv inn gyldig nummer");
define("no_ERR_SQL_SYNTAX", "Du har en feil i DQL syntaks ");
define("no_ERROR_OCCURED", "Feil oppstod");
define("no_ERROR_OCCURRED", "Feil oppstod. Se feilmelding under");
define("no_EXCESSIVE_LOGIN_ATTEMPTS", "For mange påloggingsforsøk");
define("no_FATAL_ERROR", "Fatal feil");
define("no_FETCH_INTERVAL_REQUIRE", "Fetch intervall kreves");
define("no_FILE_TOO_BIG", "Filen er for stor");
define("no_FILE_UPLOAD_DISABLED_PHP_INI", "Fildirektivet er deaktivert i php.ini");
define("no_FIRST_NAME", "Fornavn");
define("no_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "For at POP3 mail fetch skal fungere må du sette en opp en cron job eller aktivere auto-cron");
define("no_FORGOT_LOGIN_INFO", "Glemt påloggingsinfo? Vennlist <a href=\"open.php\">åpne en ny supportsak</a>.");
define("no_FROM_BANLIST", "fra utestengt epostliste");
define("no_FULL_NAME", "Navn");
define("no_GENERAL_INQUIRY", "Generelle spørsmål");
define("no_GENERAL_SETTINGS", "Generelle instillinger");
define("no_GET_A_PEACE_OF_MIND", "Ta det rolig!");
define("no_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "Global autosvar i instillinger må være aktivert for avdeling for at instillingene skal tre i kraft. ");
define("no_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "Global instilling om kan deaktiveres på epostnivå");
define("no_HELP_TOPIC", "Helpeemne");
define("no_HELPDESK_NAME", "Helpdesk Navn/Tittel");
define("no_HELPDESK_STATUS", "Helpdesk status");
define("no_HELPDESK_URL", "Helpdesk URL");
define("no_HELPS_WITH_SPAM", "Hjelper med spamkontroll. Velg 0 for ubegrenset");
define("no_HOME", "Hjem");
define("no_HOST_MISSING", "Host mangler");
define("no_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Timer før supportsaken blir markert forsinket. Tast 0 for å deaktivere auto-forsinkelse");
define("no_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "Hvis aktivert supportsaklås får automatisk fornyelse.");
define("no_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "Hvis du ønsker å sende ytterligere kommentarer eller opplysninger vedrørende samme sak, må du følge instruksjonene på e-post");
define("no_IMAP_DOESNT_EXISTS", "IMAP ekstierer ikke. PHP må kombinert med IMAP aktivert.");
define("no_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "For å effektivisere support forespørsler og gi deg bedre service, benytter vi et eget supportsystem. Hver henvendelse blir tildelt et unikt saksnummer som du kan bruke til å spore fremgang og svar. All historikk blir lagret i våre systemer.");
define("no_INDICATE_SOURCE", "Indikere kilde");
define("no_INSTALL_COMPLETE", "Gratulerer - osTicket installasjonen er fullført!");
define("no_INTERNAL_ERROR_OCCURED", "Intern feil oppstod");
define("no_INTERNAL_ERROR", "Intern feil. Vennligst sørg for at nedlastingen er den siste");
define("no_INTERNAL_NOTE_POSTED", "Internt notat skrevet");
define("no_INVALID_ATTACH", "Ugyldig vedlegg");
define("no_INVALID_FILE_TYPE", "Ugyldig filtype");
define("no_INVALID_FILE", "Ugyldig fil");
define("no_INVALID_LOGIN", "Ugyldig login");
define("no_INVALID_SOURCE", "Ugyldig kilde");
define("no_INVALID_SQL_SCHEMA", "Ugyldig SQL skjema. Kontakt utvikler/systemadmin");
define("no_INVALID_UPLOAD_DIR", "Ukyldig opplastningskatalog");
define("no_INVALID", "Ugyldig");
define("no_KNOWLEDGE_BASE", "Kunnskapsbase");
define("no_LANG_PRIVATE", "Privat");
define("no_LANG_PUBLIC", "Offentlig");
define("no_LAST_NAME", "Etternavn");
define("no_LAST_RESPONDENT", "Siste saksbehandler");
define("no_LAST_UPDATED", "Sist oppdatert");
define("no_LOCK", "Lås");
define("no_LOCKED", "Låst");
define("no_MAIL_METH", "Epostmetoder");
define("no_MAIL_PARSE_ERRORS", "Epost feil");
define("no_MAKE_PRIVATE", "Gjør privat");
define("no_MAKE_PUBLIC", "Gjør offentlig");
define("no_MAKE_URL_CLICKABLE", "Gjør URL'er klikkbare");
define("no_MANAGER", "Leder");
define("no_MASS_MANAGE_TICKETS", "Masseadminister supportsaker. Kontakt systemadmin for tilgang");
define("no_MAX_ALLOWED", "Max tillatt");
define("no_MAX_FILE_SIZED_REQ", "maksimum filstørrelse kreves");
define("no_MAX_LOGIN_ATTEMPTS", "Du har brukt opp antall påloggingsforsøk. Prøv igjen om 5 minutter eller <a href=\"open.php\">åpne en ny supportsak</a>");
define("no_MAX_OPEN_TICKETS", "Maksimum <b>Åpne</b> supportsaker");
define("no_MAX_PAGE_SIZE", "Maks sidestørrelse");
define("no_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Melding lagt til en eksisterende supportsak bekreftelse");
define("no_MESSAGE_POSTED_SUCCESS", "Melding publisert");
define("no_MESSAGE_REQUIRED", "Melding kreves");
define("no_MESSAGE", "Melding");
define("no_MIN_TO_LOCK_A_TICKET", "Minutter til å låse supportsak. Velg 0 for å deaktivere låsing");
define("no_MISSING_MESSAGE", "Mangler meldingsID");
define("no_MISSING_OR_INVALID_GROUP", "Mangler/Ugyldig gruppe");
define("no_MISSING_SQL_SCHEMA", "Mangler SQL Skjema");
define("no_MOBILE", "Mobil");
define("no_MUST_BE_SIX_CHARS", "Må være minst 6 tegn");
define("no_MUST_SELECT_PRIORITY", "Du må velge prioritet");
define("no_MY_ACCOUNT", "Min konto");
define("no_MY_PREFERENCES", "Mine instillinger");
define("no_MY_PROFILE_INFO", "Min profilinformasjon");
define("no_MY_PROFILE", "Min profil");
define("no_NAME", "Navn");
define("no_NEED_HELP_QUESTION", "Trenger du hjelp?");
define("no_NEW_DEPT", "Ny avdeling");
define("no_NEW_MESSAGE_ALERT", "Ny meldingsvarsel");
define("no_NEW_MESSAGE", "Ny melding");
define("no_NEW_PASS_NOT_MATCH", "Nytt passord matcher ikke");
define("no_NEW_PASS_REQ", "Nytt passord kreves");
define("no_NEW_PASS_SAME_OLD", "Nytt passord er det samme som det gamle");
define("no_NEW_PREMADE_REPLY", "Nytt autosvar");
define("no_NEW_TICKET_ALERT", "Ny supportsakvarsel");
define("no_NEW_TICKET", "Ny supportsak");
define("no_NO_ACCESS_TO_TICKET", "Du har ikke tilgang til supportsaken");
define("no_NO_PERMISSION_TO_REASSIGN", "Du har ikke rettigheter til å tildele supportsaker");
define("no_NO_PERMISSION_TO", "Du har ikke rettigeter til");
define("no_NO_REPLY_EMAIL_ADDRESS", "Ikke-svar epostadresse");
define("no_NO_REPLY_EMAIL", "Ikke-svar epost");
define("no_NO_STAFF_FOUND", "Ingen saksbehandlere funnet");
define("no_NO_SUCH_FILE", "Ingen slik fil");
define("no_NO_TICKETS_FOUND", "Ingen supportsaker funnet");
define("no_NO_TICKETS_SELECTED", "Ingen supportsak er valgt. Du må velge minst en supportsak.");
define("no_NO_USER_ADD_USER", "Ingen brukere (Add bruker)");
define("no_NONE", "Ingen");
define("no_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "Du har ikke rettigheter til å forandre sakens prioritet");
define("no_NOT_ALLOWED_TO_TRANSFER_TICKETS", "Du har ikke rettigheter til å overføre supportsaken");
define("no_NOTE_REQ", "Notat kreves");
define("no_NOTE_REQUIRED", "Notat/melding kreves");
define("no_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Notat er sendt til bruker. Epost varseler saksbehandler");
define("no_OBSERVE", "Observer");
define("no_OF", "di");
define("no_OFFICE_PHONE", "Arbeidstelefon");
define("no_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "Frakoblet modul vil deaktivere klients grensesnitt og tillater <b>bare</b> <b>super admin</b> å logge på SupportCenteret");
define("no_OFFLINE", "Frakoblet");
define("no_ONLINE", "Pålogget");
//define("no_OPEN_LOWER", "åpne");
define("no_OPEN_NEW_TICKET", "Åpne ny supportsak");
define("no_OPEN_TICKET", "Åpne supportsak");
define("no_OPEN", "Åpne");
define("no_OSTICKET_BASIC_INSTALL", "osTicket Basic installasjon");
define("no_OSTICKET_INSTALLER", "osTicket Installer");
define("no_OSTICKET_REQUIRES_MYSQL", "osTicket krever MySQL 4.1.1 eller bedre! Vennligst oppgrader");
define("no_OUTGOING_EMAIL", "Utgående mail");
define("no_OVERDUE_LOWER", "forfalte");
define("no_OVERDUE_TICKET_ALERT", "Forfalt epostvarsel");
define("no_OVERLIMIT_NOTICE", "Overlimit Notat");
//define("no_PAGE", "side");
define("no_PASS_CHANGE_SUCCESS", "Passord endret");
define("no_PASS_TO_NOT_MATCH", "Passord stemmer ikke");
define("no_PASSWORD_REQUIRED", "Passord kreves");
define("no_PER_EMAIL", "pr epost");
define("no_PERM_DENIED", "Perm. Avslått.");
define("no_PHONE_NUM_REQ", "Telefon # kreves");
define("no_PHONE", "Telefon");
define("no_PHP_DATE_MANUAL", "Vennligt besøk <a href=\"http://php.net/date\" target=\"_blank\">PHP Manual</a> for støttede parametre.");
define("no_PHP_OUT_OF_DATE", "PHP installasjon utdatert");
define("no_PHRASE_TOO_SHORT", "Setningen er for kort!");
define("no_PHRASE_TWO_WORDS", "Setning av 2+ ord");
define("no_PLEASE_ENTER_VALID_EMAIL", "Vennligst skriv inn gyldig epost.");
define("no_PLEASE_FILL_TO_OPEN_A_TICKET", "Vennligst fyll ut skjemaet nedenfor for å åpne en ny supportsak.");
define("no_POSSIBLE_ERROR_DETECTED", "Mulige feil oppdaget, vennligst sjekk advarslene nedenfor");
define("no_POSSIBLY_ACCESS_DENIED", "Tilgang nektes, vennligst kontakt teknisk brukerstøtte.");
define("no_POSSIBLY_INVALID_TICKET", "Ukyldig saksnummer");
define("no_POST_REPLY", "Svar");
define("no_POSTNOTE", "notat");
define("no_PREF_ERROR", "Feil ved oppdatering av instillinger.");
define("no_PREF_UPDATED", "Instillinger oppdatert");
define("no_PREFERENCES", "Instillinger");
define("no_PREFERRED_TIMEZONE", "Ønsket tidssone");
define("no_PREMADE_REPLIES", "Autosvar");
define("no_PREMADE_REPLY", "Autosvar");
define("no_PRIMARY_OUTGOING_MAIL", "Primær utgående epost");
define("no_PRIORITY_CHANGED_SUCCESS", "Prioritert endret");
define("no_PRIORITY", "Prioritet");
define("no_PRIVATE_HIDDEN", "Privat (gjemt)");
define("no_PROBLEM_CHANGING_PRIORITY", "Problemer med å endre prioritet");
define("no_PROBLEM_CLOSING_TICKET", "Problemer med å lukke supportsak");
define("no_PROBLEM_RELEASING_TICKET", "Problemer med å sende supportsak");
define("no_PROBLEM_REOPENING_TICKET", "Problemer med å gjenåpne supportsak.");
define("no_PROBLEMS_ADMIN_PAGE", "Problemer med å laste adminside.");
define("no_PROBLEMS_DELETING_THE_TICKET", "Problemer med å slette supportsak");
define("no_PROBLEMS_DISPLAYING_DIR", "Problemer med å vise katalogen");
define("no_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Problemer med å markere forfalt supportsak");
define("no_PROCESS", "prosess");
define("no_PROF_INST_AVAILABLE", "Professional installasjon tilgjengelig");
define("no_PROFILE_UPDATE_SUCCESS", "Profil oppdatert!");
define("no_PUBLIC", "Offentlig");
define("no_QUERY", "Søk");
define("no_RANDOM", "Tilfeldig");
define("no_RECOMMENDED", "anbefales");
define("no_REJECTED", "avvist");
define("no_RELEASE_LOWER", "slipp");
define("no_REMOVING_QUOTED_REPLY", "Fjern siterte svar");
define("no_REOPEN_LOWER", "gjenåpne");
define("no_REOPEN", "Gjenåpne");
define("no_REOPENED_TICKETS", "Gjenåpnede supportsaker");
define("no_REPLY_REQUIRED", "Svar kreves");
define("no_REPLY_SEPARATOR_TAG", "Svar SeparatorTag");
define("no_REPLY_TITLE", "Svar tittel");
define("no_REPLY", "svar");
define("no_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Nødvendig når avdeling er offentlig");
define("no_REQUIRED", "påkrevd");
define("no_RESET_CHANGES", "Nullstill endringer");
define("no_RESET", "Nullstill");
define("no_RESPONSE_MESSAGE_REQUIRED", "Svarmelding påkrevd");
define("no_RESPONSE_POSTED_SUCCESS", "Svar sendt");
define("no_SALVE_EMAIL_HEADERS", "Lagre epostoverskrift");
define("no_SAVE_CHANGES", "Lagre endringer");
define("no_SAVE_RAW_HEADERS", "Lagre overskrift");
define("no_SAVE", "Lagre");
define("no_SEARCH_FOR", "Søk etter");
define("no_SEARCH_TERM_MORE_THAN_3_CHARS", "Søkestrengen må være mer enn 3 tegn");
define("no_SEARCH", "Søk");
define("no_SECURITY_VIOLATION", "Sikkerhetbrudd. Gjentatte brudd vil føre til at kontoen din blir låst.");
define("no_SELECT_ASSIGNEE", "Velg oppdragsansvarlig");
define("no_SELECT_DEFAULT_DEPT", "Velg standard avdeling");
define("no_SELECT_DEPARTMENT", "Velg avdeling");
define("no_SELECT_HELP_TOPIC", "Velg emne");
define("no_SELECT_MANAGER_OPT", "Velg avdelingsleder (valgfritt)");
define("no_SELECT_ONE", "Velg en");
define("no_SELECT_RECIPIENTS", "Velg mottakere");
define("no_SELECT", "Velg");
define("no_SELECTED_DEPT_DELETED", "utvalgte avdelinger er slettet");
define("no_SELECTED_EMAILS_DELETED", "utvalgte epostadresser er slettet");
define("no_SELECTED_EMAILS_REMOVED", "utvalgte epostadresser er sletttet fra utestengt epostliste");
define("no_SELECTED_EMAILS_USED_BY_A_DEPT", "En eller flere av de valgte e-postadressene blir brukt av en avdeling. Fjern avdeling først.");
define("no_SELECTED_ENTRIES", "utvalgte oppføringer");
define("no_SELECTED_REPLIES_DELETED", "utvalgte svar erslettet");
define("no_SELECTED_REPLIES_DISABLED", "utvalgte svar er deaktivert");
define("no_SELECTED_REPLIES_ENABLED", "utvalgte svar er aktivert");
define("no_SELECTED_SERVICES_ENABLED", "utvalgte tjenester er aktivert");
define("no_SELECTED_TICKETS_CLOSED", "utvalgte supportsaker er lukket");
define("no_SELECTED_TICKETS_DELETED", "utvalgte supportsaker er slettet");
define("no_SELECTED_TICKETS_OVERDUE", "utvalgte supportsaker er markert som forfalt");
define("no_SELECTED_TICKETS_REOPENED", "utvalgte supportsaker er gjenåpnet");
define("no_SELECTED_TICKETS", "utvalgte supportsaker");
define("no_SELECTED_TOPIC_DISABLED", "utvalgte emner deaktivert");
define("no_SELECTED_TOPICS_DELETED", "utvalgte emner slettet");
define("no_SELECTED_USERS", "utvalgt(e) bruker(e)");
define("no_SEND_OVERLIMIT_NOTICE", "Send varsel om at grensen er nådd");
define("no_SENT_ONLY_ONCE", "Sendt <b>bare en gang</b>. <b>Admin får varseler på alle fornektelser som standard</b>");
define("no_SEQUENTIAL", "Sekvensiell");
define("no_SERVER_TIME", "Servertid");
define("no_SESSION_TIMED_OUT", "Tidsavbrutt - årsak: inaktivitet");
define("no_SHOW_ASSIGNED_TICKETS", "Vis tildelte supportsaker i åpen kø");
define("no_SHOWING", "Vis");
define("no_SIGNATURE", "Signatur");
define("no_SORT_BY", "Sorter");
define("no_SQL_ERRORS", "SQL feil");
define("no_STAFF_MAX_IDLE_TIME", "Saksbehandlers max Idle tid i minutter. Velg 0 for å deaktivere timeout");
define("no_STAFF_MEMBERS", "Saksbehandlere");
define("no_STAFF_PANEL", "SupportCenter");
define("no_STAFF_SESSION_TIMEOUT", "Saksbehandler timeout");
define("no_STATUS", "Status");
define("no_STRIP_QUOTED_REPLY", "Strip sitert svar");
define("no_SUBJECT_MISSING", "Emne mangler");
define("no_SUBJECT", "Tittel");
define("no_SUBMIT_A_NEW_REQUEST", "Send inn en ny henvendelse. Vennligst oppgi så mange detaljer som mulig slik at vi best kan hjelpe deg. For å oppdatere en tidligere supportsak, kan du bruke skjemaet til høyre. En gyldig e-postadresse kreves.");
define("no_SUMMARY_OF_THE_ISSUE_REQUIRED", "Oppsummering av problemet kreves");
define("no_SUPPORT_OFFLINE", "SupportCenteret er Offline");
define("no_SUPPORT_TEAM", "Support Team ");
define("no_SUPPORT_TICKET_CREATED", "Supportsak opprettet");
define("no_SUPPORT_TICKET_REQ_DENIED_FOR", "Supportsak forespørsel nektet for");
define("no_SUPPORT_TICKET_SYSTEM", "SupportCenter system");
define("no_SYSTEM_ADMIN_EMAIL_ADDRESS", "Epostadresse systemadmin");
define("no_SYSTEM_ERRORS", "Systemfeil");
define("no_SYSTEM_OFFLINE", "System frakoblet");
define("no_SYSTEM_PREFERENCES_AND_SETTINGS", "Systemvalg og instillinger");
define("no_TABLE_PREFIX", "Table prefix");
define("no_TEMPLATE_ALERT_MSG_REQUIRED", "Mal for varselsmelding kreves");
define("no_TEMPLATE_MSG_REQUIRED", "Meldingsmal kreves");
define("no_TEMPLATES_UPDATED_SUCCESS", "Mal oppdatert");
define("no_THANK_YOU_FOR_CHOOSING_OSTICKET", "Takk for at du valgte osTicket.\nSørg for å joine osTicket forums http://osticket.com/forums for å oppdateringer og sikkerhetsmeldinger. På osTicket forums har du også muligheten til å få hjelp ifm av guider, svar osv. I tillegg til forumet, formidler osTicket brukervenlige opplæringsmanualer, dokumentasjon, og notater. \n\n Hvis du ønsker ytterligere support tilbyr vi kommersiell support med svargaranti og utvidet tilgang. Vennlist kontakt oss!");
define("no_THANK_YOU_FOR_CONTACTING_US", "Takk for at du kontaktet oss. <br>Supportsaken er nå sendt til vår supportavdeling, og en saksbehandler vil komme tilbake til deg i løpet av kort tid.");
define("no_THANK_YOU_HELPDESK_OFFLINE", "Takk for din interesse i å kontakte oss. <br> Vårt SupportCenter er stengt for øyeblikket, vennligst kom tilbake på et senere tidspunkt.");
define("no_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "Dette er global innstilling som kan deaktiveres på avdelingsnivå");
define("no_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Supportsak allerede tildelt saksbehandler.");
define("no_TICKET_ALREADY_ASSIGNED" , "Supportsak allerede tildelt");
define("no_TICKET_ALREADY_IN_DEPT", "Supportsak allerede tildelt avdelingen");
define("no_TICKET_ASSIGNED_TO_THE_STAFF", "Supportsak tildelt saksbehandler");
define("no_TICKET_CREATED_BY_STAFF", "Supportsak opprettet av saksbehandler");
define("no_TICKET_CREATED_SUCCESS", "Supportsak opprettet");
define("no_TICKET_DELETED_FOREVER", "Supportsak slettet");
define("no_TICKET_DENIED_403", "Supportsak feil #403");
define("no_TICKET_DENIED_NOTICE", "Supportsak: notatfeil");
define("no_TICKET_FLAGGED_AS_OVERDUE", "Supportsak merket forfalt");
define("no_TICKET_GRACE_PERIOD", "Supportsak utsettelse");
define("no_TICKET_ID", "Saksnummer");
//define("no_TICKET_LOWER", "supportsak");
define("no_TICKET_NOT_ASSIGNED", "Supportsak er ikke tildelt");
define("no_TICKET_OPTIONS_AND_SETTINGS", "Supportsak instillinger &amp; Instillinger");
define("no_TICKET_PRIORITY", "Saksprioritet");
define("no_TICKET_RELEASED_FROM", "Supportsak utgitt/tilordnet av");
define("no_TICKET_STATUS_SET_TO", "Sakstatus satt til");
define("no_TICKET_STATUS", "Sakstatus");
define("no_TICKET_TRANSFER", "Supportsak flyttet");
define("no_TICKET_WILL_BE_REOPENED", "Supportsaken vil bli gjenåpnet ved ny korrespondanse");
define("no_TICKETS_PER_PAGE", "Supportsak per side");
//define("no_TICKETS", "Supportsak");
define("no_TIME_FORMAT", "Tidsformat");
define("no_TITLE_ALREADY_EXISTS", "Tittel eksisterer allerede");
define("no_TITLE_REQ", "Tittel kreves");
define("no_TITLE_REQUIRED", "Tittel kreves");
define("no_TITLE", "Tittel");
define("no_TO_BAN_EMAILS", "til utestengte epostadresser");
define("no_TO_CLOSE", "for å lukke");
define("no_TO_DELETE_SELECTED_DEPTS", "for å slette utvalgte avdelinger");
define("no_TO_DELETE_TICKETS", "for å slette supportmelding(er)");
define("no_TO_DELETE", "for å slette");
define("no_TO_DISABLE", "for å deaktivere");
define("no_TO_ENABLE", "for å aktivere");
define("no_TO_FLAG_TICKETS_OVERDUE", "for å markere supportsak(er) forfalt");
define("no_TO_LOCK", "for å låse");
define("no_TO_MAKE_SELECTED_DEPTS_PRIVATE", "for å sette utvalgte avdelinger privat");
define("no_TO_MAKE_SELECTED_DEPTS_PUBLIC", "for å sette utvalgte avdelinger offentlig");
define("no_TO_MARK_SELECTED_TICKETS_OVERDUE", "for å sette utvalgte supportsaker forfalt");
define("no_TO_REM_EMAILS_FROM_BANLIST", "fjern epostadresser fra utestengt epostliste");
define("no_TO_REOPEN", "for å gjenåpne");
define("no_TO_VIEW_THE_STATUS_OF_A_TICKET", "For å se status på din supportsak, vennligst login med din epostadresse og saksnummer under.<br/>Hvis det er første gang du kontakter oss i SupportCenteret, vennligst <a href=\"open.php\">klikk her</a> for å åpne en ny supportsak.");
define("no_TO", "til");
define("no_TOGGLE", "Veksle");
define("no_TOPIC_TOO_SHORT", "Emne er for kort. Minimum 5 tegn kreves");
define("no_TRANSFER", "overfør");
define("no_TRY_AGAIN", "Prøv igjen");
define("no_TYPE", "Type");
define("no_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "Kan ikke legge til epost i utestengt epostliste");
define("no_UNABLE_TO_ADD_EMAIL", "Kan ikke legge til epostadresse. Internfeil");
define("no_UNABLE_TO_ADD_MAIL_TO_BANLIST", "Kan ikke legge til epost i utestengt epostliste. Prøv igjen");
define("no_UNABLE_TO_ASSIGN_TICKET", "Kan ikke tildele supportsak");
define("no_UNABLE_TO_COMPLETE_ACTION", "Kan ikke fullføre handlingen");
define("no_UNABLE_TO_COMPLETE_PASS_CHANGE", "Klarte ikke fullføre endring av passord. Internfeil.");
define("no_UNABLE_TO_COMPLETE_THE_TRANSFER", "Klarte ikke å fullføre flytteprosessen");
define("no_UNABLE_TO_CONNECT_MYSQL", "Kan ikke koble til MySQL server. Mulighens feil logininfo <br>");
define("no_UNABLE_TO_CREATE_DB", "Kan ikke opprette databasen på grunn av tillatelse");
define("no_UNABLE_TO_CREATE_THE_REPLY", "Kan ikke opprette svar. Internfeil");
define("no_UNABLE_TO_CREATE_TICKET", "Kan ikke opprette supportsak. Korrigere feilen(e), og prøv igjen");
define("no_UNABLE_TO_DELETE_SELECTED_DEPT", "Kan ikke slette valgte avdelinger.");
define("no_UNABLE_TO_DELETE_SELECTED_EMAILS", "Kan ikke slette valgte epostadresser");
define("no_UNABLE_TO_DISABLE_SELECTED_TOPICS", "Kan ikke deaktivere valgte emner");
define("no_UNABLE_TO_FETCH_INFO_ON", "Kan ikke hente informasjon om");
define("no_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "Kan ikke fjerne utvalgte e-postadresser");
define("no_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "Kan ikke gjøre valgt(e) avdeling(er) privat. Muligens allerede privat!");
define("no_UNABLE_TO_OPEN_CONF_FILE", "Kan ikke åpne config-filen for skriving. Tillatelse nektet!");
define("no_UNABLE_TO_POST_RESPONSE", "Kan ikke poste svar.");
define("no_UNABLE_TO_POST_THE_MESSAGE", "Kan ikke poste meldingen.");
define("no_UNABLE_TO_POST_THE_NOTE", "Kan ikke poste notat.");
define("no_UNABLE_TO_REMOVE_EMAIL", "Kan ikke fjerne epostadresse");
define("no_UNABLE_TO_SELECT_DB", "Klare ikke velge database");
define("no_UNABLE_TO_UPDATE_EMAIL", "Kan ikke oppdatere e-post. Intern feil oppstod");
define("no_UNBAN_EMAIL_LOWER", "utestengt epostliste");
define("no_UNKNOWN_ACTION", "ukjent handling");
define("no_UNKNOWN_BANLIST_COMMAND", "Ukjent utestengt epostliste kommando!");
define("no_UNKNOWN_COMMAND", "Ukjent kommando");
define("no_UNKNOWN_DEPT_ACTION", "Ukjent avdelingshandling");
define("no_UNKNOWN", "Ukjent");
define("no_UPDATE_DEPARTMENT", "Oppdater avdeling");
define("no_UPDATE_ERROR", "Oppdater feil!");
define("no_UPDATED_SUCCESS", "Oppdatert!");
define("no_UPLOAD_DIR_INVALID", "opplastningskatalog feilet. Kontakt systemadmin.");
define("no_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "Bruk epost prioritet når tilgjengelig (e-supportsak)");
define("no_USERNAME_MISSING", "Brukernavn mangler");
define("no_USERNAME", "Brukernavn");
define("no_USERS", "Brukere");
define("no_VALID_EMAIL", "Gyldig epost");
define("no_VALID_PASS_REQ", "Gyldig passord kreves");
define("no_VIEW_STATUS", "Vis status");
define("no_WELCOME_BACK", "Velkommen tilbake! Du har status 'på ferie'. Vennligst la admin/avdelingsleder vite at du er tilbake.");
define("no_WELCOME_TO_SUPPORT_CENTER", "Velkommen til SupportCenter!");
define("no_YOU_ARE_NOT_ALLOWED", "Ikke tillatt");
define("no_YOU_HAVE_REACHED_MAX_TICKETS", "Du har nådd maksimum åpne supportsaker som er tillatt");
define("no_YOU_LL_NEED_TICKET_NUMBER", "Du trenger saksnummer sammen med registrert epostadresser for å vise status og fremdrift i vårt onlinecenter.");
define("no_YOU_MUST_CHANGE_PASS", "Du må endre passordet for å fortsette.");
define("no_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "Du må angi hosts to whitelist");
define("no_YOU_MUST_SELECT_ACTION_TO_PERFORM", "Du må velge handling som skal utføres");
define("no_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "Du må velge minst ett element");
define("no_YOU_MUST_SELECT_ONE_EMAIL", "Du må velge minst en e-postadresse");
define("no_YOU_MUST_SELECT", "Du må velge");
define("no_YOU_NEED_TO_SET_UPLOADDIR", "Du må sette opp opplastningskatalog.");
define("no_YOU_PIPE_WE_ACCEPT_POLICY", "You pipe we accept policy");
define("no_ZERO_RESULTS", "Søk ga ingen resultat");
