<?php
/*
 * Template language file for translation
 * Check http://go.zingiri.com/knowledgebase.php?action=displayarticle&id=1029 for translation instructions
 */
define("xx_A_DEPT", "a Dept.");
define("xx_A_PRIORITY", "a priority");
define("xx_ACCESS_DENIED", "Access Denied");
define("xx_ACTION_DENIED_TICKET_LOCKED", "Action Denied. Ticket is locked by someone else!");
define("xx_ACTION_DENIED", "Action Denied");
define("xx_ACTIVE", "Active");
define("xx_ADD_NEW_PREMADE_REPLY", "Add New Premade Reply");
define("xx_ADD_NEW_USER", "Add new user");
define("xx_ADMIN_EMAIL_GETS_AN_ALERT_BY_DEFAULT", "Admin Email gets an alert by default. Select additional recipients below");
define("xx_ADMIN_EMAIL", "Admin Email");
define("xx_ADMIN_PANEL", "Admin panel");
define("xx_ADVANCED", "Advanced");
define("xx_ALERT_FROM_EMAIL_ADDRESS", "Alert(s) FROM Email Address");
define("xx_ALERT_SUBJECT_MISSING", "Alert subject missing");
define("xx_ALERTS_NOTICES", "Alerts &amp; Notices");
define("xx_ALL_DEP", "All Department");
define("xx_ALL_DEPTS", "All Departments");
define("xx_ALL", "All");
define("xx_ALLOW_CLIENT_TO_OVERWRITE_PRIORITY", "Allow client to overwrite/set priority (online tickets)");
define("xx_ALLOWED_FILE_EXT_REQ", "Allowed file extentions required");
define("xx_ALLOWED", "allowed");
define("xx_AN_EMAIL_WITH_TICKET_HAS_BEEN_SENT", "An email with the ticket number has been sent to");
define("xx_ANOTHER_DEPT_USING_HOST_COMBINATION", "Another department using host/user combination.");
define("xx_ANSWER", "Answer");
define("xx_API_SETTINGS_UPDATED", "API settings updated");
define("xx_ARE_YOU_SURE_YOU_WANT", "Are you sure you want");
define("xx_ASSIGN", "assign");
define("xx_ASSIGNED_STAFF", "Assigned Staff");
define("xx_ASSIGNED_TICKETS", "Assigned Tickets");
define("xx_AT_LEAST_ONE_TOPIC", "at least one topic");
define("xx_ATTACH_FILE", "Attach file");
define("xx_ATTACH_SETTINGS_UPDATED", "Attachments settings updated");
define("xx_ATTACH", "Attachment");
define("xx_ATTACHMENT_DISABLED", "Attachments Disabled");
define("xx_ATTEMPTS", "Attempts");
define("xx_AUTHENTICATION_REQUIRED", "Authentication required");
define("xx_AUTOASSIGN_REOPENED_TICKETS_TO_LAST_RESPONDENT", "Auto-assign reopened tickets to last respondent 'available'. (<i> 3 months limit</i>)");
define("xx_AUTOLOCK_TIME", "Auto-lock time");
define("xx_AUTORESPONDERS_GLOBAL_SETTING", "Autoresponders &nbsp;(Global Setting)");
define("xx_AUTORESPONDERS", "Autoresponders");
define("xx_AUTORESPONSE_FROM_EMAIL", "Auto response FROM Email");
define("xx_AUTORESPONSE_INCLUDES_THE_TICKET_ID", "Autoresponse includes the ticket ID required to check status of the ticket");
define("xx_BAD_PREFIX_UNDERSCORE", "Bad prefix. Must have underscore (_) at the end. e.g 'ost_'");
define("xx_BAN_EMAIL_LOWER", "banemail");
define("xx_BYTES_ALLOWED", "bytes allowed");
define("xx_CAN_BE_APPENDED_TO_RESPONSES", "can be appended to responses.&nbsp;(available as a choice for public departments)  ");
define("xx_CAN_NOT_DEL_DEPT_ASSOCIATED_WITH_HELP_TOPICS", "Can not delete Dept. associated with a help topics. Remove association first.");
define("xx_CAN_NOT_DEL_DEPT_WITH_MEMBERS", "Can not delete Dept. with members. Move staff first.");
define("xx_CANCEL", "Cancel");
define("xx_CATEGORY", "Category");
define("xx_CELL_PHONE", "Cell phone");
define("xx_CHANGE_PASS", "Change password");
define("xx_CHANGE_PRIORITY", "change_priority");
define("xx_CHECK_STATUS_OPENED_TICKETS", "Check status of previously opened ticket. we provide archives and history of all your support requests complete with responses.");
define("xx_CHECK_STATUS", "Check Status");
define("xx_CLICKABLE_URL", "Clickable URLs");
define("xx_CLIENT_SESSION_TIMEOUT_IN_MINS", "Client's max Idle time in minutes. Enter 0 to disable timeout");
define("xx_CLIENT_SESSION_TIMEOUT", "Client Session Timeout");
define("xx_CLOSE_LOWER", "close");
define("xx_CLOSE_REOPEN_TICKETS", "close/reopen tickets");
define("xx_CLOSE", "Close");
define("xx_CLOSED", "Closed");
define("xx_COMMERCIAL_SUPPORT_AVAILABLE", "Commercial Support Available");
define("xx_CONF_FILE_ALREADY_MOD", "Configuration file already modified!");
define("xx_CONF_FILE_NOT_WRITABLE", "Configuration file is not writable");
define("xx_CONFIRM_NEW_PASS", "Confirm new password");
define("xx_CONFIRM", "Confirm");
define("xx_CONFLICTS_WITH_SYSTEM_EMAIL_ABOVE", "Conflicts with system email above");
define("xx_CONTACT_ADMIN", "Contact admin if you believe this is in error");
define("xx_CREATE_DATE", "Create Date");
define("xx_CURR_PASS_REQ", "Current password required");
define("xx_CURR_TIME", "Current time");
define("xx_DATE_AND_TIME_FORMAT", "Date &amp; Time Format");
define("xx_DATE_AND_TIME", "Date &amp; Time");
define("xx_DATE_FORMAT", "Date Format");
define("xx_DAY_DATE_TIME_FORMAT", "Day, Date &amp; Time Format");
define("xx_DAYLIGHT_SAVING", "Daylight Saving");
define("xx_DAYLIGHT_SAVINGS", "Daylight Savings");
define("xx_DB_NOT_EXISTS", "Database doesn't exist");
define("xx_DEFAULT_DEPARTMENT", "Default Department");
define("xx_DEFAULT_EMAIL_TEMPLATE", "Default Email Template");
define("xx_DEFAULT_EMAIL", "Default Email");
define("xx_DEFAULT_PAGE_SIZE", "Default page size");
define("xx_DEFAULT_PRIORITY", "Default priority");
define("xx_DEFAULT_TIMEZONE", "Default Timezone");
define("xx_DELETE_DEPS", "Delete depts");
define("xx_DELETE_LOWER", "delete");
define("xx_DELETE_TICKETS", "delete tickets");
define("xx_DELETE", "Delete");
define("xx_DEPARTMENT_MANAGED", "Department Manager (spammy)");
define("xx_DEPARTMENT_MANAGER", "Department Manager");
define("xx_DEPARTMENT_MEMBERS", "Department Members (spammy)");
define("xx_DEPARTMENT_UNDER_WHICH_THE_ANSWER_WILL_BE_MADE_AVAILABLE", "Department under which the 'answer' will be made available");
define("xx_DEPARTMENTS", "Departments");
define("xx_DEPENDS_ON_THE_TAG_BELOW", "depends on the tag below");
define("xx_DEPT_DEPENDS_ON_EMAIL", "Dept depends on email &amp; help topics settings for incoming tickets.");
define("xx_DEPT_EMAIL_ABOVE", "Dept Email (above)");
define("xx_DEPT_EMAIL", "Dept email");
define("xx_DEPT_MANAGER", "Dept Manager");
define("xx_DEPT_NAME", "Department name");
define("xx_DEPT_SIGNATURE", "Dept Signature");
define("xx_DEPT_TRANSFER", "Dept. Transfer");
define("xx_DEPT_TYPE", "Dept Type");
define("xx_DEPT", "Department");
define("xx_DIR_MUST_BE_VALID_WRITABLE", "Directory must be valid and writeable");
define("xx_DIRECTORY", "Directory");
define("xx_DISABLE", "Disable");
define("xx_DISABLED", "Disabled");
define("xx_DO_REQUESTED_ACTION", "do requested action");
define("xx_EDIT_PREMADE_REPLY", "Edit Premade Reply");
define("xx_EMAIL_ADD_SUCCESS", "Email added successfully");
define("xx_EMAIL_ADDED_TO_BANLIST", "Email added to banlist");
define("xx_EMAIL_ADDRESS", "Email address");
define("xx_EMAIL_ALREADY_BANNED", "Email already banned");
define("xx_EMAIL_ALREADY_EXISTS", "Email already exists");
define("xx_EMAIL_IN_BANLIST", "Email is in banlist. Must be removed to reply");
define("xx_EMAIL_MISMATCH", "Email mismatch.");
define("xx_EMAIL_REMOVED", "Email removed");
define("xx_EMAIL_SETTINGS", "Email Settings");
define("xx_EMAIL_UNKNOWN", "Email unknown");
define("xx_EMAIL_UPDATED_SUCCESS", "Email updated successfully");
define("xx_ENABLE_AUTOCRON", "Enable Auto Cron");
define("xx_ENABLE_CRON_CALL", "Enable cron call on staff's activity");
define("xx_ENABLE_EMAIL_PIPING", "Enable email piping");
define("xx_ENABLE_POP3_EMAIL_FETCH", "Enable POP3 email fetch");
define("xx_ENABLE", "Enable");
define("xx_ENABLED_ERRORS_ARE_SENT_TO_ADMIN_EMAIL_SET_ABOVE", "Enabled errors are sent to admin email set above");
define("xx_ENTER_MESSAGE", "Enter Message");
define("xx_ENTER_VALID_NUM", "Enter a valid number");
define("xx_ERR_SQL_SYNTAX", "You have an error in your SQL syntax ");
define("xx_ERROR_OCCURED", "Error(s) occured.");
define("xx_ERROR_OCCURRED", "Error occured. See error messages below.");
define("xx_EXCESSIVE_LOGIN_ATTEMPTS", "Excessive Login attempts");
define("xx_FATAL_ERROR", "Fatal Error");
define("xx_FETCH_INTERVAL_REQUIRE", "Fetch interval required");
define("xx_FILE_TOO_BIG", "File is too big");
define("xx_FILE_UPLOAD_DISABLED_PHP_INI", "The 'file_uploads' directive is disabled in php.ini");
define("xx_FIRST_NAME", "First name");
define("xx_FOR_POP3_MAIL_FETCH_TO_WORK_YOU_MUST_SET_A_CRON_JOB", "For POP3 mail fetch to work you must set a cron job or simply enable auto-cron");
define("xx_FORGOT_LOGIN_INFO", "Forgot your login info? Please <a href=\"open.php\">open a new ticket</a>.");
define("xx_FROM_BANLIST", "from banlist");
define("xx_FULL_NAME", "Full Name");
define("xx_GENERAL_INQUIRY", "General Inquiry");
define("xx_GENERAL_SETTINGS", "General Settings");
define("xx_GET_A_PEACE_OF_MIND", "Get a peace of mind");
define("xx_GLOBAL_AUTORESPONDER_IN_PREFERENCE_SECTION", "Global autoresponder in preference section must be enabled for Dept 'Enable' setting to take effect.");
define("xx_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_EMAIL_LEVEL", "Global setting which can be disabled at email level");
define("xx_HELP_TOPIC", "Help Topic");
define("xx_HELPDESK_NAME", "Helpdesk Name/Title");
define("xx_HELPDESK_STATUS", "Helpdesk Status");
define("xx_HELPDESK_URL", "Helpdesk URL");
define("xx_HELPS_WITH_SPAM", "Helps with spam and flood control. Enter 0 for unlimited");
define("xx_HOME", "Home");
define("xx_HOST_MISSING", "Host missing");
define("xx_HOURS_BEFORE_TICKET_IS_MARKED_OVERDUE", "Hours before ticket is marked overdue. Enter 0 to disable aging");
define("xx_IF_ENABLE_TICKET_LOCK_GET_AUTORENEWED", "If enabled ticket lock get auto-renewed on form activity.");
define("xx_IF_YOU_WISH_TO_SEND_ADDITIONAL_COMMENTS", "If you wish to send additional comments or information regarding same issue, please follow the instructions on the email.");
define("xx_IMAP_DOESNT_EXISTS", "IMAP doesn't exist. PHP must be compiled with IMAP enabled.");
define("xx_IN_ORDER_TO_STREAMLINE_SUPPORT_REQUESTS", "In order to streamline support requests and better serve you, we utilize a support ticket system. Every support request is assigned a unique ticket number which you can use to track the progress and responses online. For your reference we provide complete archives and history of all your support requests.");
define("xx_INDICATE_SOURCE", "Indicate source");
define("xx_INSTALL_COMPLETE", "Congratulations osTicket basic installation completed!");
define("xx_INTERNAL_ERROR_OCCURED", "Internal error occured");
define("xx_INTERNAL_ERROR", "Internal error. Please make sure your download is the latest");
define("xx_INTERNAL_NOTE_POSTED", "Internal note posted");
define("xx_INVALID_ATTACH", "Invalid Attachment");
define("xx_INVALID_FILE_TYPE", "Invalid file type");
define("xx_INVALID_FILE", "Invalid file");
define("xx_INVALID_LOGIN", "Invalid login");
define("xx_INVALID_SOURCE", "Invalid source");
define("xx_INVALID_SQL_SCHEMA", "Invalid SQL schema. Get help from Developers");
define("xx_INVALID_UPLOAD_DIR", "Invalid upload dir");
define("xx_INVALID", "Invalid");
define("xx_KNOWLEDGE_BASE", "Knowledge base");
define("xx_LANG_PRIVATE", "Private");
define("xx_LANG_PUBLIC", "Public");
define("xx_LAST_NAME", "Last name");
define("xx_LAST_RESPONDENT", "Last Respondent");
define("xx_LAST_UPDATED", "Last updated");
define("xx_LOCK", "Lock");
define("xx_LOCKED", "Locked");
define("xx_MAIL_METH", "Mail Methods");
define("xx_MAIL_PARSE_ERRORS", "Mail Parse Errors");
define("xx_MAKE_PRIVATE", "Make private");
define("xx_MAKE_PUBLIC", "Make public");
define("xx_MAKE_URL_CLICKABLE", "Make URLs clickable");
define("xx_MANAGER", "Manager");
define("xx_MASS_MANAGE_TICKETS", "mass manage tickets. Contact admin for such access");
define("xx_MAX_ALLOWED", "Max Allowed");
define("xx_MAX_FILE_SIZED_REQ", "Maximum file size required");
define("xx_MAX_LOGIN_ATTEMPTS", "You've reached maximum failed login attempts allowed. Try again after 5 minutes or <a href=\"open.php\">open a new ticket</a>");
define("xx_MAX_OPEN_TICKETS", "Maximum <b>Open</b> Tickets");
define("xx_MAX_PAGE_SIZE", "Maximum page size");
define("xx_MESSAGE_APPENDED_TO_AN_EXISTING_TICKET_CONFIRMATION", "Message appended to an existing ticket confirmation");
define("xx_MESSAGE_POSTED_SUCCESS", "Message Posted Successfully");
define("xx_MESSAGE_REQUIRED", "Message required");
define("xx_MESSAGE", "Message");
define("xx_MIN_TO_LOCK_A_TICKET", "Minutes to lock a ticket on activity. Enter 0 to disable locking");
define("xx_MISSING_MESSAGE", "Missing message ID");
define("xx_MISSING_OR_INVALID_GROUP", "Missing or invalid group");
define("xx_MISSING_SQL_SCHEMA", "Missing SQL schema");
define("xx_MOBILE", "Mobile");
define("xx_MUST_BE_SIX_CHARS", "Must be at least 6 characters");
define("xx_MUST_SELECT_PRIORITY", "You must select priority");
define("xx_MY_ACCOUNT", "My Account");
define("xx_MY_PREFERENCES", "My Preferences");
define("xx_MY_PROFILE_INFO", "My Profile Info");
define("xx_MY_PROFILE", "My Profile");
define("xx_NAME", "Name");
define("xx_NEED_HELP_QUESTION", "Need help?");
define("xx_NEW_DEPT", "New Department");
define("xx_NEW_MESSAGE_ALERT", "New Message Alert");
define("xx_NEW_MESSAGE", "New message");
define("xx_NEW_PASS_NOT_MATCH", "New password(s) don't match");
define("xx_NEW_PASS_REQ", "New password required");
define("xx_NEW_PASS_SAME_OLD", "New password is same as old password");
define("xx_NEW_PREMADE_REPLY", "New Premade Reply");
define("xx_NEW_TICKET_ALERT", "New Ticket Alert");
define("xx_NEW_TICKET", "New ticket");
define("xx_NO_ACCESS_TO_TICKET", "You do not have access to the ticket");
define("xx_NO_PERMISSION_TO_REASSIGN", "You do not have permission to re-assign assigned tickets");
define("xx_NO_PERMISSION_TO", "You do not have permission to");
define("xx_NO_REPLY_EMAIL_ADDRESS", "No Reply Email Address");
define("xx_NO_REPLY_EMAIL", "No Reply email");
define("xx_NO_STAFF_FOUND", "No staff found");
define("xx_NO_SUCH_FILE", "No such file");
define("xx_NO_TICKETS_FOUND", "NO tickets found.");
define("xx_NO_TICKETS_SELECTED", "No tickets selected. You must select at least one ticket.");
define("xx_NO_USER_ADD_USER", "No Users (Add Users)");
define("xx_NONE", "None");
define("xx_NOT_ALLOWED_TO_CHANGE_TICKET_PRIORITY", "You are not allowed to change ticket's priority");
define("xx_NOT_ALLOWED_TO_TRANSFER_TICKETS", "You are not allowed to transfer tickets.");
define("xx_NOTE_REQ", "Note message required");
define("xx_NOTE_REQUIRED", "Note/Message required");
define("xx_NOTICES_SENT_TO_USER_USE_NO_REPLY_EMAIL", "Notices sent to user use 'No Reply Email' whereas alerts to staff use 'Alert Email' set above as FROM address respectively.");
define("xx_OBSERVE", "Observe");
define("xx_OF", "di");
define("xx_OFFICE_PHONE", "Office phone");
define("xx_OFFLINE_MODE_WILL_DISABLE_CLIENT_INTERFACE", "Offline mode will disable client interface and <b>only</b> allow <b>super admin</b> to login to Staff Control Panel");
define("xx_OFFLINE", "Offline");
define("xx_ONLINE", "Online");
//define("xx_OPEN_LOWER", "open");
define("xx_OPEN_NEW_TICKET", "Open New Ticket");
define("xx_OPEN_TICKET", "Open Ticket");
define("xx_OPEN", "Open");
define("xx_OSTICKET_BASIC_INSTALL", "osTicket Basic Installation");
define("xx_OSTICKET_INSTALLER", "osTicket Installer");
define("xx_OSTICKET_REQUIRES_MYSQL", "osTicket requires MySQL 4.1.1 or better! Please upgrade");
define("xx_OUTGOING_EMAIL", "Outgoing Email");
define("xx_OVERDUE_LOWER", "overdue");
define("xx_OVERDUE_TICKET_ALERT", "Overdue Ticket Alert");
define("xx_OVERLIMIT_NOTICE", "Overlimit Notice");
//define("xx_PAGE", "page");
define("xx_PASS_CHANGE_SUCCESS", "Password Changed Successfully");
define("xx_PASS_TO_NOT_MATCH", "passwords to not match!");
define("xx_PASSWORD_REQUIRED", "Password required");
define("xx_PER_EMAIL", "per email");
define("xx_PERM_DENIED", "Perm. Denied.");
define("xx_PHONE_NUM_REQ", "Phone # required");
define("xx_PHONE", "Phone");
define("xx_PHP_DATE_MANUAL", "Please refer to <a href=\"http://php.net/date\" target=\"_blank\">PHP Manual</a> for supported parameters.");
define("xx_PHP_OUT_OF_DATE", "PHP installation seriously out of date");
define("xx_PHRASE_TOO_SHORT", "phrase is too short!");
define("xx_PHRASE_TWO_WORDS", "Phrase of 2+ words");
define("xx_PLEASE_ENTER_VALID_EMAIL", "Please enter a valid email.");
define("xx_PLEASE_FILL_TO_OPEN_A_TICKET", "Please fill in the form below to open a new ticket.");
define("xx_POSSIBLE_ERROR_DETECTED", "Possible errors detected, please check the warnings below");
define("xx_POSSIBLY_ACCESS_DENIED", "Possibly access denied, if you believe this is in error please get technical support.");
define("xx_POSSIBLY_INVALID_TICKET", "Possibly invalid ticket ID");
define("xx_POST_REPLY", "Post Reply");
define("xx_POSTNOTE", "postnote");
define("xx_PREF_ERROR", "Preference update error.");
define("xx_PREF_UPDATED", "Preferences Updated Successfully");
define("xx_PREFERENCES", "Preferences");
define("xx_PREFERRED_TIMEZONE", "Preferred Timezone");
define("xx_PREMADE_REPLIES", "Premade Replies");
define("xx_PREMADE_REPLY", "Premade Reply");
define("xx_PRIMARY_OUTGOING_MAIL", "Primary Outgoing Email");
define("xx_PRIORITY_CHANGED_SUCCESS", "Priority Changed Successfully");
define("xx_PRIORITY", "Priority");
define("xx_PRIVATE_HIDDEN", "Private (Hidden)");
define("xx_PROBLEM_CHANGING_PRIORITY", "Problems changing priority.");
define("xx_PROBLEM_CLOSING_TICKET", "Problems closing the ticket.");
define("xx_PROBLEM_RELEASING_TICKET", "Problems releasing the ticket.");
define("xx_PROBLEM_REOPENING_TICKET", "Problems reopening the ticket.");
define("xx_PROBLEMS_ADMIN_PAGE", "Problems loading requested admin page.");
define("xx_PROBLEMS_DELETING_THE_TICKET", "Problems deleting the ticket");
define("xx_PROBLEMS_DISPLAYING_DIR", "Problems displaying directory");
define("xx_PROBLEMS_MARKING_THE_TICKET_OVERDUE", "Problems marking the the ticket overdue");
define("xx_PROCESS", "process");
define("xx_PROF_INST_AVAILABLE", "Professional Installation Available");
define("xx_PROFILE_UPDATE_SUCCESS", "Profile Updated Successfully");
define("xx_PUBLIC", "Public");
define("xx_QUERY", "Query");
define("xx_RANDOM", "Random");
define("xx_RECOMMENDED", "recommended");
define("xx_REJECTED", "rejected");
define("xx_RELEASE_LOWER", "release");
define("xx_REMOVING_QUOTED_REPLY", "Removing quoted reply");
define("xx_REOPEN_LOWER", "reopen");
define("xx_REOPEN", "Reopen");
define("xx_REOPENED_TICKETS", "Reopened tickets");
define("xx_REPLY_REQUIRED", "Reply required");
define("xx_REPLY_SEPARATOR_TAG", "Reply Separator Tag");
define("xx_REPLY_TITLE", "Reply Title");
define("xx_REPLY", "reply");
define("xx_REQUIRED_WHEN_DEPT_IS_PUBLIC", "Required when Dept is public");
define("xx_REQUIRED", "required");
define("xx_RESET_CHANGES", "Reset Changes");
define("xx_RESET", "Reset");
define("xx_RESPONSE_MESSAGE_REQUIRED", "Response message required");
define("xx_RESPONSE_POSTED_SUCCESS", "Response Posted Successfully");
define("xx_SALVE_EMAIL_HEADERS", "Save Email Headers");
define("xx_SAVE_CHANGES", "Save Changes");
define("xx_SAVE_RAW_HEADERS", "Save raw headers");
define("xx_SAVE", "Save");
define("xx_SEARCH_FOR", "Search for");
define("xx_SEARCH_TERM_MORE_THAN_3_CHARS", "Search term must be more than 3 chars");
define("xx_SEARCH", "Search");
define("xx_SECURITY_VIOLATION", "Security violation. Repeated violations will result in your account being locked.");
define("xx_SELECT_ASSIGNEE", "Select assignee");
define("xx_SELECT_DEFAULT_DEPT", "Select Default Dept");
define("xx_SELECT_DEPARTMENT", "Select Department");
define("xx_SELECT_HELP_TOPIC", "Select help topic");
define("xx_SELECT_MANAGER_OPT", "Select Manager (optional)");
define("xx_SELECT_ONE", "Select one");
define("xx_SELECT_RECIPIENTS", "Select recipients");
define("xx_SELECT", "Select");
define("xx_SELECTED_DEPT_DELETED", "selected departments deleted");
define("xx_SELECTED_EMAILS_DELETED", "selected email(s) deleted");
define("xx_SELECTED_EMAILS_REMOVED", "selected emails removed from banlist");
define("xx_SELECTED_EMAILS_USED_BY_A_DEPT", "One or more of the selected emails is being used by a Dept. Remove association first.");
define("xx_SELECTED_ENTRIES", "selected entries");
define("xx_SELECTED_REPLIES_DELETED", "Selected replies deleted");
define("xx_SELECTED_REPLIES_DISABLED", "Selected replies disabled");
define("xx_SELECTED_REPLIES_ENABLED", "Selected replies enabled");
define("xx_SELECTED_SERVICES_ENABLED", "selected services enabled");
define("xx_SELECTED_TICKETS_CLOSED", "selected tickets closed");
define("xx_SELECTED_TICKETS_DELETED", "selected tickets deleted");
define("xx_SELECTED_TICKETS_OVERDUE", "selected tickets marked overdue");
define("xx_SELECTED_TICKETS_REOPENED", "selected tickets reopened");
define("xx_SELECTED_TICKETS", "selected tickets");
define("xx_SELECTED_TOPIC_DISABLED", "selected topics disabled");
define("xx_SELECTED_TOPICS_DELETED", "selected topics deleted");
define("xx_SELECTED_USERS", "selected user(s)");
define("xx_SEND_OVERLIMIT_NOTICE", "Send overlimit notice");
define("xx_SENT_ONLY_ONCE", "Sent <b>only once</b> on limit violation to the user. <b>Admin gets alerts on ALL denials by default</b>");
define("xx_SEQUENTIAL", "Sequential");
define("xx_SERVER_TIME", "Server time");
define("xx_SESSION_TIMED_OUT", "Session timed out due to inactivity");
define("xx_SHOW_ASSIGNED_TICKETS", "Show assigned tickets on open queue");
define("xx_SHOWING", "Showing");
define("xx_SIGNATURE", "Signature");
define("xx_SORT_BY", "Sort by");
define("xx_SQL_ERRORS", "SQL errors");
define("xx_STAFF_MAX_IDLE_TIME", "Staff's max Idle time in minutes. Enter 0 to disable timeout");
define("xx_STAFF_MEMBERS", "Staff Members");
define("xx_STAFF_PANEL", "Staff panel");
define("xx_STAFF_SESSION_TIMEOUT", "Staff Session Timeout");
define("xx_STATUS", "Status");
define("xx_STRIP_QUOTED_REPLY", "Strip Quoted Reply");
define("xx_SUBJECT_MISSING", "subject missing");
define("xx_SUBJECT", "Subject");
define("xx_SUBMIT_A_NEW_REQUEST", "Submit a new support request. Please provide as much detail as possible so we can best assist you. To update a previously submitted ticket, please use the form to the right. A valid email address is required.");
define("xx_SUMMARY_OF_THE_ISSUE_REQUIRED", "Summary of the issue required");
define("xx_SUPPORT_OFFLINE", "Support ticket system is offline");
define("xx_SUPPORT_TEAM", "Support Team ");
define("xx_SUPPORT_TICKET_CREATED", "Support ticket request created");
define("xx_SUPPORT_TICKET_REQ_DENIED_FOR", "Support ticket request denied for");
define("xx_SUPPORT_TICKET_SYSTEM", "Support ticket system");
define("xx_SYSTEM_ADMIN_EMAIL_ADDRESS", "System Admin Email Address");
define("xx_SYSTEM_ERRORS", "System Errors");
define("xx_SYSTEM_OFFLINE", "System offline");
define("xx_SYSTEM_PREFERENCES_AND_SETTINGS", "System Preferences and Settings");
define("xx_TABLE_PREFIX", "Table prefix");
define("xx_TEMPLATE_ALERT_MSG_REQUIRED", "Template alert message required");
define("xx_TEMPLATE_MSG_REQUIRED", "Template message required");
define("xx_TEMPLATES_UPDATED_SUCCESS", "Templates updated successfully");
define("xx_THANK_YOU_FOR_CHOOSING_OSTICKET", "Thank you for choosing osTicket.\nMake sure you join osTicket forums http://osticket.com/forums to stay upto date on the latest news, security alerts and updates. osTicket forums is also a great place to get assistance, guidance and help. In addition to the forums, osTicket wiki provides useful collection of educational materials, documentation, and notes from the community.\n\n If you are looking for greater level of support, we provide professional services and custom commercial support with guaranteed response times and access to the core development team. We can also customize the system to meet your unique needs.\nFor more information or to discuss your needs, please contact us today. Any feedback will be appreciated!\nosTicket Team");
define("xx_THANK_YOU_FOR_CONTACTING_US", "Thank you for contacting us.<br>A support ticket request has been created and a representative will be getting back to you shortly if necessary.");
define("xx_THANK_YOU_HELPDESK_OFFLINE", "Thank you for your interest in contacting us.<br>Our helpdesk is offline at the moment, please check back at a later time.");
define("xx_THIS_IS_GLOBAL_SETTING_WHICH_CAN_BE_DISABLED_AT_DEPARTMENT_LABEL", "This is global setting which can be disabled at department level");
define("xx_TICKET_ALREADY_ASSIGNED_TO_THE_STAFF", "Ticket already assigned to the staff.");
define("xx_TICKET_ALREADY_ASSIGNED" , "Ticket already assigned.");
define("xx_TICKET_ALREADY_IN_DEPT", "Ticket already in the Dept.");
define("xx_TICKET_ASSIGNED_TO_THE_STAFF", "Ticket Assigned to staff");
define("xx_TICKET_CREATED_BY_STAFF", "Ticket created by staff");
define("xx_TICKET_CREATED_SUCCESS", "Ticket created successfully");
define("xx_TICKET_DELETED_FOREVER", "Ticket Deleted Forever");
define("xx_TICKET_DENIED_403", "Ticket denied Error #403");
define("xx_TICKET_DENIED_NOTICE", "Ticket Denied Notice");
define("xx_TICKET_FLAGGED_AS_OVERDUE", "Ticket flagged as overdue");
define("xx_TICKET_GRACE_PERIOD", "Ticket Grace Period");
define("xx_TICKET_ID", "Ticket IDs");
//define("xx_TICKET_LOWER", "ticket");
define("xx_TICKET_NOT_ASSIGNED", "Ticket is not assigned!");
define("xx_TICKET_OPTIONS_AND_SETTINGS", "Ticket Options &amp; Settings");
define("xx_TICKET_PRIORITY", "Ticket Priority");
define("xx_TICKET_RELEASED_FROM", "Ticket released (unassigned) from");
define("xx_TICKET_STATUS_SET_TO", "Ticket status set to");
define("xx_TICKET_STATUS", "Ticket status");
define("xx_TICKET_TRANSFER", "Ticket Transfered Successfully");
define("xx_TICKET_WILL_BE_REOPENED", "Ticket will be reopened on message post");
define("xx_TICKETS_PER_PAGE", "Tickets/items per page");
//define("xx_TICKETS", "Tickets");
define("xx_TIME_FORMAT", "Time Format");
define("xx_TITLE_ALREADY_EXISTS", "Title already exists");
define("xx_TITLE_REQ", "Title required");
define("xx_TITLE_REQUIRED", "Title required");
define("xx_TITLE", "Title");
define("xx_TO_BAN_EMAILS", "to ban emails");
define("xx_TO_CLOSE", "to close");
define("xx_TO_DELETE_SELECTED_DEPTS", "to delete selected depts");
define("xx_TO_DELETE_TICKETS", "to delete tickets");
define("xx_TO_DELETE", "to delete");
define("xx_TO_DISABLE", "to disable");
define("xx_TO_ENABLE", "to enable");
define("xx_TO_FLAG_TICKETS_OVERDUE", "to flag tickets overdue");
define("xx_TO_LOCK", "to lock");
define("xx_TO_MAKE_SELECTED_DEPTS_PRIVATE", "to make selected depts private");
define("xx_TO_MAKE_SELECTED_DEPTS_PUBLIC", "to make selected depts public");
define("xx_TO_MARK_SELECTED_TICKETS_OVERDUE", "to mark selected tickets overdue/stale");
define("xx_TO_REM_EMAILS_FROM_BANLIST", "remove emails from banlist.");
define("xx_TO_REOPEN", "to reopen");
define("xx_TO_VIEW_THE_STATUS_OF_A_TICKET", "To view the status of a ticket, provide us with your login details below.<br/>If this is your first time contacting us or you've lost the ticket ID, please <a href=\"open.php\">click here</a> to open a new ticket.");
define("xx_TO", "to");
define("xx_TOGGLE", "Toggle");
define("xx_TOPIC_TOO_SHORT", "Topic is too short. 5 chars minimum");
define("xx_TRANSFER", "transfer");
define("xx_TRY_AGAIN", "Try again");
define("xx_TYPE", "Type");
define("xx_UNABLE_TO_ADD_EMAIL_TO_BANLIST", "Unable to add the email to banlist");
define("xx_UNABLE_TO_ADD_EMAIL", "Unable to add email. Internal error");
define("xx_UNABLE_TO_ADD_MAIL_TO_BANLIST", "Unable to add email to banlist. Try again");
define("xx_UNABLE_TO_ASSIGN_TICKET", "Unable to assign the ticket");
define("xx_UNABLE_TO_COMPLETE_ACTION", "Unable to complete action");
define("xx_UNABLE_TO_COMPLETE_PASS_CHANGE", "Unable to complete password change. Internal error.");
define("xx_UNABLE_TO_COMPLETE_THE_TRANSFER", "Unable to complete the transfer");
define("xx_UNABLE_TO_CONNECT_MYSQL", "Unable to connect to MySQL server. Possibly invalid login info. <br>");
define("xx_UNABLE_TO_CREATE_DB", "Unable to create the database due to permission");
define("xx_UNABLE_TO_CREATE_THE_REPLY", "Unable to create the reply. Internal error");
define("xx_UNABLE_TO_CREATE_TICKET", "Unable to create the ticket. Correct the error(s) and try again");
define("xx_UNABLE_TO_DELETE_SELECTED_DEPT", "Unable to delete selected departments.");
define("xx_UNABLE_TO_DELETE_SELECTED_EMAILS", "Unable to delete selected email(s).");
define("xx_UNABLE_TO_DISABLE_SELECTED_TOPICS", "Unable to disable selected topics");
define("xx_UNABLE_TO_FETCH_INFO_ON", "Unable to fetch info on");
define("xx_UNABLE_TO_MAKE_REMOVE_SELECTED_EMAILS", "Unable to make remove selected emails");
define("xx_UNABLE_TO_MAKE_SELECTED_DEPT_PRIVATE", "Unable to make selected department(s) private. Possibly already private!");
define("xx_UNABLE_TO_OPEN_CONF_FILE", "Unable to open config file for writting. Permission denied!");
define("xx_UNABLE_TO_POST_RESPONSE", "Unable to post the response.");
define("xx_UNABLE_TO_POST_THE_MESSAGE", "Unable to post the message");
define("xx_UNABLE_TO_POST_THE_NOTE", "Unable to post the note.");
define("xx_UNABLE_TO_REMOVE_EMAIL", "Unable to remove the email");
define("xx_UNABLE_TO_SELECT_DB", "Unable to select the database");
define("xx_UNABLE_TO_UPDATE_EMAIL", "Unable to update email. Internal error occured");
define("xx_UNBAN_EMAIL_LOWER", "unbanemail");
define("xx_UNKNOWN_ACTION", "Unknown action");
define("xx_UNKNOWN_BANLIST_COMMAND", "Uknown banlist command!");
define("xx_UNKNOWN_COMMAND", "Uknown command!");
define("xx_UNKNOWN_DEPT_ACTION", "Unknown Dept action");
define("xx_UNKNOWN", "Unknown");
define("xx_UPDATE_DEPARTMENT", "Update Department");
define("xx_UPDATE_ERROR", "Update error!");
define("xx_UPDATED_SUCCESS", "updated successfully");
define("xx_UPLOAD_DIR_INVALID", "upload dir invalid. Contact admin.");
define("xx_USE_EMAIL_PRIORITY_WHEN_AVAILABLE", "Use email priority when available (emailed tickets)");
define("xx_USERNAME_MISSING", "Username missing");
define("xx_USERNAME", "Username");
define("xx_USERS", "Users");
define("xx_VALID_EMAIL", "Valid email");
define("xx_VALID_PASS_REQ", "Valid password required");
define("xx_VIEW_STATUS", "View Status");
define("xx_WELCOME_BACK", "Welcome back! You are listed as 'on vacation' Please let admin or your manager know that you are back.");
define("xx_WELCOME_TO_SUPPORT_CENTER", "Welcome to the support center.");
define("xx_YOU_ARE_NOT_ALLOWED", "You are not allowed");
define("xx_YOU_HAVE_REACHED_MAX_TICKETS", "You've reached the maximum open tickets allowed.");
define("xx_YOU_LL_NEED_TICKET_NUMBER", "You'll need the ticket number along with your email to view status and progress online.");
define("xx_YOU_MUST_CHANGE_PASS", "You must change your password to continue.");
define("xx_YOU_MUST_ENTER_HOSTS_TO_WHITELIST", "You must enter hosts to whitelist");
define("xx_YOU_MUST_SELECT_ACTION_TO_PERFORM", "You must select action to perform");
define("xx_YOU_MUST_SELECT_AT_LEAST_ONE_ITEM", "You must select at least one item");
define("xx_YOU_MUST_SELECT_ONE_EMAIL", "You must select at least one email");
define("xx_YOU_MUST_SELECT", "You must select");
define("xx_YOU_NEED_TO_SET_UPLOADDIR", "You need to setup upload dir.");
define("xx_YOU_PIPE_WE_ACCEPT_POLICY", "You pipe we accept policy");
define("xx_ZERO_RESULTS", "Query returned 0 results");
